snippet apk
alias alp al apk
  apk --update --no-cahe add \
    && ${0:packages} \

snippet ENTRYPOINT
alias en ent entry entr
  ENTRYPOINT ["mysql"]

snippet ENV
alias env envi
  ENV {1:FOO="bar"}



