# Autogenerated config.py
# Documentation:
#   qute://help/configuring.html
#   qute://help/settings.html

# Uncomment this to still load settings configured via autoconfig.yml
# config.load_autoconfig()

# Name of the session to save by default. If this is set to null, the
# session which was last loaded is saved.
# Type: SessionName
c.session.default_name = 'LastSession.qt'

# Load a restored tab as soon as it takes focus.
# Type: Bool
c.session.lazy_restore = True

# Always restore open sites when qutebrowser is reopened.
# Type: Bool
c.auto_save.session = True

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'file://*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'chrome://*/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'qute://*/*')

# Allow locally loaded documents to access remote URLs.
# Type: Bool
c.content.local_content_can_access_remote_urls = True

# Allow websites to show notifications.
# Type: BoolAsk
# Valid values:
#   - true
#   - false
#   - ask
config.set('content.notifications', False, 'https://www.reddit.com')

# Directory to save downloads to. If unset, a sensible OS-specific
# default is used.
# Type: Directory
c.downloads.location.directory = '~/Downloads'

# Default program used to open downloads. If null, the default internal
# handler is used. Any `{}` in the string will be expanded to the
# filename, else the filename will be appended.
# Type: String
c.downloads.open_dispatcher = None

# Characters used for hint strings.
# Type: UniqueCharString
c.hints.chars = 'asdwerxcv'

# Open new tabs (middleclick/ctrl+click) in the background.
# Type: Bool
c.tabs.background = True

# Position of new tabs which are not opened from another tab. See
# `tabs.new_position.stacking` for controlling stacking behavior.
# Type: NewTabPosition
# Valid values:
#   - prev: Before the current tab.
#   - next: After the current tab.
#   - first: At the beginning.
#   - last: At the end.
c.tabs.new_position.unrelated = 'next'

# Default monospace fonts. Whenever "monospace" is used in a font
# setting, it's replaced with the fonts listed here.
# Type: Font
c.fonts.monospace = '"xos4 Terminus", Terminus, Monospace, "DejaVu Sans Mono", Monaco, "Bitstream Vera Sans Mono", "Andale Mono", "Courier New", Courier, "Liberation Mono", monospace, Fixed, Consolas, Terminal'

# Font used in the completion widget.
# Type: Font
c.fonts.completion.entry = '12pt dejavu sans mono'

# Font used in the completion categories.
# Type: Font
c.fonts.completion.category = 'bold 13pt dejavu sans mono'

# Font used for the debugging console.
# Type: QtFont
c.fonts.debug_console = '13pt dejavu sans mono'

# Font used for the downloadbar.
# Type: Font
c.fonts.downloads = '13pt dejavu sans mono'

# Font used for the hints.
# Type: Font
c.fonts.hints = 'bold 14pt dejavu sans mono'

# Font used in the keyhint widget.
# Type: Font
c.fonts.keyhint = '14pt dejavu sans mono'

# Font used for error messages.
# Type: Font
c.fonts.messages.error = '13pt dejavu sans mono'

# Font used for info messages.
# Type: Font
c.fonts.messages.info = '13pt dejavu sans mono'

# Font used for warning messages.
# Type: Font
c.fonts.messages.warning = '13pt dejavu sans mono'

# Font used for prompts.
# Type: Font
c.fonts.prompts = '11pt dejavu sans mono'

# Font used in the statusbar.
# Type: Font
c.fonts.statusbar = '11pt dejavu sans mono'

# Font used in the tab bar.
# Type: QtFont
c.fonts.tabs = '12pt dejavu sans mono'

# Load qutebrowser/autoconfig.yml
config.load_autoconfig()
