#### Required
[[plugins]]
repo = 'Shougo/dein.vim'

### Async Processor
[[plugins]]
# run vim-plugins asynchronously, inc., quickrun.
repo = 'Shougo/vimproc.vim'
build = 'make'

### Run Code on vim
[[plugins]]
repo = 'thinca/vim-quickrun'
hook_add = '''
  let g:quickrun_config = {}
  let g:quickrun_config['markdown'] = {
    \ 'outputter': 'browser'
    \ }
  '''

### Start Page
[[plugins]]
repo = 'mhinz/vim-startify'

### Filer
[[plugins]]
repo = 'kristijanhusak/defx-git'
depends = 'defx.nvim'
[[plugins]]
repo = 'kristijanhusak/defx-icons'
depends = 'defx.nvim'
[[plugins]]
repo = 'Shougo/defx.nvim'
#### Plugins Visual
## Color Themes
[[plugins]]
repo = 'tomasr/molokai'
hook_post_update = '''
  !ln -sfn $XDG_CACHE_HOME/nvim/dein/repos/github.com/tomasr/molokai/colors/molokai.vim
  '''
#[[plugins]]
#repo = 'altercation/vim-colors-solarized'

## Status Bar
#[[plugins]]
#repo = 'itchyny/lightline.vim' # config is written in 'plugin.vim'
[[plugins]]
repo = 'vim-airline/vim-airline'
[[plugins]]
repo = 'vim-airline/vim-airline-themes'
depends = 'vim-airline'

#[[plugins]]
## Show marks
#repo = 'jacquesbh/vim-showmarks'

#[[plugins]]
#repo = 'tyru/qfpopup.vim'
