# From: dein.vimrc

# Colorscheme; Collection
[[plugins]]
repo = 'flazz/vim-colorschemes' #{{{
on_event = 'VimEnter'
hook_post_source = 'runtime colorschemes.vimrc'
#}}}
#[[plugins]]
#repo = 'flrnprz/candid.vim' #{{{
## Looks like dracula scheme.
#on_event = 'VimEnter'
#hook_post_source = 'runtime candid.vimrc'
##}}}

# Colorscheme; Statusline
[[plugins]]
repo = 'vim-airline/vim-airline' #{{{
on_event = 'BufRead'
# Uncompatible with nyaovim?
# Better to be sourced earlier than colorschemes
hook_add = 'runtime airline.vimrc'
[[plugins]]
repo = 'vim-airline/vim-airline-themes'
on_event = 'VimEnter'
#}}}
#[[plugins]]
#repo = 'itchyny/lightline.vim' #{{{
#on_event = 'BufAdd'
#hook_post_source = 'runtime lightline.vimrc'
#[[plugins]]
#repo = 'taohexxx/lightline-buffer'
#on_source = 'lightline.vim'
#hook_post_source = 'runtime lightline-buffer.vimrc'
##}}} End of Lightline

# Colorscheme; Detection
[[plugins]]
repo = 'cocopon/inspecthi.vim' #{{{
# Generates a beautiful color swatch from the current buffer
on_cmd = 'Inspecthi'
hook_add = 'runtime inspecthi.vimrc'
#}}}
[[plugins]]
repo = 'cocopon/colorswatch.vim' #{{{
# Inspects a link structure of highlighting groups
on_cmd = 'ColorSwatchGenerate'
hook_add = 'runtime colorswatch.vimrc'
#}}}

# Colorscheme; Modifier
[[plugins]]
repo = 'cocopon/pgmnt.vim' #{{{
# Template engine for colorschemes, in pure Vim script
# e.g., if g:colors_name ==# 'iceberg' | call pgmnt#foo#bar('foobar', 'foofoo') ...
on_event = 'VimEnter'
hook_post_source = 'runtime pgmnt.vimrc'
#}}}

# Icons
[[plugins]]
repo = 'ryanoasis/vim-devicons' #{{{
on_event = 'BufRead'
hook_post_source = 'runtime devicons.vimrc'
#}}}

# Indent
#[[plugins]]
#repo = 'Yggdroot/indentLine' #{{{
## Note: Causes a bulk of problems
#on_event = 'BufRead'
#hook_add = 'runtime indentLine.vimrc'
##}}}

# Resonance
#[[plugins]]
#repo = 'junegunn/rainbow_parentheses.vim' #{{{
#on_event = 'BufWinEnter'
#hook_post_source = 'runtime rainbow_parentheses.vimrc'
##}}}
#[[plugins]]
#repo = 'luochen1990/rainbow' #{{{
## CAUTION: source rainbow.vimrc AFTER :colorscheme.
#on_event = 'BufReadPre'
##}}}
[[plugins]]
repo = 'andymass/vim-matchup' #{{{
# Better `%`
on_event = 'BufWinEnter'
hook_post_source = 'runtime matchup.vimrc'
#}}}
[[plugins]]
repo = 'itchyny/vim-cursorword' #{{{
# Underlines appear on every word under the cursor.
on_event = 'CursorMoved'
hook_post_source = 'runtime cursorword.vimrc'
#}}}
