# From: add/dein.vim

# Colorscheme; Collection
[[plugins]]
repo = 'flazz/vim-colorschemes' #{{{
on_event = 'VimEnter'
hook_post_source = 'runtime add/colorschemes.vim'
#}}}
#[[plugins]]
#repo = 'flrnprz/candid.vim' #{{{
## Looks like dracula scheme.
#on_event = 'VimEnter'
#hook_post_source = 'runtime add/candid.vim'
##}}}

# Colorscheme; Statusline
#[[plugins]]
#repo = 'hardcoreplayers/spaceline.vim' #{{{
## Not good w/ neovim-qt
#on_event = 'BufRead'
#hook_source = 'runtime rc/spaceline.vim'
##}}}
[[plugins]]
repo = 'vim-airline/vim-airline' #{{{
on_event = 'BufRead'
# Uncompatible with nyaovim?
# Better to be sourced earlier than colorschemes
hook_source = 'runtime add/airline.vim'
[[plugins]]
repo = 'vim-airline/vim-airline-themes'
on_event = 'VimEnter'
#}}}
#[[plugins]] # has extentions
#repo = 'itchyny/lightline.vim' #{{{
#on_event = 'BufAdd'
#hook_post_source = 'runtime add/lightline.vim'
#[[plugins]]
#repo = 'albertomontesg/lightline-asyncrun'
# provides an indicator to tell async jobs running in background.
#on_source = 'vim-airline'
#depends = 'asyncrun.vim'
#hook_post_source = 'runtime add/lightline-asyncrun.vim'
#[[plugins]]
#repo = 'skywind3000/asyncrun.vim'
#on_event = 'BufRead'
#hook_post_source = 'runtime add/asyncrun.vim'
#[[plugins]]
#repo = 'taohexxx/lightline-buffer'
#on_source = 'lightline.vim'
#hook_post_source = 'runtime add/lightline-buffer.vim'
##}}} End of Lightline

# Colorscheme; Detection
[[plugins]]
repo = 'cocopon/inspecthi.vim' #{{{
# Generates a beautiful color swatch from the current buffer
on_cmd = 'Inspecthi'
hook_add = 'runtime add/inspecthi.vim'
#}}}
[[plugins]]
repo = 'cocopon/colorswatch.vim' #{{{
# Inspects a link structure of highlighting groups
on_cmd = 'ColorSwatchGenerate'
hook_add = 'runtime add/colorswatch.vim'
#}}}

# Colorscheme; Modifier
[[plugins]]
repo = 'cocopon/pgmnt.vim' #{{{
# Template engine for colorschemes, in pure Vim script
# e.g., if g:colors_name ==# 'iceberg' | call pgmnt#foo#bar('foobar', 'foofoo') ...
on_event = 'VimEnter'
hook_post_source = 'runtime add/pgmnt.vim'
#}}}

# Icons
[[plugins]]
repo = 'ryanoasis/vim-devicons' #{{{
on_event = 'BufRead'
hook_post_source = 'runtime add/devicons.vim'
#}}}

# Indent
#[[plugins]]
#repo = 'Yggdroot/indentLine' #{{{
## Note: Causes a bulk of problems
#on_event = 'BufRead'
#hook_add = 'runtime add/indentLine.vim'
##}}}

# Resonance
[[plugins]]
repo = 'itchyny/vim-cursorword' #{{{
# Underlines appear on every word under the cursor.
on_event = 'CursorMoved'
# Error: no such Event CursorWord0
#hook_add = 'let g:cursorword_highlight = 0'
hook_post_source = 'runtime add/cursorword.vim'
#}}}
#[[plugins]]
#repo = 'junegunn/rainbow_parentheses.vim' #{{{
#on_event = 'BufWinEnter'
#hook_post_source = 'runtime add/rainbow_parentheses.vim'
##}}}
#[[plugins]]
#repo = 'luochen1990/rainbow' #{{{
## CAUTION: source add/rainbow.vim AFTER :colorscheme.
#on_event = 'BufReadPre'
##}}}

#[[plugins]]
#repo = 'junegunn/limelight.vim'
#on_cmd = 'Limelight'
#hook_add = 'runtime add/limelight.vim'
