# From: dein.vimrc
# Ref: Init.toml

# Indent
[[plugins]]
repo = 'Yggdroot/indentLine' #{{{
on_event = 'BufRead'
hook_add = 'runtime indentLine.vimrc'
#}}}

# Paren: Doesn't Work
#[[plugins]]
#repo = 'luochen1990/rainbow' #{{{
## CAUTION: source rainbow.vimrc AFTER :colorscheme.
#on_event = 'BufReadPre'
##}}}

# Resonance
[[plugins]]
repo = 'andymass/vim-matchup' #{{{
# Better `%`
on_event = 'CursorMoved'
hook_post_source = 'runtime matchup.vimrc'
#}}}
[[plugins]]
repo = 'itchyny/vim-cursorword' #{{{
# Underlines appear on every word under the cursor.
on_event = 'CursorMoved'
hook_post_source = 'runtime cursorword.vimrc'
#}}}

[[plugins]]
repo = 'flazz/vim-colorschemes' #{{{
on_event = 'CmdlineEnter'
#hook_post_source = 'set rtp+=~/.cache/dein/repos/github.com/flazz/vim-colorschemes/colors/*.vim'
#}}}
