# From: dein.vimrc
# Ref: Init.toml

# Colorscheme
#[[plugins]]
#repo = 'altercation/solarized' #{{{
#on_if = 'has("nvim")'
#hook_post_source = 'runtime solarized.vimrc'
##}}}
#[[plugins]]
#repo = 'morhetz/gruvbox' #{{{
## CAUTION: Colorscheme MUST be sourced after dein#end() on dein.vim.
#on_event = 'BufRead'
#if = 'has("nvim")'
#hook_add = 'runtime gruvbox.vimrc'
##}}}
[[plugins]]
repo = 'KeitaNakamura/neodark.vim' #{{{
on_event = 'BufRead'
if = 'has("nvim")'
hook_add = 'runtime neodark.vimrc'
##}}}
#[[plugins]]
#repo = 'crusoexia/vim-monokai' #{{{
#if = 'has("nvim")'
#hook_add = 'runtime monokai.vim'
##}}}
[[plugins]]
repo = 'flazz/vim-colorschemes' #{{{
on_event = 'CmdlineEnter'
#}}}

# Indent
[[plugins]]
repo = 'Yggdroot/indentLine' #{{{
on_event = 'BufRead'
hook_add = 'runtime indentLine.vimrc'
#}}}

# Resonance
#[[plugins]]
#repo = 'luochen1990/rainbow' #{{{
## CAUTION: source rainbow.vimrc AFTER :colorscheme.
#on_event = 'BufReadPre'
##}}}
[[plugins]]
repo = 'andymass/vim-matchup' #{{{
# Better `%`
on_event = 'CursorMoved'
hook_post_source = 'runtime matchup.vimrc'
#}}}
[[plugins]]
repo = 'itchyny/vim-cursorword' #{{{
# Underlines appear on every word under the cursor.
on_event = 'CursorMoved'
hook_post_source = 'runtime cursorword.vimrc'
#}}}
