# From: dein.vimrc

# LSP
[[plugins]]
repo = 'neoclide/coc.nvim' #{{{
# Branch: neoclide/coc.nvim_release
# Note: Written in TypeScript.
rev = 'release'
#hook_done_update = 'yarn install --frozen-lockfile'
on_event = 'VimEnter'
hook_post_source = 'runtime coc.vimrc'
#}}}
#[[plugins]]
#repo = 'prabirshrestha/vim-lsp' #{{{
## Written in Pure viml
#hook_post_source = 'runtime lsp.vimrc'
#[[plugins]]
#repo = 'prabirshrestha/async.vim'
#on_event = 'BufRead'
#hook_post_source = 'runtime async.vimrc'
#[[plugins]]
#repo = 'prabirshrestha/asyncomplete.vim'
#on_event = 'BufRead'
#hook_post_source = 'runtime asyncomplete.vimrc'
#[[plugins]]
#repo = 'prabirshrestha/asyncomplete-lsp.vim'
#on_event = 'BufRead'
#hook_post_source = 'runtime asyncomplete-lsp.vimrc'
##}}}
#[[plugins]]
#repo = 'autozimu/LanguageClient-neovim' #{{{
## Note: Written in Rust.
#rev = 'next'
#build = 'bash install.sh'
#on_event = 'BufRead'
#hook_add = 'runtime LanguageClient.vimrc'
##}}}

[[plugins]]
repo = 'voldikss/actionmenu.nvim'
# Provides coc.nvim actionmenu features for such as 'codeAction'.
on_source = 'coc.nvim'
hook_post_source = 'runtime actionmenu.vimrc'

# FZF
[[plugins]]
repo = 'junegunn/fzf' #{{{
on_event = 'VimEnter'
[[plugins]]
repo = 'junegunn/fzf.vim'
on_event = 'VimEnter'
hook_add = 'runtime fzf.vimrc'
#}}}

# Git;
[[plugins]] # has extentions
repo = 'tpope/vim-fugitive' #{{{
type = 'git'
on_event = 'BufRead'
hook_post_source = 'runtime fugitive.vimrc'
# Fugitive; Branch Viewr
[[plugins]]
repo = 'sodapopcan/vim-twiggy' #{{{
on_map = '<Plug>(twiggy'
on_cmd = ':Twiggy'
hook_add = 'runtime twiggy.vimrc'
#}}}
#[[plugins]]
#repo = 'idanarye/vim-merginal' #{{{
## Note: twiggy is better.
#type = 'git'
#on_event = 'CmdLineEnter'
#on_map = ':Merginal'
### Doesn't work well.
##on_cmd = 'Merginal'
#hook_add = 'runtime merginal.vimrc'
##}}}
# Fugitive; Commit's Message viewer
[[plugins]]
repo = 'rhysd/git-messenger.vim' #{{{
type = 'git'
on_cmd = 'GitMessenger'
hook_add = 'runtime git-messenger.vimrc'
#}}}
# Fugitive; for Gbrowse
[[plugins]]
repo = 'tpope/vim-rhubarb' #{{{
on_cmd = 'Gbrowse'
hook_post_source = 'runtime rhubarb.vimrc'
#}}}
[[plugins]]
repo = 'shumphrey/fugitive-gitlab.vim' #{{{
on_cmd = 'Gbrowse'
hook_post_source = 'runtime fugitive-gitlab.vimrc'
#}}}
## Fugitive; Local Log Viewer
#[[plugins]]
#repo = 'int3/vim-extradite' #{{{
## Note: Enough w/ coc.nvim
## Also provides diff viewer.
#on_event = ['BufRead']
#hook_post_source = 'runtime extradite.vimrc'
##}}}
## Fugitive; Log Wrapper
#[[plugins]]
#repo = 'rbong/vim-flog' #{{{
#on_event = ['BufRead']
#hook_post_source = 'runtime flog.vimrc'
#}}}
## Fugitive; Diff Wrapper
#[[plugins]]
#repo = 'arkwright/vim-manhunt' #{{{
#on_event = 'BufRead'
#hook_post_source = 'runtime manhunt.vimrc'
##}}}
#[[plugins]]
#repo = 'junegunn/gv.vim' #{{{
#type = 'git'
#on_ft = ['fugitive', 'gitcommit', 'git']
#hook_post_source = 'runtime gv.vimrc'
##}}}
#[[plugins]]
#repo = 'rhysd/committia.vim' #{{{
#type = 'git'
#on_ft = ['fugitive', 'gitcommit', 'git']
##on_source = 'vim-fugitive'
#hook_post_source = 'runtime committia.vimrc'
##}}}
#}}} End of Fugitive
#[[plugins]]
#repo = 'airblade/vim-gitgutter' #{{{
## enough only with coc.nvim & fugitive.vim?
#type = 'git'
#on_event = 'BufRead'
#hook_post_source = 'runtime gitgutter.vimrc'
##}}}
#[[plugins]]
#repo = 'lambdalisue/gina.vim' #{{{
#on_event = ['BufWritePost']
#hook_post_source = 'runtime gina.vimrc'
##}}}

# Enable Collaborative Editing
[[plugins]]
repo = 'Floobits/floobits-neovim'
# Need to create an account of floobits.
on_cmd = 'Floo'
hook_add = 'runtime floobits.vimrc'

# Shell; Wrapper
[[plugins]]
repo = 'kassio/neoterm' #{{{
on_event = 'BufAdd'
hook_post_source = 'runtime neoterm.vimrc'
#}}}
[[plugins]]
repo = 'Shougo/deol.nvim' #{{{
on_event = 'VimEnter'
hook_post_source = 'runtime deol.vimrc'
#}}}

# Shell; Async Processor
#[[plugins]]
#repo = 'thinca/vim-quickrun' #{{{
#on_map = 'QuickRun'
#hook_add = 'runtime quickrun.vimrc'
##}}}
#[[plugins]]
#repo = 'neomake/neomake' #{{{
#on_map = 'make'
#hook_add = 'runtime neomake.vimrc'
#}}}
#[[plugins]]
#repo = 'skywind3000/asyncrun.vim' #{{{
## Only supports external shell to qf.
#on_map = 'AsyncRun'
#hook_add = 'runtime asyncrun.vimrc'
#}}}

# Shell; Info
[[plugins]]
repo = 'HiPhish/info.vim'
on_cmd = 'Info'
hook_post_source = 'runtime info.vimrc'

# i3-wm
#[[plugins]]
#repo = 'termhn/i3-vim-nav' #{{{
#on_if = 'isdirectory("~/go/src/github.com/termhn/i3-vim-nav")'
#hook_post_source = 'runtime i3-vim-nav.vimrc'
##}}}
