# From: rc/dein.vim

# LSP
[[plugins]]
repo = 'neoclide/coc.nvim' #{{{
# Branch: neoclide/coc.nvim_release
# Note: Written in TypeScript.
rev = 'release'
#hook_done_update = 'yarn install --frozen-lockfile'
on_event = 'VimEnter'
hook_post_source = 'runtime rc/coc.vim'
#}}}
#[[plugins]]
#repo = 'prabirshrestha/vim-lsp' #{{{
## Written in Pure viml
#hook_post_source = 'runtime rc/lsp.vim'
#[[plugins]]
#repo = 'prabirshrestha/async.vim'
#on_event = 'BufRead'
#hook_post_source = 'runtime rc/async.vim'
#[[plugins]]
#repo = 'prabirshrestha/asyncomplete.vim'
#on_event = 'BufRead'
#hook_post_source = 'runtime rc/asyncomplete.vim'
#[[plugins]]
#repo = 'prabirshrestha/asyncomplete-lsp.vim'
#on_event = 'BufRead'
#hook_post_source = 'runtime rc/asyncomplete-lsp.vim'
##}}}
#[[plugins]]
#repo = 'autozimu/LanguageClient-neovim' #{{{
## Note: Written in Rust.
#rev = 'next'
#build = 'bash install.sh'
#on_event = 'BufRead'
#hook_add = 'runtime rc/LanguageClient.vim'
##}}}

[[plugins]]
repo = 'voldikss/actionmenu.nvim' #{{{
# Provides coc.nvim actionmenu features for such as 'codeAction'.
on_source = 'coc.nvim'
hook_post_source = 'runtime rc/actionmenu.vim'
#}}}

# Git;
[[plugins]] # has extentions
repo = 'tpope/vim-fugitive' #{{{
type = 'git'
on_event = 'BufRead'
hook_post_source = 'runtime rc/fugitive.vim'
# Fugitive; Branch Viewr
[[plugins]]
repo = 'sodapopcan/vim-twiggy' #{{{
on_cmd = ':Twiggy'
hook_add = 'runtime rc/twiggy.vim'
#}}}
#[[plugins]]
#repo = 'idanarye/vim-merginal' #{{{
## Note: twiggy is better.
#type = 'git'
#on_event = 'CmdLineEnter'
#on_map = ':Merginal'
### Doesn't work well.
##on_cmd = 'Merginal'
#hook_add = 'runtime rc/merginal.vim'
##}}}
# Fugitive; Commit's Message viewer
[[plugins]]
repo = 'rhysd/git-messenger.vim' #{{{
type = 'git'
on_cmd = 'GitMessenger'
hook_add = 'runtime rc/git-messenger.vim'
#}}}
# Fugitive; for Gbrowse
[[plugins]]
repo = 'tpope/vim-rhubarb' #{{{
on_cmd = 'Gbrowse'
hook_post_source = 'runtime rc/rhubarb.vim'
#}}}
[[plugins]]
repo = 'shumphrey/fugitive-gitlab.vim' #{{{
on_cmd = 'Gbrowse'
hook_post_source = 'runtime rc/fugitive-gitlab.vim'
#}}}
## Fugitive; Local Log Viewer
#[[plugins]]
#repo = 'int3/vim-extradite' #{{{
## Note: Enough w/ coc.nvim
## Also provides diff viewer.
#on_event = ['BufRead']
#hook_post_source = 'runtime rc/extradite.vim'
##}}}
## Fugitive; Log Wrapper
#[[plugins]]
#repo = 'rbong/vim-flog' #{{{
#on_event = ['BufRead']
#hook_post_source = 'runtime rc/flog.vim'
#}}}
## Fugitive; Diff Wrapper
#[[plugins]]
#repo = 'arkwright/vim-manhunt' #{{{
#on_event = 'BufRead'
#hook_post_source = 'runtime rc/manhunt.vim'
##}}}
#[[plugins]]
#repo = 'junegunn/gv.vim' #{{{
#type = 'git'
#on_ft = ['fugitive', 'gitcommit', 'git']
#hook_post_source = 'runtime rc/gv.vim'
##}}}
#[[plugins]]
#repo = 'rhysd/committia.vim' #{{{
#type = 'git'
#on_ft = ['fugitive', 'gitcommit', 'git']
##on_source = 'vim-fugitive'
#hook_post_source = 'runtime rc/committia.vim'
##}}}
#}}} End of Fugitive
#[[plugins]]
#repo = 'airblade/vim-gitgutter' #{{{
## enough only with coc.nvim & fugitive.vim?
#type = 'git'
#on_event = 'BufRead'
#hook_post_source = 'runtime rc/gitgutter.vim'
##}}}
#[[plugins]]
#repo = 'lambdalisue/gina.vim' #{{{
#on_event = ['BufWritePost']
#hook_post_source = 'runtime rc/gina.vim'
##}}}

# Docker
#[[plugins]]
#repo = 'skanehira/docker.vim' #{{{
## to manage docker's images/containers
## Note: unavailable on neovim
#if = '!has("nvim")'
#on_cmd = 'Docker'
#hook_add = 'runtime rc/docker.vim'
##}}}
[[plugins]]
repo = 'skanehira/docker-compose.vim'
on_cmd = 'DockerCompose'
hook_add = 'runtime rc/docker-compose.vim'

# Doc; Info
[[plugins]]
repo = 'HiPhish/info.vim' #{{{
on_cmd = 'Info'
hook_add = 'runtime rc/info.vim'
#}}}

# Shell; Async Processor
[[plugins]]
repo = 'thinca/vim-quickrun' #{{{
on_cmd = 'QuickRun'
hook_add = 'runtime rc/quickrun.vim'
#}}}
#[[plugins]]
#repo = 'neomake/neomake' #{{{
#on_cmd = 'make'
#hook_add = 'runtime rc/neomake.vim'
##}}}
#[[plugins]]
#repo = 'skywind3000/asyncrun.vim' #{{{
## Only supports external shell to qf.
#on_cmd = 'AsyncRun'
#hook_add = 'runtime rc/asyncrun.vim'
#}}}

# Shell; Wrapper
#[[plugins]]
#repo = 'kassio/neoterm' #{{{
#on_event = 'BufAdd'
#hook_post_source = 'runtime rc/neoterm.vim'
##}}}
#[[plugins]]
#repo = 'Shougo/deol.nvim' #{{{
#on_event = 'VimEnter'
#hook_post_source = 'runtime rc/deol.vim'
##}}}

# i3-wm
#[[plugins]]
#repo = 'termhn/i3-vim-nav' #{{{
#on_if = 'isdirectory("~/go/src/github.com/termhn/i3-vim-nav")'
#hook_post_source = 'runtime rc/i3-vim-nav.vim'
##}}}
