# From: add/dein.vim

# LSP
[[plugins]]
repo = 'neoclide/coc.nvim' #{{{
# Branch: neoclide/coc.nvim_release
# Note: Written in TypeScript.
rev = 'release'
#hook_done_update = 'yarn install --frozen-lockfile'
on_event = 'VimEnter'
if = 'executable("yarn")'
hook_add = 'runtime add/coc.vim'
#}}}
#[[plugins]]
#repo = 'prabirshrestha/vim-lsp' #{{{
## Written in Pure viml
#hook_post_source = 'runtime add/lsp.vim'
#[[plugins]]
#repo = 'prabirshrestha/async.vim'
#on_event = 'BufRead'
#hook_post_source = 'runtime add/async.vim'
#[[plugins]]
#repo = 'prabirshrestha/asyncomplete.vim'
#on_event = 'BufRead'
#hook_post_source = 'runtime add/asyncomplete.vim'
#[[plugins]]
#repo = 'prabirshrestha/asyncomplete-lsp.vim'
#on_event = 'BufRead'
#hook_post_source = 'runtime add/asyncomplete-lsp.vim'
##}}}
#[[plugins]]
#repo = 'autozimu/LanguageClient-neovim' #{{{
## Note: Written in Rust.
#rev = 'next'
#build = 'bash install.sh'
#on_event = 'BufRead'
#hook_add = 'runtime add/LanguageClient.vim'
##}}}

[[plugins]]
repo = 'voldikss/actionmenu.nvim' #{{{
# Provides coc.nvim actionmenu features for such as 'codeAction'.
on_source = 'coc.nvim'
hook_post_source = 'runtime add/actionmenu.vim'
#}}}

# Docker
#[[plugins]]
#repo = 'skanehira/docker.vim' #{{{
## to manage docker's images/containers
## Note: unavailable on neovim
#if = '!has("nvim")'
#on_cmd = 'Docker'
#hook_add = 'runtime add/docker.vim'
##}}}
#[[plugins]]
#repo = 'skanehira/docker-compose.vim'
## Error:
## [dein] Error generating helptags:
## [dein] Vim(helptags):E154: Duplicate tag "docker-compose" in file /home/kaile256/.cache/dein/.cache/init.vim/.dein/doc/docker-compose.txt
## [dein] function <SNR>346_on_pull_exit[45]..<SNR>346_recache_rtp[19]..dein#recache_runtimepath[1]..dein#install#_recache_runtimepath[19]..<SNR>362_helptags, line 12
#on_cmd = 'DockerCompose'
#hook_add = 'runtime add/docker-compose.vim'

# Pair Programming
#[[plugins]]
#repo = 'derteta/vimpair'
## Error: buggy on init
#on_cmd = 'VimpairServerStart "127.0.0.1"'
#hook_add = 'runtime add/vimpair.vim'

# Doc; Info
[[plugins]]
repo = 'HiPhish/info.vim' #{{{
on_cmd = 'Info'
hook_add = 'runtime add/info.vim'
#}}}

## REPL;
#[[plugins]]
#repo = 'sillybun/vim-repl'
#on_cmd = 'REPL'
#hook_add = 'runtime add/repl.vim'
# Shell; Async Processor
[[plugins]]
repo = 'thinca/vim-quickrun' #{{{
on_cmd = 'QuickRun'
hook_add = 'runtime add/quickrun.vim'
#}}}
#[[plugins]]
#repo = 'neomake/neomake' #{{{
#on_cmd = 'make'
#hook_add = 'runtime add/neomake.vim'
##}}}
#[[plugins]]
#repo = 'skywind3000/asyncrun.vim' #{{{
## Only supports external shell to qf.
#on_cmd = 'AsyncRun'
#hook_add = 'runtime add/asyncrun.vim'
#}}}

# Shell; Wrapper
#[[plugins]]
#repo = 'kassio/neoterm' #{{{
## also has async-run feature.
#on_cmd = ['T']
#hook_add = 'runtime add/neoterm.vim'
##}}}
#[[plugins]]
#repo = 'Shougo/deol.nvim' #{{{
#on_event = 'VimEnter'
#hook_post_source = 'runtime add/deol.vim'
##}}}

# i3-wm
#[[plugins]]
#repo = 'termhn/i3-vim-nav' #{{{
#on_if = 'isdirectory("~/go/sadd/github.com/termhn/i3-vim-nav")'
#hook_post_source = 'runtime add/i3-vim-nav.vim'
##}}}
