[ftplugin]
# Execute after ftplugin.
vim = ''' "{{{
setl fdm=marker fdl=0
"}}} '''
qf = ''' "{{{
setl signcolumn=
augroup MyQfBuffer
  au!
  function! s:quickfix_keymap() "{{{
    nnoremap <buffer> <c-o> :cprevious<cr>
    nnoremap <buffer> <c-i> :cnext<cr>
    nnoremap <buffer> <a-]> :cnewer<cr>
    nnoremap <buffer> <a-[> :colder<cr>
  endfunction "}}}
  wu BufWinEnter * if &ft == 'qf' | call <SID>quickfix_keymap() | endif
augroup END
" TODO: `setl signcolumn= nonumber` on Help TOC
"}}} '''
help = ''' "{{{
setl buflisted nonumber signcolumn= nolist
norm zz
"}}} '''
toml = ''' "{{{
setl fdm=marker fdl=0

augroup AutoFormatOnToml
  au!
  " Remove Unnecessary part of URL
  au BufWritePre *.toml keeppatterns %s/https:\/\/github.com\///ge
augroup END

"noremap <buffer><silent> <S-TAB> :keeppatterns %s/^\s\+//ge<cr>
"}}} '''

i3 = ''' "{{{
setl fdm=marker fdl=0

noremap <buffer><silent> <S-TAB> :keepjumps keeppatterns %s/^\s\+//ge<cr> 
"}}} '''

json = ''' "{{{
setl fdm=syntax fdl=1
"}}} '''
ruby = ''' "{{{
setl fdm=syntax fdl=1
setl tabstop=2 softtabstop=2 shiftwidth=2
"}}} '''
python = ''' "{{{
setl fdm=syntax fdl=1
setl tabstop=2 softtabstop=2 shiftwidth=2
"}}} '''

_ = ''' "{{{
au FileType * if &l:fo =~ 'ro' | set formatoptions-=ro | endif
"}}} '''
