# From: add/dein.vim

# FZF
[[plugins]]
repo = 'junegunn/fzf' #{{{
# Note: Necessary only for :FZF
on_cmd = 'FZF'
hook_source = 'runtime add/fzf.vim'
[[plugins]]
#repo = 'junegunn/fzf.vim'
repo = 'kaile256/fzf.vim'
on_cmd = 'fzf#vim#'
rev = 'command_functions'
hook_add = 'runtime add/fzf.vim'
hook_source = 'runtime source/fzf.vim'
hook_post_source = 'runtime post/fzf.vim'
#}}}

# Filer
[[plugins]] # has extentions
repo = 'Shougo/defx.nvim' #{{{
if = 'has("python3")'
on_cmd = 'Defx'
hook_add = 'runtime add/defx.vim'
hook_post_source = 'runtime post/defx.vim'
[[plugins]]
repo = 'kristijanhusak/defx-git' #{{{
on_source = 'defx.nvim'
#}}}
#[[plugins]]
#repo = 'kristijanhusak/defx-icons' #{{{
#on_source = 'defx.nvim'
##}}}
#}}} End of Defx
#[[plugins]]
#repo = 'lambdalisue/fila.vim' #{{{
## Note: currently has no docment.
#on_cmd = 'Fila'
#hook_add = 'runtime add/fila.vim'
##}}}
#[[plugins]]
#repo = 'cocopon/vaffle.vim' #{{{
#on_if = 'has("python3")'
#hook_post_source = 'runtime add/vaffle.vim'
##}}}
#[[plugins]]
#repo = 'justinmk/vim-dirvish' #{{{
#on_event = 'BufAdd'
#hook_post_source = 'runtime add/dirvish.vim'
#}}}

# CTags/global
[[plugins]]
repo = 'jsfaint/gen_tags.vim' #{{{
on_event = 'BufLeave'
hook_post_source = 'runtime add/gen_tags.vim'
#}}}
#[[plugins]]
#repo = 'SpaceVim/gtags.vim' #{{{
## Only for SpaceVim? E117: Unknown function: gtags#update
## 1. generate gtags file automatically
## 2. quickfix list support
## 3. A fuzzy finder souces for some plugins:
##          denite, unite, fzf, leader-f, fzy
#on_event = 'BufRead'
#hook_post_source = 'runtime add/gtags.vim'
##}}}
#[[plugins]]
#repo = 'majutsushi/tagbar' #{{{
#on_event = ['BufNew','BufRead']
#hook_post_source = 'runtime add/tagbar.vim'
#}}}
[[plugins]]
repo = 'liuchengxu/vista.vim' #{{{
# Also supports lsp via such plugins as coc, vim-lsp.
on_cmd = 'Vista'
hook_add = 'runtime add/vista.vim'
#}}}

# Enhance; Marks
[[plugins]]
repo = 'MattesGroeger/vim-bookmarks' #{{{
on_cmd = 'Bookmark'
on_map = '<C-u>Bookmark'
hook_add = 'runtime add/bookmarks.vim'
#}}}
#[[plugins]]
#repo = 'jacquesbh/vim-showmarks'{{{
#on_map = ['m','`',"'",'<space>']
#hook_add = 'runtime add/showmarks.vim'
#}}}

