# From: rc/dein.vir

# Multiple FileType;
#[[plugins]]
#repo = 'tpope/vim-sleuth' #{{{
## Note: Sleuth means a detective.
## Enough with coc-prettier?
## Automatically adjusts 'shiftwidth' and 'expandtab'
#on_event = ['BufNewFile','BufRead']
#hook_add = 'runtime rc/sleuth.vim'
##}}}
#[[plugins]]
#repo = 'Shougo/context_filetype.vim' #{{{
#on_ft = ['vimwiki','markdown','html','php','neosnippet','snippets']
##}}}
#[[plugins]]
#repo = 'vim-syntastic/syntastic' #{{{
#on_ft = ['toml']
#hook_post_source = 'runtime rc/syntastic.vim'
##}}}

[[plugins]]
repo = 'mhinz/vim-lookup' #{{{
# Enable to jump to definition as &runtimepath.
#on_ft = 'vim'
on_map = '<Cmd>lookup#'
hook_add = 'runtime rc/lookup.vim'
#}}}

# for Document;
[[plugins]]
repo = 'thinca/vim-ft-help_fold' #{{{
# Note: conflicted with `set modeline`
on_ft = 'help'
#}}}
[[plugins]]
repo = 'Konfekt/vim-office' #{{{
# no need any config.
on_ft = ['pdf', 'doc', 'docx', 'els', 'xlsx', 'ppt', 'pptx', 'odt', 'epub']
#}}}
[[plugins]]
repo = 'itchyny/vim-pdf' #{{{
on_ft = ['pdf']
#}}}
[[plugins]]
repo = 'othree/html5.vim' #{{{
on_ft = 'html'
#[[plugins]]
#repo = 'mattn/emmet-vim'
#on_ft = 'html'
[[plugins]]
# Html; Auto Close for html-tags
repo = 'alvan/vim-closetag'
on_event = 'BufRead'
hook_add = 'runtime! rc/closetag.vim'
on_ft = ['html', 'javascript']
hook_add = '''
let g:cloesetag_filenames = '*.html,*.vue'
'''
#}}}
#[[plugins]]
#repo = 'freitass/todo.txt-vim' #{{{
## Use `set syn=help` instead
#on_ft = 'text'
##}}}
[[plugins]]
repo = 'plasticboy/vim-markdown'
if = '&l:ft !=# "vimwiki"'
on_ft = 'markdown'
hook_add = 'runtime rc/markdown.vim'
#[[plugins]]
#repo = 'suan/vim-instant-markdown'
#if = '&l:ft !=# "vimwiki"'
#on_ft = 'markdown'
#hook_add = 'runtime rc/instant-markdown.vim'
#}}}

# for Shell or Term-Emulater;
[[plugins]]
repo = 'dag/vim-fish' #{{{
on_ft = 'fish'
#}}}
[[plugins]]
repo = 'chrisbra/vim-zsh' #{{{
on_ft = 'zsh'
#}}}
[[plugins]]
repo = 'ericpruitt/tmux.vim' #{{{
on_ft = 'tmux'
#}}}

# for External;
# 13-wm
#[[plugins]]
#repo = 'mboughaba/i3config.vim' #{{{
## Note: No enough Syntax Configured yet
#on_ft = 'i3'
##}}}
[[plugins]]
repo = 'PotatoesMaster/i3-vim-syntax' #{{{
# CAUTION: Not Maintained Anymore
on_ft = 'i3'
#}}}

[[plugins]]
repo = 'neovimhaskell/haskell-vim'
on_ft = 'haskell'
hook_post_source = 'runtime rc/haskell.vim'
# for Dynamic
# Python
[[plugins]]
repo = 'plytophogy/vim-virtualenv' #{{{
# supports pip-packages, independently installed in shell, to work on vim
on_ft = 'python'
[[plugins]]
repo = 'python-mode/python-mode' #{{{
on_ft = 'python'
hook_post_update = 'git submodule update --init --recursive'
hook_post_source = 'runtime rc/python-mode.vim'
#}}}
[[plugins]]
repo = 'drmingdrmer/vim-indent-lua' #{{{
on_ft = 'lua'
#}}}
#[[plugins]]
#repo = 'Alloyed/lua-lsp' #{{{
#on_ft = 'lua'
#}}}
[[plugins]]
repo = 'udalov/kotlin-vim' #{{{
on_ft = 'kotlin'
#}}}

[[plugins]]
repo = 'vmchale/tomlcheck-vim' #{{{
on_ft = 'toml'
#}}}
[[plugins]]
repo = 'cespare/vim-toml' #{{{
on_ft = 'toml'
# syntax highlight for 'hook_add'
[[plugins]]
repo = 'delphinus/vim-toml-dein'
on_ft = 'toml'
#}}}

#[[plugins]]
#repo = 'lervag/vimtex' #{{{
#on_ft = 'tex'
#hook_post_source = 'runtime rc/vimtex.vim'
#}}}
