# From: dein.vimrc

# Required
[[plugins]]
repo = 'Shougo/dein.vim' #{{{
hook_done_update= 'UpdateRemotePlugins'
#}}}

[[plugins]]
repo = 'vimwiki/vimwiki' #{{{
rev = 'dev'
#rev = 'v2.4.1'  # the repo is dirty to activate.
hook_add = 'runtime vimwiki.vimrc'
#}}}

[[plugins]]
repo = 'junegunn/fzf' #{{{
[[plugins]]
repo = 'junegunn/fzf.vim'
hook_add = 'runtime fzf.vimrc'
#}}}

[[plugins]]
repo = 'tpope/vim-fugitive' #{{{
type = 'git'
hook_add = 'runtime fugitive.vimrc'
#}}}

#[[plugins]]
#repo = 'morhetz/gruvbox' #{{{
## CAUTION: Colorscheme MUST be sourced after dein#end() on dein.vim.
#if = 'has("nvim")'
#hook_add = 'runtime gruvbox.vimrc'
##}}}
#[[plugins]]
#repo = 'joshdick/onedark.vim' #{{{
#if = 'has("nvim")'
#hook_add = 'runtime onedark.vimrc'
##}}}
[[plugins]]
repo = 'KeitaNakamura/neodark.vim' #{{{
if = 'has("nvim")'
hook_add = 'runtime neodark.vimrc'
#}}}

[[plugins]]
repo = 'vim-airline/vim-airline' #{{{
hook_add = 'runtime airline.vimrc'
[[plugins]]
repo = 'vim-airline/vim-airline-themes'
#}}}

#[[plugins]]
#repo = 'itchyny/lightline.vim' #{{{
## ERORR: g:lightline is undefined.
#hook_add = 'runtime! lightline.vimrc'
##}}}
