# From: rc/dein.vim

# Required
[[plugins]]
repo = 'Shougo/dein.vim' #{{{
hook_done_update= 'UpdateRemotePlugins'
#}}}

[[plugins]]
repo = 'Shougo/vimproc.vim' #{{{
# run vim-plugins asynchronously, like openbrowser, quickrun.
build = 'make'
#}}}
