# From: dein.vimrc

# Required
[[plugins]]
repo = 'Shougo/dein.vim' #{{{
hook_done_update= 'UpdateRemotePlugins'
#}}}

[[plugins]]
repo = 'vimwiki/vimwiki' #{{{
rev = 'dev'
#rev = 'v2.4.1'  # the repo is dirty to activate.
hook_add = 'runtime vimwiki.vimrc'
#}}}

[[plugins]]
repo = 'junegunn/fzf' #{{{
[[plugins]]
repo = 'junegunn/fzf.vim'
hook_add = 'runtime fzf.vimrc'
#}}}

# Colorscheme
[[plugins]]
repo = 'cocopon/iceberg.vim' #{{{
if = 'exists("g:nyaovim_version")'
hook_add = 'runtime iceberg.vimrc'
#}}}
#[[plugins]]
#repo = 'altercation/solarized' #{{{
#on_if = 'has("nvim")'
#hook_post_source = 'runtime solarized.vimrc'
##}}}
#[[plugins]]
#repo = 'morhetz/gruvbox' #{{{
## CAUTION: Colorscheme MUST be sourced after dein#end() on dein.vim.
##if = 'exists("g:GuiLoaded") && GuiName() ==# "nvim-qt"' # doesn't work.
#if = '!exists("g:nyaovim_version")'
#hook_add = 'runtime gruvbox.vimrc'
##}}}
[[plugins]]
repo = 'KeitaNakamura/neodark.vim' #{{{
if = '!exists("g:nyaovim_version")'
hook_add = 'runtime neodark.vimrc'
#}}}
#[[plugins]]
#repo = 'crusoexia/vim-monokai' #{{{
#hook_add = 'runtime monokai.vim'
##}}}
