# From: dein.vimrc

# Imput Method
[[plugins]]
repo = 'tyru/eskk.vim' #{{{
# Note: dein doesn't source eskk.vim on non-lazy though sourcing vimrc.
# Note: on_map = '<Plug>' neither fails to work.
# TODO: Do NEVER source eskk on gnvim/nvim-qt.
on_event = ['InsertEnter', 'CmdlineEnter']
hook_add = 'runtime eskk.vimrc'
[[plugins]]
# Syntax Files for skkdict.
repo = 'tyru/skkdict.vim' #{{{
on_ft = 'skkdict'
#}}}
#}}}

# Unicode
[[plugins]]
repo = 'chrisbra/unicode.vim'
on_event = 'InsertEnter'
# Note: on_map of unicode.vim is useless; maybe because they are imap.
#on_map = ['<Plug>(UnicodeComplete)', '<Plug>(DigraphComplete)']
hook_post_source = 'runtime unicode.vimrc'

# CapsLock
#[[plugins]]
#repo = 'tpope/vim-capslock' #{{{
## Doesn't Work
#on_event = ['InsertEnter', 'CmdlineEnter']
#hook_post_source = 'runtime capslock.vimrc'
##}}}
#[[plugins]]
#repo = 'mattn/vim-switch-esc-capslock' #{{{
#### For Windows?
#on_event = ['InsertEnter', 'CmdlineEnter']
#hook_post_source = 'runtime switch-esc-capslock.vimrc'
##}}}

# Completion
[[plugins]]
repo = 'Shougo/deoplete.nvim' #{{{
# good with eskk.vim
on_if = 'has("python3")'
on_event = ['InsertCharPre', 'InsertEnter']
hook_post_source = 'runtime deoplete.vimrc'
#[[plugins]]
#repo = 'SevereOverfl0w/deoplete-github' #{{{
#on_ft = ['gitcommit']
##}}}
#[[plugins]]
#repo = 'wellle/tmux-complete.vim' #{{{
#on_ft = 'tmux'
##}}}
[[plugins]]
repo = 'deoplete-plugins/deoplete-zsh' #{{{
on_ft = 'zsh'
#}}}
[[plugins]]
repo = 'ponko2/deoplete-fish' #{{{
on_ft = 'fish'
#}}}
#}}}
#[[plugins]]
#repo = 'tenfyzhong/CompleteParameter.vim' #{{{
## Enough w/ lsp and snippets?
#on_map = '<Plug>(complete_parameter#'
#hook_add = 'runtime CompleteParameter.vimrc'
##}}}

# Snippets; Engine
[[plugins]]
repo = 'Shougo/neosnippet.vim' #{{{
on_event = ['InsertEnter', 'TermOpen','CmdlineEnter']
on_map = 'NeoSnippet'
hook_add = 'runtime neosnippet.vimrc'
#}}}
#[[plugins]]
#repo = 'SirVer/ultisnips' #{{{
## Note: it override <TAB>
#on_event = ['InsertEnter','TermOpen']
#hook_post_source = 'runtime ultisnips.vimrc'
##}}}
# Snippets; Contents
[[plugins]]
repo = 'honza/vim-snippets' #{{{
on_event = ['InsertEnter', 'TermOpen']
on_source = 'neosnippet.vim'
#}}}
#[[plugins]]
#repo = 'Shougo/neosnippet-snippets' #{{{
## minimal
#on_event = ['InsertEnter', 'TermOpen','CmdlineEnter']
##}}}
#[[plugins]]
#repo = 'garbas/vim-snipmate' #{{{
#on_event = ['InsertEnter', 'TermOpen']
#}}}
