# From: rc/dein.vim

# Imput Method
[[plugins]]
repo = 'tyru/eskk.vim' #{{{
# Note: on_map fails to work in insert mode.
on_event = ['InsertEnter', 'CmdlineEnter']
hook_add = 'runtime rc/eskk.vim'
[[plugins]]
# Syntax Files for skkdict.
repo = 'tyru/skkdict.vim' #{{{
on_ft = 'skkdict'
#}}}
#}}}

[[plugins]]
repo = 'deton/jasegment.vim'
# remaps `W`,`E`, and so on.
on_ft = 'markdown'
#hook_post_source = 'runtime rc/jasegment.vim'

[[plugins]]
repo = 'deton/jasentence.vim'
# remaps `)(` for '、' and '。'
on_ft = 'markdown'
#hook_post_source = 'runtime rc/jasentence.vim'

[[plugins]]
repo = 'fuenor/JpFormat.vim'
if = 'exists("JpFormatCursorMovedI") && (JpFormatCursorMovedI == 1)'
if = 'exists("JpFormatGqMode") && (JpFormatGqMode == 1)'
on_ft = ['markdown']
on_cmd = 'Jp'
on_map = '<Cmd>Jp'
hook_add = 'runtime rc/JqFormat.vim'

#[[plugins]]
#repo = 'kana/vim-textobj-jabraces'
## provides textobj of japanese braces.
## e.g., for 『』as `ajk`
##       to <Plug>(textobj-jabraces-double-kakko-a)
#on_ft = 'markdown'
#hook_add = 'runtime rc/textobj-jabraces.vim'
