# From: add/dein.vim

# Document
#[[plugins]]
#repo = 'vim-jp/vimdoc-ja-working'
#on_cmd = ['FzfHelptags', 'Helptags', 'help']

# Imput Method
[[plugins]] # has extensions
repo = 'tyru/eskk.vim' #{{{
on_cmd = 'eskk#enable()'
hook_add = 'runtime add/eskk.vim'
# TODO: Do them below, on background.
hook_done_update= '''
exe 'e' g:dein_cache_dir .'/repos/github.com/tyru/eskk.vim/autoload/eskk.vim'
%s/<C-j>/C-space/e
write
'''
[[plugins]]
repo = 'tyru/skkdict.vim' #{{{
# Syntax Files for skkdict.
on_ft = 'skkdict'
#}}}
#}}}

[[plugins]]
repo = 'deton/jasegment.vim'
# no mappings for 'w', 'e', and so on.
# remaps `W`,`E`, and so on.
on_ft = 'markdown'
#hook_post_source = 'runtime add/jasegment.vim'

[[plugins]]
repo = 'deton/jasentence.vim'
# remaps `)(` for '、' and '。'
on_ft = 'markdown'
#hook_post_source = 'runtime add/jasentence.vim'

#[[plugins]]
#repo = 'fuenor/JpFormat.vim' #{{{
#on_ft = ['markdown']
#on_cmd = 'Jp'
#hook_add = 'runtime add/JqFormat.vim'
##}}}

#[[plugins]]
#repo = 'kana/vim-textobj-jabraces'
## provides textobj of japanese braces.
## e.g., for 『』as `ajk`
##       to <Plug>(textobj-jabraces-double-kakko-a)
#on_ft = 'markdown'
#hook_add = 'runtime add/textobj-jabraces.vim'
