# From: add/dein.vim

[[plugins]]
repo = 'bkad/CamelCaseMotion' #{{{
on_map = {no = '<Plug>CamelCaseMotion_'}
#on_event = 'BufRead'
hook_add = 'runtime add/CamelCaseMotion.vim'
#}}}

# Search
[[plugins]]
repo = 'haya14busa/vim-asterisk' #{{{
# Keep the cursor on `*` or `#`, even on visual mode.
on_event = 'BufRead'
# Note: on_map is too late on visual mode.
#on_map = {xn = '<Plug>(asterisk-'}
hook_add = 'runtime add/asterisk.vim'
#}}}
#[[plugins]]
#repo = 'haya14busa/vim-metarepeat' #{{{
#on_map = {nx = '<Plug>(metarepeat'}
#hook_add = 'runtime add/metarepeat.vim'
##}}}
#[[plugins]]
#repo = 'thinca/vim-visualstar' #{{{
#on_map = '<Plug>(visualstar-'
#hook_add = 'runtime add/visualstar.vim'
##}}}

# Leap to Target
#[[plugins]]
#repo = 'justinmk/vim-sneak' #{{{
#on_map = {nox = '<Plug>Sneak_'}
#hook_add = 'runtime add/sneak.vim'
#hook_post_source = '''
#silent! unmap s
#silent! unmap S
#'''
##}}}
# Leap; Easy Motion
[[plugins]] # has extentions
repo = 'easymotion/vim-easymotion' #{{{
on_map = {nox = '<Plug>(easymotion-'}
hook_add = 'runtime add/easymotion.vim'
hook_post_source = 'runtime post/easymotion.vim'
#[[plugins]]
#repo = 'haya14busa/vim-easyoperator-phrase' #{{{
#on_map = '<plug>(easyoperator-'
#hook_add = 'runtime add/easyoperator.vim'
##}}}
#[[plugins]]
#repo = 'haya14busa/incsearch.vim' #{{{
#on_event = 'ColorScheme'
#hook_post_source = 'runtime add/incsearch.vim'
#}}}
#[[plugins]]
#repo = 'haya14busa/incsearch-easymotion.vim' #{{{
#on_event = 'ColorScheme'
#hook_post_source = 'runtime add/incsearch-easymotion.vim'
#}}}
#[[plugins]]
#repo = 'haya14busa/incsearch-fuzzy.vim' #{{{
#on_event = 'ColorScheme'
#hook_post_source = 'runtime add/incsearch-fuzzy.vim'
#}}}
#}}}

#[[plugins]]
#repo = 'ripxorip/aerojump.nvim'
## seems buggy.
#on_map = {nox = '<Plug>(Aerojump'}
#hook_add = 'runtime add/aerojump.vim'

# Operater; Comment out
#[[plugins]]
#repo = 'tomtom/tcomment_vim' #{{{
## Memo: complex named <Plug>-mappings
#on_map = '<Plug>TComment'
#on_cmd = ':TComment'
#hook_add = 'runtime add/tcomment.vim'
##}}}
[[plugins]]
repo = 'tyru/caw.vim' #{{{
# operater to comment out
on_map = '<Plug>(caw:'
hook_add = 'runtime add/caw.vim'
#}}}
#[[plugins]]
#repo = 'scrooloose/nerdcommenter' #{{{
## Reason: has no operater
#on_map = '<Plug>NERDCommenter'
#hook_add = 'runtime add/nerdcommenter.vim'
##}}}
#[[plugins]]
#repo = 'tpope/vim-commentary' #{{{
## Simplest
#on_map = '<Cmd>Commentary'
#hook_add = 'runtime add/plugin.vim'
##}}}

# Operater; Arrangement
[[plugins]]
repo = 'machakann/vim-swap'
on_map = '<Plug>(swap-'
hook_add = 'runtime add/swap.vim'
[[plugins]]
repo = 'junegunn/vim-easy-align' #{{{
on_map = ['<Plug>(EasyAlign)', '<Plug>(LiveEasyAlign)']
hook_add = 'runtime add/easy-align.vim'
#}}}
#[[plugins]]
#repo = 'AndrewRadev/splitjoin.vim' #{{{
#on_event = 'BufRead'
#hook_post_source = 'runtime add/splitjoin.vim'
#}}}

# Operater; Simultaneous
[[plugins]]
repo = 'andymass/vim-matchup' #{{{
# Better `%`
on_event = 'VimEnter'
hook_add = 'runtime add/matchup.vim'
hook_post_source = 'runtime post/matchup.vim'
#}}}
[[plugins]]
repo = 'machakann/vim-sandwich' #{{{
on_map = {ni = '<Plug>(operator-sandwich-'} # too late via <c-o>
hook_add = 'runtime add/sandwich.vim'
#}}}
#[[plugins]]
#repo = 'tpope/vim-surround' #{{{
#on_event = 'BufRead'
#hook_post_source = 'runtime add/surround.vim'
#}}}
[[plugins]]
repo = 'terryma/vim-multiple-cursors' #{{{
on_event = ['BufRead']
hook_add = 'runtime add/multiple-cursors.vim'
#}}}
[[plugins]]
repo = 'matze/vim-move' #{{{
on_map = {nx = '<Plug>Move'}
hook_add = 'runtime add/move.vim'
#}}}
#[[plugins]]
#repo = 't9md/vim-textmanip' #{{{
## Note: has copy feature
#on_event = 'BufRead'
#hook_add = 'runtime add/textmanip.vim'
#}}}

#[[plugins]]
#repo = 'tommcdo/vim-express' #{{{
#on_event = 'VimEnter'
#hook_post_source = 'runtime add/express.vim'
##}}}
