# From: dein.toml

[[plugins]]
repo = 'kaile256/vim-among_HML'
on_cmd = 'among_HML#'
hook_add = 'runtime add/among_HML.vim'

[[plugins]]
repo = 'kaile256/vim-sensible_K'
# Note: defines no map/cmd, only using augroup.
on_event = 'VimEnter'
hook_add = 'runtime add/sensible_K.vim'
