# From: dein.vimrc

# Repeat
#[[plugins]]
#repo = 'tpope/vim-repeat' #{{{
## Note: <Plug>(coc-command-repeat) covers even easy-motion's such as `df<P`
## No Help
#on_event = ['TextChanged', 'TextChangedI']
##}}}

#[[plugins]]
#repo = 'fszymanski/fzf-gitignore' #{{{
#type = 'git'
##on_if = '@% =~# ".gitignore"'
#hook_post_source = 'runtime fzf-gitignore.vimrc'
##}}}

# Edit; Undo
[[plugins]]
repo = 'simnalamburt/vim-mundo' #{{{
on_map = ':Mundo'
hook_add = 'runtime mundo.vimrc'
#}}}
#[[plugins]]
#repo = 'jaxbot/selective-undo.vim' #{{{
## End of Dev?
#on_event = 'BufRead'
#hook_post_source = 'runtime selective-undo.vimrc'
##}}}
#[[plugins]]
#repo = 'machakann/vim-highlightedundo' #{{{
#if = 'executable("diff")'
#on_event = 'BufRead'
#hook_post_source = 'runtime highlightedundo.vimrc'
#}}}
#[[plugins]]
#repo = 'mbbill/undotree' #{{{
#on_map = 'Undotree'
#hook_add = 'runtime undotree.vimrc'
##}}}

# Edit; Inc/Decrement
#[[plugins]]
#repo = 'qwertologe/nextval.vim' #{{{
#on_map = '<Plug>nextval'
#hook_add = 'runtime nextval.vimrc'
##}}}

# Edit; Diff
[[plugins]]
repo = 'AndrewRadev/linediff.vim' #{{{
on_map = 'Linediff'
hook_add = 'runtime linediff.vimrc'
#}}}

# Fold
[[plugins]]
repo = 'LeafCage/foldCC' #{{{
on_event = 'BufWinEnter'
hook_post_source = 'runtime foldCC.vimrc'
#}}}
#[[plugins]]
#repo = 'SwintonStreet/HighlightFoldLevelVimScript' #{{{
# Seems not to work. May not get along with foldCC.
#hook_add = 'runtime HighlightFoldLevel.vimrc'
##}}}
#[[plugins]]
#repo = 'anschnapp/move-less' #{{{
#on_event = 'BufRead'
#hook_add = 'runtime move-less.vimrc'
#}}}
#[[plugins]]
#repo = 'tmhedberg/SimpylFold' #{{{
#on_ft = 'python'
#hook_post_source = 'runtime SimpylFold.vimrc'
##}}}

# Dein Extention
[[plugins]]
repo = 'wsdjeg/dein-ui.vim' #{{{
on_event = 'CmdlineEnter'
hook_post_source = 'runtime dein-ui.vimrc'
#}}}
[[plugins]]
repo = 'haya14busa/dein-command.vim' #{{{
# For `Dein list`
on_event = 'CmdlineEnter'
hook_post_source = 'runtime dein-command.vimrc'
#}}}

# Checker
[[plugins]]
repo = 'rhysd/vim-grammarous' #{{{
# Grammer Check
on_cmd = 'GrammarousCheck'
hook_add = 'runtime grammarous.vimrc'
#}}}
[[plugins]]
repo = 'rhysd/vim-themis'
on_cmd = ['BufRead']
hook_post_source = 'runtime themis.vimrc'

#[[plugins]]
#repo = 'chrisbra/NrrwRgn' #{{{
#on_event = 'VimEnter'
#hook_post_source = 'runtime NrrwRgn.vimrc'
##}}}
#[[plugins]]
#repo = 'AndrewRadev/switch.vim' #{{{
## toggle as predefined, such as 'true' & 'false'.
#on_if = '&modifiable'
#hook_post_source = 'runtime switch.vimrc'
#}}}

## Image Viewer
#[[plugins]]
#repo = 'Cj-bc/drcs.vim'
#rev = 'develop'
#on_event = ['jpeg', 'gif', 'png', 'drcs']
#hook_post_source = 'runtime drcs.vimrc'

# Template
#[[plugins]]
#repo = 'mattn/sonictemplate-vim' #{{{
#on_event = 'BufNew'
#hook_post_source = 'runtime sonictemplate.vimrc'
#}}}

# Developper Tool
[[plugins]]
repo = 'tweekmonster/helpful.vim'
on_cmd = 'HelpfulVersion'
hook_add = 'runtime helpful.vimrc'

[[plugins]]
repo = 'thinca/vim-scouter'
on_cmd = 'Scouter'
