# From: dein.vimrc

# Interface
#[[plugins]]
#repo = 'fszymanski/fzf-gitignore' #{{{
#type = 'git'
##on_if = '@% =~# ".gitignore"'
#hook_post_source = 'runtime fzf-gitignore.vimrc'
##}}}
[[plugins]]
repo = 'neoclide/coc.nvim' #{{{
rev = 'release'
on_event = 'VimEnter'
hook_post_source = 'runtime coc.vimrc'
#}}}
#[[plugins]]
#repo = 'Shougo/denite.nvim' #{{{
#if = 'has("python3")'
#hook_add = 'runtime denite.vimrc'
#[[plugins]]
#repo = 'Shougo/neoyank.vim' #{{{
#on_source = 'denite.nvim'
##}}}
#[[plugins]]
#repo = 'ozelentok/denite-gtags' #{{{
#on_source = 'denite.nvim'
##}}}
#[[plugins]]
#repo = 'rafi/vim-denite-session' #{{{
#on_source = 'denite.nvim'
##}}}
#[[plugins]]
#repo = 'neoclide/denite-git' #{{{
#on_source = 'denite.nvim'
##}}}
#[[plugins]]
#repo = 'Shougo/neomru.vim' #{{{
#on_source = 'denite.nvim'
##}}}
#[[plugins]]
#repo = 'neoclide/coc-denite' #{{{
## for Denite source
#on_source = 'denite.nvim'
#}}}
#[[plugins]]
#repo = 'raghur/fruzzy' #{{{
#on_source = 'denite.nvim'
#hook_post_source = 'runtime fruzzy.vimrc'
#}}}
##}}}
[[plugins]]
repo = 'tpope/vim-repeat' #{{{
# No Help
on_event = ['TextChanged', 'TextChangedI']
#}}}

# Edit; Fold
[[plugins]]
repo = 'LeafCage/foldCC' #{{{
on_event = 'BufWinEnter'
hook_post_source = 'runtime foldCC.vimrc'
#}}}
#[[plugins]]
#repo = 'tmhedberg/SimpylFold' #{{{
#on_ft = 'python'
#hook_post_source = 'runtime SimpylFold.vimrc'
##}}}

# Edit; Diff
[[plugins]]
repo = 'AndrewRadev/linediff.vim' #{{{
on_map = 'Linediff'
hook_add = 'runtime linediff.vimrc'
#}}}

# Template
#[[plugins]]
#repo = 'mattn/sonictemplate-vim' #{{{
#on_event = 'BufNew'
#hook_post_source = 'runtime sonictemplate.vimrc'
#}}}

# Dein Extention
[[plugins]]
repo = 'wsdjeg/dein-ui.vim' #{{{
on_event = 'CmdlineEnter'
hook_post_source = 'runtime dein-ui.vimrc'
#}}}
[[plugins]]
repo = 'haya14busa/dein-command.vim' #{{{
# For `Dein list`
on_event = 'CmdlineEnter'
hook_post_source = 'runtime dein-command.vimrc'
#}}}

# Checker
[[plugins]]
repo = 'rhysd/vim-grammarous' #{{{
# Grammer Check
on_cmd = 'GrammarousCheck'
hook_add = 'runtime grammarous.vimrc'
#}}}
[[plugins]]
repo = 'rhysd/vim-themis'
on_cmd = ['BufRead']
hook_post_source = 'runtime themis.vimrc'

#[[plugins]]
#repo = 'chrisbra/NrrwRgn' #{{{
#on_event = 'VimEnter'
#hook_post_source = 'runtime NrrwRgn.vimrc'
##}}}
#[[plugins]]
#repo = 'AndrewRadev/switch.vim' #{{{
## toggle as predefined, such as 'true' & 'false'.
#on_if = '&modifiable'
#hook_post_source = 'runtime switch.vimrc'
#}}}
