# From: add/dein.vim

[[plugins]]
repo = 'mattn/vim-findroot'
on_cmd = 'FindRoot'
hook_add = 'runtime add/findroot.vim'

#[[plugins]]
#repo = 'thinca/vim-ref' #{{{
#on_event = 'BufRead'
#hook_add = 'runtime rc/ref.vim'
##}}}

# Hex Editor
[[plugins]]
repo = 'd0c-s4vage/pfp-vim' #{{{
on_cmd = 'Pfp'
hook_add = 'runtime add/pfp.vim'
#}}}

# Repeat
[[plugins]]
repo = 'tpope/vim-repeat' #{{{
# Note: has no help
# Note: dein doesn't load this plugin, on unknown reason,
#       so I made a symlink to the directory at plugin/.
#       Therefore, the lazy loading doesn't work either.
on_map = '<Plug>(Repeat'
hook_add = 'runtime add/repeat.vim'
#}}}

# Floating Window
#[[plugins]]
#repo = 'ncm2/float-preview.nvim' #{{{
#on_source = ['delplete.nvim', 'coc.nvim']
#hook_post_source = 'runtime add/float-preview.vim'
##}}}
#[[plugins]]
#repo = 'voldikss/vim-floaterm' #{{{
#on_cmd = 'FloatermToggle'
#on_map = '<Plug>(floaterm-'
#hook_add = 'runtime add/floaterm.vim'
##}}}

# Interactive
#[[plugins]]
#repo = 'metakirby5/codi.vim' #{{{
## An interactive scratchpad for hackers.
#on_ft = ['python', 'javascript', 'coffeescript', 'haskell', 'ruby', 'OCaml', 'R', 'clojure', 'php', 'lua', 'cpp', 'julia', 'elm', 'elixir', 'typescript', 'mathjs']
#hook_post_source = 'runtime add/codi.vim'
##}}}

#[[plugins]]
#repo = 'fszymanski/fzf-gitignore' #{{{
#type = 'git'
##on_if = '@% =~# ".gitignore"'
#hook_post_source = 'runtime add/fzf-gitignore.vim'
##}}}

[[plugins]]
repo = 'severin-lemaignan/vim-minimap'
on_cmd = 'Minimap'
hook_add = 'runtime add/minimap.vim'
# the name, vim-minimap, causes error when jump to this repository.
hook_done_update = '''
exe 'e' g:dein_cache_dir .'/repos/github.com/severin-lemaignan/vim-minimap/autoload/minimap.py'
g/MINIMAP/s/vim-minimap/[minimap]/e
write
'''

# Edit; Undo
[[plugins]]
repo = 'simnalamburt/vim-mundo' #{{{
on_cmd = 'Mundo'
hook_add = 'runtime add/mundo.vim'
#}}}
#[[plugins]]
#repo = 'jaxbot/selective-undo.vim' #{{{
#on_event = 'BufRead'
#hook_post_source = 'runtime add/selective-undo.vim'
##}}}
#[[plugins]]
#repo = 'machakann/vim-highlightedundo' #{{{
#if = 'executable("diff")'
#on_event = 'BufRead'
#hook_post_source = 'runtime add/highlightedundo.vim'
#}}}
#[[plugins]]
#repo = 'mbbill/undotree' #{{{
#on_map = 'Undotree'
#hook_add = 'runtime add/undotree.vim'
##}}}

# Edit; Inc/Decrement
#[[plugins]]
#repo = 'qwertologe/nextval.vim' #{{{
#on_map = '<Plug>nextval'
#hook_add = 'runtime add/nextval.vim'
##}}}

# Edit; Diff
[[plugins]]
repo = 'AndrewRadev/linediff.vim' #{{{
on_cmd = 'Linediff'
hook_add = 'runtime add/linediff.vim'
#}}}
#[[plugins]]
#repo = 'chrisbra/vim-diff-enhanced' #{{{
#on_cmd = ['EnhancedDiff', 'PatienceDiff']
#hook_add = 'runtime diff-enhanced.vimrc'
##}}}

# Fold
#[[plugins]]
#repo = 'LeafCage/foldCC' #{{{
#on_event = 'BufWinEnter'
#hook_post_source = 'runtime add/foldCC.vim'
##}}}
[[plugins]]
repo = 'Konfekt/FastFold'
on_event = 'BufRead'
hook_source = 'runtime add/FastFold.vim'
#[[plugins]]
#repo = 'SwintonStreet/HighlightFoldLevelVimScript' #{{{
# Seems not to work. May not get along with foldCC.
#hook_add = 'runtime add/HighlightFoldLevel.vim'
##}}}
#[[plugins]]
#repo = 'anschnapp/move-less' #{{{
#on_event = 'BufRead'
#hook_add = 'runtime add/move-less.vim'
#}}}
#[[plugins]]
#repo = 'tmhedberg/SimpylFold' #{{{
#on_ft = 'python'
#hook_post_source = 'runtime add/SimpylFold.vim'
##}}}

# Dein Extention
[[plugins]]
repo = 'wsdjeg/dein-ui.vim' #{{{
on_event = 'CmdlineEnter'
hook_post_source = 'runtime add/dein-ui.vim'
#}}}
[[plugins]]
repo = 'haya14busa/dein-command.vim' #{{{
# For `Dein list`
on_event = 'CmdlineEnter'
hook_post_source = 'runtime add/dein-command.vim'
#}}}

## Image Viewer
#[[plugins]]
#repo = 'Cj-bc/drcs.vim' #{{{
#rev = 'develop'
#on_event = ['jpeg', 'gif', 'png', 'drcs']
#hook_post_source = 'runtime add/drcs.vim'
##}}}

# Template
#[[plugins]]
#repo = 'mattn/sonictemplate-vim' #{{{
#on_event = 'BufNew'
#hook_post_source = 'runtime add/sonictemplate.vim'
#}}}

# Checker
[[plugins]]
repo = 'rhysd/vim-grammarous' #{{{
# Grammer Check
on_cmd = 'GrammarousCheck'
hook_add = 'runtime add/grammarous.vim'
#}}}
#[[plugins]]
#repo = 'chrisbra/NrrwRgn' #{{{
#on_event = 'VimEnter'
#hook_post_source = 'runtime add/NrrwRgn.vim'
##}}}
#[[plugins]]
#repo = 'AndrewRadev/switch.vim' #{{{
## toggle as predefined, such as 'true' & 'false'.
#on_if = '&modifiable'
#hook_post_source = 'runtime add/switch.vim'
#}}}

# Developper Tool
[[plugins]]
repo = 'tpope/vim-scriptease'
on_cmd = 'scriptease#'
hook_add = 'runtime add/scriptease.vim'
[[plugins]]
repo = 'thinca/vim-scouter' #{{{
on_cmd = 'Scouter'
#}}}
#[[plugins]]
#repo = 'tweekmonster/dyslexic.vim' #{{{
## Spell checker according to <cword>.
#on_cmd = 'Dyslexic'
#hook_add = 'runtime dyslexic.vimrc'
##}}}
[[plugins]]
repo = 'tweekmonster/helpful.vim' #{{{
on_cmd = 'HelpfulVersion'
hook_add = 'runtime add/helpful.vim'
#}}}
[[plugins]]
repo = 'rhysd/vim-themis' #{{{
# A library of vim-script for test-making.
hook_post_source = 'runtime add/themis.vim'
#}}}
[[plugins]]
repo = 'junegunn/vader.vim' #{{{
# a test-framework for vimscript.
on_cmd = 'Vader'
hook_add = 'runtime add/vader.vim'
#}}}
