# From: dein.vimrc

[[plugins]]
repo = 'neoclide/coc.nvim' #{{{
# Should be lazy loaded to `:call coc#util#install()` automatically.
rev = 'release'
on_event = 'VimEnter'
hook_post_source = 'runtime coc.vimrc'
#}}}
[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_if = 'has("python3")'
on_event = ['InsertEnter']
hook_post_source = 'runtime deoplete.vimrc'

# Git;
[[plugins]]
repo = 'rhysd/git-messenger.vim'
type = 'git'
on_event = 'BufRead'
hook_post_source = 'runtime git-messenger.vimrc'
[[plugins]]
repo = 'junegunn/gv.vim'
type = 'git'
on_ft = ['fugitive', 'gitcommit', 'git']
#on_source = 'vim-fugitive'
hook_post_source = 'runtime gv.vimrc'
[[plugins]]
repo = 'rhysd/committia.vim'
type = 'git'
on_ft = ['fugitive', 'gitcommit', 'git']
#on_source = 'vim-fugitive'
hook_post_source = 'runtime committia.vimrc'


# Leap;
[[plugins]]
repo = 'bkad/CamelCaseMotion' #{{{
on_event = 'VimEnter'
hook_post_source = 'runtime CamelCaseMotion.vimrc'
#}}}
[[plugins]]
repo = 'easymotion/vim-easymotion' #{{{
on_event = 'ColorScheme'
hook_post_source = 'runtime easymotion.vimrc'
[[plugins]]
repo = 'haya14busa/vim-easyoperator-phrase' #{{{
on_event = 'ColorScheme'
hook_post_source = 'runtime easyoperator.vimrc'
#}}}
#[[plugins]]
#repo = 'haya14busa/incsearch.vim' #{{{
#on_event = 'ColorScheme'
#hook_post_source = 'runtime incsearch.vimrc'
#}}}
#[[plugins]]
#repo = 'haya14busa/incsearch-easymotion.vim' #{{{
#on_event = 'ColorScheme'
#hook_post_source = 'runtime incsearch-easymotion.vimrc'
#}}}
#[[plugins]]
#repo = 'haya14busa/incsearch-fuzzy.vim' #{{{
#on_event = 'ColorScheme'
#hook_post_source = 'runtime incsearch-fuzzy.vimrc'
#}}}
#}}}

# Filer
#[[plugins]]
#repo = 'cocopon/vaffle.vim' #{{{
#on_if = 'has("python3")'
#hook_post_source = 'runtime vaffle.vimrc'
##}}}
#[[plugins]]
#repo = 'Shougo/defx.nvim' #{{{
### CAUTION: defx.vimrc MUST be sourced after dein#end() on dein.vim.
#on_if = 'has("python3")'
#hook_post_source = 'runtime defx.vimrc'
#hook_done_update = 'UpdateRemotePlugins'
#[[plugins]]
#repo = 'kristijanhusak/defx-git' #{{{
## Ref: defx.vimrc
#on_source = 'defx.nvim'
##}}}
#[[plugins]]
#repo = 'kristijanhusak/defx-icons' #{{{
#on_source = 'defx.nvim'
##}}}
##}}}
#[[plugins]]
#repo = 'justinmk/vim-dirvish'
#on_event = 'BufAdd'
#hook_post_source = 'runtime dirvish.vimrc'

# Edit; Operater
[[plugins]]
repo = 'machakann/vim-sandwich' #{{{
on_event = 'BufRead'
hook_post_source = 'runtime sandwich.vimrc'
#}}}
#[[plugins]]
#repo = 'tpope/vim-surround'{{{
#on_event = 'BufRead'
#hook_post_source = 'runtime surround.vimrc'
#}}}
[[plugins]]
repo = 'tpope/vim-repeat' #{{{
on_event = ['TextChanged', 'TextChangedI']
#}}}

# Edit; Fold
[[plugins]]
repo = 'LeafCage/foldCC' #{{{
on_event = 'BufWinEnter'
hook_post_source = 'runtime foldCC.vimrc'
#}}}
[[plugins]]
repo = 'tmhedberg/SimpylFold' #{{{
on_ft = 'python'
hook_post_source = 'runtime SimpylFold.vimrc'
#}}}

# Edit; Diff
[[plugins]]
repo = 'AndrewRadev/linediff.vim'
on_map = ['v', '<c-v>', 'V']
hook_post_source = 'runtime linediff.vimrc'

# Edit; Snippets
## Snippets; Engine #{{{
#[[plugins]]
#repo = 'Shougo/neosnippet.vim' #{{{
#on_event = ['InsertEnter', 'TermOpen','CmdlineEnter']
#hook_add = 'runtime! neosnippet.vimrc'
##}}}
[[plugins]]
repo = 'SirVer/ultisnips' #{{{
on_event = ['InsertEnter','TermOpen']
hook_post_source = 'runtime ultisnips.vimrc'
#}}}
#}}}

# Snippets; Contents #{{{
[[plugins]]
repo = 'Shougo/neosnippet-snippets' #{{{
on_event = ['InsertEnter', 'TermOpen','CmdlineEnter']
#}}}
[[plugins]]
repo = 'honza/vim-snippets' #{{{
on_event = ['InsertEnter', 'TermOpen']
#}}}
#[[plugins]]
#repo = 'garbas/vim-snipmate' #{{{
#on_event = ['InsertEnter', 'TermOpen']
#}}}
#}}}

# Marks {{{
[[plugins]]
repo = 'mattesgroeger/vim-bookmarks' #{{{
on_map = 'm'
hook_post_source = 'runtime bookmarks.vimrc'
#}}}
#[[plugins]]
#repo = 'jacquesbh/vim-showmarks'{{{
#on_map = ['m','`',"'",'<space>']
#hook_post_source = 'runtime showmarks.vimrc'
# }}}
#}}}

# Imput Method #{{{
[[plugins]]
repo = 'tyru/eskk.vim' #{{{
on_event = ['InsertEnter', 'CmdlineEnter']
hook_post_source = 'runtime eskk.vimrc'
#}}}
#[[plugins]]
#repo = 'tpope/vim-capslock' #{{{
## Doesn't Work
#on_event = ['InsertEnter', 'CmdlineEnter']
#hook_post_source = 'runtime capslock.vimrc'
##}}}
#[[plugins]]
#repo = 'mattn/vim-switch-esc-capslock' #{{{
#### For Windows?
#on_event = ['InsertEnter', 'CmdlineEnter']
#hook_post_source = 'runtime switch-esc-capslock'
##}}}
# }}}

# Vimwiki; Outliner #{{{
[[plugins]]
repo = 'vim-voom/VOoM' #{{{
on_ft = ['vimwiki','org','markdown','tex','toml']
hook_post_source = 'runtime voom.vimrc'
# }}}

## Table-Mode #{{{
#[[plugins]]
#repo = 'dhruvasagar/vim-table-mode' #{{{
#hook_add = 'runtime table-mode.vimrc'
#on_ft = ['org', 'text', 'vimwiki', 'md']
# }}}
# }}}

## Org Mode
#[[plugins]]
#repo = 'jceb/vim-orgmode' #{{{
#on_ft = 'org'
#hook_post_source = 'runtime orgmode.vimrc'
##}}}
#### Hyperlink
#[[plugins]]
#repo = 'vim-scripts/utl.vim' #{{{
#on_ft = 'org'
#hook_post_source = 'runtime utl.vimrc'
##}}}
##[[plugins]]
##repo = 'tpope/vim-speeddating' #{{{
### <c-a/x> for dateing.
##on_ft = 'org'
##hook_post_source = 'runtime speeddating.vimrc'
##}}}
##}}}

# Twitter {{{
[[plugins]]
repo = 'basyura/TweetVim' #{{{
on_event = 'CmdlineEnter'
hook_post_source = 'runtime tweetvim.vimrc'
#}}}
[[plugins]]
repo = 'basyura/twibill.vim' # {{{
on_event = 'CmdlineEnter'
hook_post_source = 'runtime twibill.vimrc'
#}}}
#}}}

#[[plugins]]
#repo = 'inkarkat/vim-SyntaxRange' #{{{
## Multiple-Language Syntax in one buffer.
#on_ft = ['snippets','org']
#hook_post_source = 'runtime SyntaxRange.vimrc'
##}}}
#[[plugins]]
#repo = 'chrisbra/NrrwRgn' #{{{
#on_event = 'VimEnter'
#hook_post_source = 'runtime NrrwRgn.vimrc'
##}}}

# Template
#[[plugins]]
#repo = 'mattn/sonictemplate-vim' #{{{
#on_event = 'BufNew'
#hook_post_source = 'runtime sonictemplate.vimrc'
#}}}

### Operator #{{{
[[plugins]]
repo = 'machakann/vim-sandwich' #{{{
on_event = 'BufRead'
hook_post_source = 'runtime sandwich.vimrc'
#}}}
[[plugins]]
repo = 'junegunn/vim-easy-align' #{{{
on_event = 'BufRead'
hook_post_source = 'runtime easy-align.vimrc'
#}}}
#[[plugins]]
#repo = 'AndrewRadev/splitjoin.vim' #{{{
#on_event = 'BufRead'
#hook_post_source = 'runtime splitjoin.vimrc'
#}}}
#[[plugins]]
#repo = 'tpope/vim-surround' #{{{
#on_event = 'BufRead'
#hook_post_source = 'runtime surround.vimrc'
#}}}
#}}}

# Shell; Deol
[[plugins]]
repo = 'kassio/neoterm'
on_event = 'BufAdd'
hook_post_source = 'runtime neoterm.vimrc'
[[plugins]]
repo = 'Shougo/deol.nvim' #{{{
on_cmd = ['te','tb','ts','tv']
hook_post_source = 'runtime deol.vimrc'
#}}}
## Shell; Async Processor
[[plugins]]
repo = 'thinca/vim-quickrun' #{{{
on_map = 'QuickRun'
hook_post_source = 'runtime quickrun.vimrc'
#}}}
[[plugins]]
repo = 'neomake/neomake' #{{{
on_map = 'make'
hook_post_source = 'runtime neomake.vimrc'
#}}}
#[[plugins]]
#repo = 'skywind3000/asyncrun.vim' #{{{
## Only supports external shell to qf.
#on_map = 'AsyncRun'
#hook_post_source = 'runtime asyncrun.vimrc'
#}}}
#[[plugins]]
#repo = 'Shougo/vimproc.vim' #{{{
## run vim-plugins asynchronously, like openbrowser, quickrun.
#build = 'make'
#}}}

# Browser
[[plugins]]
repo = 'tyru/open-browser.vim' #{{{
on_if = 'executable("qutebrowser")'
hook_post_source = 'runtime open-browser.vimrc'
#}}}
[[plugins]]
repo = 'tyru/open-browser-github.vim' #{{{
on_source = 'open-browser.vim'
hook_post_source = 'runtime open-browser-github.vimrc'
#}}}

# Calendar
[[plugins]]
repo = 'itchyny/calendar.vim' #{{{
on_event = 'VimEnter'
on_cmd = '<a-q>'
hook_post_source = 'runtime calendar.vimrc'
#}}}

### Tags
[[plugins]]
repo = 'jsfaint/gen_tags.vim' #{{{
on_event = 'BufLeave'
hook_post_source = 'runtime gen_tags.vimrc'
#}}}
#[[plugins]]
#repo = 'majutsushi/tagbar' #{{{
#on_event = ['BufNew','BufReadPost']
#hook_post_source = 'runtime tagbar.vimrc'
#}}}
[[plugins]]
repo = 'liuchengxu/vista.vim' #{{{
on_event = ['BufNew','BufRead']
hook_post_source = 'runtime vista.vimrc'
#}}}

# UI
[[plugins]]
repo = 'wsdjeg/dein-ui.vim' #{{{
on_event = 'CmdlineEnter'
hook_post_source = 'runtime dein-ui.vimrc'
#}}}

### i3-wm
#[[plugins]]
#repo = 'termhn/i3-vim-nav'
#on_if = 'isdirectory("~/go/src/github.com/termhn/i3-vim-nav")'
#hook_post_source = 'runtime i3-vim-nav.vimrc'

# Denite {{{
#[[plugins]]
#repo = 'Shougo/denite.nvim' #{{{
#if = 'has("python3")'
#hook_add = 'runtime denite.vimrc'
##}}}
#[[plugins]]
#repo = 'Shougo/neoyank.vim'
#on_source = 'denite.nvim'
#[[plugins]]
#repo = 'ozelentok/denite-gtags'
#on_source = 'denite.nvim'
#[[plugins]]
#repo = 'rafi/vim-denite-session'
#on_source = 'denite.nvim'
#[[plugins]]
#repo = 'neoclide/denite-git'
#on_source = 'denite.nvim'
#[[plugins]]
#repo = 'Shougo/neomru.vim'
#on_source = 'denite.nvim'
#[[plugins]]
#repo = 'neoclide/coc-denite' #{{{
## for Denite source
#on_source = 'denite.nvim'
#}}}
#[[plugins]]
#repo = 'raghur/fruzzy' #{{{
#on_source = 'denite.nvim'
#hook_post_source = 'runtime fruzzy.vimrc'
#}}}
#}}}

# Linux Command
#[[plugins]]
#repo = 'tpope/vim-eunuch' #{{{
## ERORR: Seems no utils provided by the plugin.
#on_event = 'CmdlineEnter'
#hook_post_source = 'runtime eunuch.vimrc'
#}}}
