# From: dein/dein.vim

[[plugins]]
repo = 'dense-analysis/ale'
if = '!exists("g:vscode")'
# Support more linters than LSP as an interface.  Though ale also supports LSP,
# coc.nvim deals with LSP better than ale.
on_event = ['BufRead']
hook_source = 'source $DEIN_RC_DIR/ale/sou.vim'
# # [[plugins]]
# repo = 'mattn/vim-ale-icons'
# # Emoji icons for ale's diagnostics.
# on_source = ['ale']
# [[plugins]]
# repo = 'wellle/context.vim'
# # Note: irritative, though very useful plugin.
# # Show the begining line of block where cursor is, when hidden over window.
# on_cmd = ['ContextEnable']
# hook_add = 'source $DEIN_RC_DIR/context/add.vim'
# hook_source = 'source $DEIN_RC_DIR/context/sou.vim'
# # hook_post_source = 'source $DEIN_RC_DIR/context/pos.vim'
#
#[ Indent ]
# [[plugins]]
# repo = 'nathanaelkane/vim-indent-guides'
# # Fill indent by colors
# on_ft = 'snippets'
# hook_source = 'runtime source/indent-guides.vim'
[[plugins]]
repo = 'glepnir/indent-guides.nvim'
# Async. As vim-indent-guides, show indent in color blocks.
if = 'has("nvim") && !exists("g:vscode")'
on_event = ['BufRead']
hook_post_source = 'luafile $DEIN_RC_DIR/indent-guides/pos.lua'
[[plugins]]
repo = 'Yggdroot/indentLine'
# Show indent levels by characters using vim's conceal feature.
if = '!has("nvim")'
on_event = 'BufRead'
hook_source = 'runtime source/indentLine.vim'
#[[plugins]]
#repo = 'thaerkh/vim-indentguides'
#on_event = 'BufRead'

#[ Cursor ]
[[plugins]]
repo = 'delphinus/vim-auto-cursorline'
# Just show cursorline after cursor holded for a while.
on_event = ['WinEnter']
hook_source = 'source $DEIN_RC_DIR/auto-cursorline/sou.vim'
[[plugins]]
repo = 'itchyny/vim-cursorword'
# Underlines appear on every word under the cursor.
on_event = 'BufAdd'
# Error: no such Event CursorWord0
#hook_add = 'let g:cursorword_highlight = 0'
hook_post_source = 'runtime add/cursorword.vim'
[[plugins]]
repo = 'kevinhwang91/nvim-hlslens'
if = 'has("nvim") && !exists("g:vscode")'
on_lua = ['hlslens']
on_event = ['CmdlineEnter']
hook_add = 'source $DEIN_RC_DIR/hlslens/add.vim'
hook_source = 'luafile $DEIN_RC_DIR/hlslens/pos.lua'
#[ Emphasize ]
#[[plugins]]
#repo = 't9md/vim-quickhl'
#on_map = {
#  nx = '<Plug>(quickhl-',
#  n  = '<Plug>(operator-quickhl-',
#}
#hook_add = 'runtime add/quickhl.vim'
#hook_post_source = 'runtime post/quickhl.vim'
# [[plugins]]
# # repo = 'junegunn/goyo.vim'
# on_cmd = 'Goyo'
[[plugins]]
repo = 'junegunn/limelight.vim'
# Note: requires &termguicolors = 1
on_map = {nx = '<Plug>(Limelight'}
on_cmd = 'Limelight'
hook_add = 'runtime add/limelight.vim'
hook_source = 'runtime source/limelight.vim'
hook_post_source = 'runtime post/limelight.vim'
[[plugins]]
repo = 'machakann/vim-highlightedyank'
# coc's highlight on yank sometimes leaves the highlight after the role.
on_event = ['TextYankPost']
hook_source = 'runtime source/highlightedyank.vim'

#[ Rainbow ]
[[plugins]]
repo = 'p00f/nvim-ts-rainbow'
if = 'has("nvim")'
depends = ['nvim-treesitter']
on_event = ['BufRead']
hook_post_source = 'luafile $DEIN_RC_DIR/treesitter/rainbow/pos.lua'
[[plugins]]
repo = 'luochen1990/rainbow'
if = '!exists("g:vscode")'
# Notice: to activate, either g:rainbow_active or g:rainbow_conf must exists.
on_func = 'rainbow_main#load'
hook_add = 'runtime add/rainbow.vim'
hook_source = 'runtime source/rainbow.vim'
#[[plugins]]
#repo = 'kien/rainbow_parentheses.vim'
# less scripts than 'frazrepo/vim-rainbow'
#on_func = ['rainbow_parentheses#']
#on_ft = [
#  'c',
#  'cpp',
#  'objc',
#  'objcpp',
#  'go',
#  'java',
#  'rust',
#]
#hook_source = 'runtime source/rainbow_parentheses.vim'
#[[plugins]]
#repo = 'frazrepo/vim-rainbow'
## customizable up to filetypes
#on_func = ['rainbow#']
#on_cmd = ['RainbowLoad']
#hook_add = 'runtime add/rainbow-frazrepo.vim'
#hook_source = 'runtime source/rainbow-frazrepo.vim'
#[[plugins]]
#repo = 'thiagoalessio/rainbow_levels.vim'
## changes highlight as the indent, *not* up to parentheses
#on_cmd = ['RainbowLevelsOn', 'RainbowLevelsToggle']

# [[plugins]]
# repo = 'kshenoy/vim-signature'
# # Show marks in signcolumn.
# on_event = ['BufRead']
#[ Icons ]
# [[plugins]]
# repo = 'ryanoasis/vim-devicons'
# on_source = ['denite.nvim', 'vim-airline', 'lightline.vim']
[[plugins]]
repo = 'kyazdani42/nvim-web-devicons'
if = 'has("nvim")'
on_source = [
  'feline.nvim',
  'galaxyline.nvim',
]

#[ Font ]
# [[plugins]]
# repo = 'delphinus/artify.nvim'
# Note: Could not render on urxvt?
# # Apply artistic font style in part. Typically, replace some components in
# # statusline/tabline. Find the available styles in README of the original
# # `sainnhe/artify.vim`.
# if = 'has("nvim")'
# on_lua = ['artify']
#
#[ Tabline ]
[[plugins]]
repo = 'seblj/nvim-tabline'
if = 'has("nvim")'
on_event = ['BufRead']
hook_post_source = 'luafile $DEIN_LUA_DIR/tabline/pos.lua'
# [[plugins]]
# repo = 'akinsho/nvim-bufferline.lua'
# if = 'has("nvim")'
# on_event = ['BufRead']
# hook_post_source = 'luafile $DEIN_LUA_DIR/bufferline/pos.lua'
#
#[ Statusline ]
#[[plugins]]
#repo = 'vim-airline/vim-airline'
## to use extentions, it check by exists('*foo'); surely loaded after all the
## plugin are loaded before vim-airline is loaded.
## on_source is slower to be set.
#on_if = "exists('*FugitiveHead') && exists(':CocCommand')"
#on_event = ['Syntax']
## Uncompatible with nyaovim?
## Better to be sourced earlier than colorschemes
##hook_add = '''
##" make sure extention to work
##if !exists('*FugitiveHead')
##  function! FugitiveHead(...) abort
##    call fugitive#head(join(a:000, ','))
##  endfunction
##endif
##'''
#hook_source = 'runtime source/airline.vim'
#hook_post_source = 'set noshowmode noruler'
#[[plugins]]
#repo = 'vim-airline/vim-airline-themes'
## Note: original only has 'dark'
#on_source = ['vim-airline']
#[[plugins]]
#repo = 'renyard/vim-git-flow-format'
#type = 'git'
#depends = 'vim-airline'
#on_event = ['BufRead']
[[plugins]]
repo = 'famiu/feline.nvim'
# Inspired by galaxyline, but intended to be more minimal and customizable.
if = 'has("nvim")'
depends = [
  'nvim-web-devicons',
  'gitsigns.nvim', # For built-in git providers
]
on_lua = ['feline']
on_event = ['BufRead']
hook_post_source = 'luafile $DEIN_LUA_DIR/feline/pos.lua'
# [[plugins]]
# # repo = 'glepnir/galaxyline.nvim'
# # Written in lua, inspired by lightline.
# if = 'has("nvim")'
# on_event = ['BufRead']
# hook_post_source = 'luafile $DEIN_LUA_DIR/galaxyline/pos.lua'
# [[plugins]]
# repo = 'ojroques/nvim-hardline'
# # Invalid on theme
# if = 'has("nvim")'
# on_lua = ['hardline']
# on_event = ['BufRead']
# hook_post_source = 'luafile $DEIN_LUA_DIR/hardline/sou.lua'
[[plugins]]
repo = 'itchyny/lightline.vim'
if = '!has("nvim")'
on_event = 'Syntax'
hook_source = 'source $DEIN_RC_DIR/lightline/sou.vim'
hook_post_source = 'source $DEIN_RC_DIR/lightline/pos.vim'
# [[plugins]]
# repo = 'josa42/vim-lightline-coc'
# on_source = 'lightline.vim'
# [[plugins]]
# repo = 'adelarsq/neoline.vim'
# # Inspired by lightline.  Written in Lua.
# on_event = ['Syntax']
#[[plugins]]
#repo = 'albertomontesg/lightline-asyncrun'
## provides an indicator to tell async jobs running in background.
#on_source = 'vim-airline'
#depends = 'asyncrun.vim'
#hook_post_source = 'runtime add/lightline-asyncrun.vim'
#[[plugins]]
#repo = 'taohexxx/lightline-buffer'
#on_source = 'lightline.vim'
#hook_post_source = 'runtime add/lightline-buffer.vim'

#[[plugins]]
#repo = 'edkolev/promptline.vim'
#on_event = ['TermOpen']
## Note: this plugin is for shell
## TODO: necessary to config for bash/zsh/fish to use this plugin
#hook_post_source = 'runtime post/promptline.vim'
[[plugins]]
repo = 'gcavallanti/vim-noscrollbar'
# Visualize relational cursor position in statusline/tabline.
# You can use it in lightline.
on_func = 'noscrollbar#statusline'
# [[plugins]]
# # repo = 'Xuyuanp/scrollbar.nvim'
# if = 'has("nvim")'
# on_event = ['WinEnter']
# hook_add = 'runtime add/scrollbar.vim'
#
#[ Color Visualizer ]
[[plugins]]
repo = 'norcalli/nvim-colorizer.lua'
if = 'has("nvim")'
on_event = ['BufRead']
hook_post_source = 'luafile $DEIN_RC_DIR/colorizer/pos.lua'

#[ Color Picker ]
[[plugins]]
repo = 'naquad/vim-picker'
lazy = 0
[[plugins]]
repo = 'DougBeney/pickachu'
on_cmd = 'Pickachu'
hook_add = 'runtime add/pickachu.vim'

