# From: dein/dein.vim
# Else: syntax.toml
# Else: compiler.toml
# Else: script.toml
# Else: xampp.toml

#[ Multiple FileType ]
[[plugins]]
repo = 'editorconfig/editorconfig-vim'
# Note: coc-prettier doesn't use editorconfig if prettier is either unavailable.
# Note: vim-prettier is unnecessary, though it also covers editorconfig.
on_event = 'BufWinEnter'
hook_source = 'runtime source/editorconfig.vim'
# [[plugins]]
# repo = 'prettier/vim-prettier'
# # Note: also read .editorconfig
# build = 'yarn install'
# on_map = {nx = '<Plug>(Prettier'}
# on_cmd = ['Prettier', 'PrettierAsync', 'PrettierCli']
# hook_source = 'runtime source/prettier.vim'
#[[plugins]]
#repo = 'tpope/vim-sleuth'
## Note: Sleuth means a detective.
## Enough with coc-prettier?
## Automatically adjusts 'shiftwidth' and 'expandtab'
#on_event = ['BufNewFile','BufRead']
#hook_add = 'runtime add/sleuth.vim'
#[[plugins]]
#repo = 'vim-syntastic/syntastic'
#on_ft = ['toml']
#hook_post_source = 'runtime add/syntastic.vim'
[[plugins]]
repo = 'Shougo/context_filetype.vim'
lazy = 0

#[ XML ]
#[[plugins]]
#repo = 'tpope/vim-ragtag'
## provides mappings for these filetypes
#on_ft = [
#  '*html*', 'wml', 'jsp', 'gsp', 'mustache', 'smarty',
#  'php', 'asp*', 'cf', 'mason', 'eruby', 'liquid', 'jst', 'eelixir',
#  'xml', 'xslt', 'xsd', 'docbk',
#  'javascript.jsx', 'jsx', 'javascriptreact', 'handlebars',
#  'typescript.tsx', 'tsx', 'typescriptreact',
#]
#[[plugins]]
#repo = 'sukima/xmledit'
#on_ft = ['html', 'php', 'xhtml', 'xml']
#build = 'make install'

#[ SuperCollider ]
[[plugins]]
repo = 'supercollider/scvim'
# includes fake REPL, tag-jumps, auto-completion via tags.
on_path = '\.scd\?$'
[[plugins]]
repo = 'davidgranstrom/scnvim'
# includes snippets on UltiSnips
if = 'has("nvim")'
hook_done_update = 'call scnvim#install()'
on_path = '\.scd\?$'

#[ Web ]
[[plugins]]
repo = 'yardnsm/vim-import-cost'
# shows how large files will be imported each lines in virtualtext; without
# virtualtext-feature, it will open a window to show the info.
build = 'npm install'
on_path = ['*.js', '*.jsx','*.ts','*.tsx']
hook_source = 'runtime source/import-cost.vim'
