# From: dein/dein.vim

#[ coc.nvim ]
[[plugins]]
repo = 'neoclide/coc.nvim'
# Branch: neoclide/coc.nvim_release; no src/, but build/.
rev = 'release'
if = '!exists("g:vscode")'
#hook_done_update = 'yarn install --frozen-lockfile'
on_func  = ['CocAction', 'CocActionAsync']
on_map  = {nvi = ['<Plug>(coc-']}
on_event = 'BufRead'
hook_add    = '''
runtime add/coc.vim
runtime add/coc.jump.vim
'''
hook_source = 'runtime source/coc.vim'
hook_done_update = '''
e $DEIN_GITHUB_DIR/neoclide/coc.nvim_release/plugin/coc.vim
" For: vim-fugitive creates invalid id buffer.
" use expand('%:p'), not '<abuf>'
g;BufEnter;v;\.git/;g;call;norm! niif expand('%:p') !~# '\.git/' |
g;BufEnter;v;endif;norm! A | endif
write
"" For: rename :CocFoo to :Cfoo in the local-repo.
"" CocFoo is used by the other coc-extentions; should not be replaced.
"let s:CocUpper2Clower = 'dgnguliC'
"g/command!/g/Coc/copy. | exe 'norm!' s:CocUpper2Clower
"unlet s:CocUpper2Clower
"write
'''
[[plugins]]
repo = 'antoinemadec/coc-fzf'
# Useless to select another options.
on_cmd = ['CocFzfList']
hook_add = 'runtime add/coc-fzf.vim'
[[plugins]]
repo = 'kizza/actionmenu.nvim'
if = 'has("nvim")'
# Provides coc.nvim actionmenu features for such as 'codeAction'.
on_source = 'coc.nvim'
hook_post_source = 'runtime add/actionmenu.vim'
#[[plugins]]
#repo = 'neoclide/redismru.vim'
# Redis; Remote Dictionary Server
#if = 'executable("redis")'
#on_source = 'denite.nvim'
#hook_post_source = 'runtime add/redismru.vim'
[[plugins]]
repo = 'pwntester/codeql.nvim'
if = 'has("nvim")'
# Integrate with 'neovim/nvim-lsp' or 'coc.nvim'.
on_ft = ['ql']

#[ vim-lsp ]
#[[plugins]]
#repo = 'prabirshrestha/vim-lsp'
## Written in Pure viml
##hook_add = 'runtime add/lsp.vim'
#[[plugins]]
#repo = 'prabirshrestha/async.vim'
#on_source = 'vim-lsp'
#[[plugins]]
#repo = 'prabirshrestha/asyncomplete.vim'
#on_event = 'BufRead'
#hook_post_source = 'runtime add/asyncomplete.vim'
#[[plugins]]
#repo = 'prabirshrestha/asyncomplete-lsp.vim'
#on_event = 'BufRead'
#hook_post_source = 'runtime add/asyncomplete-lsp.vim'
#[[plugins]]
#repo = 'autozimu/LanguageClient-neovim'
## Note: Written in Rust.
#rev = 'next'
#build = 'bash install.sh'
#on_event = 'BufRead'
#hook_add = 'runtime add/LanguageClient.vim'
#[[plugins]]
#repo = 'OmniSharp/omnisharp-vim'
#on_event = 'BufRead'
#hook_add = 'runtime add/omnisharp.vim'

#[ Format ]
#[[plugins]]
#repo = 'rhysd/vim-clang-format'
## only formats written headers; not insert new
#on_ft = ['c', 'cpp', 'objc', 'javascript', 'java', 'typescript', 'protobuf']
#on_source = 'runtime source/clang-format.vim'
