# From: dein/dein.vim

#[ Zettelkasten ]
[[plugins]]
repo = 'oberblastmeister/neuron.nvim'
if = 'executable("neuron")'
on_source = ['telescope.nvim']
depends = ['telescope.nvim']
on_lua = ['neuron']
hook_add = 'source $DEIN_RC_DIR/neuron/add.vim'
hook_source = 'luafile $DEIN_RC_DIR/neuron/sou.lua'
# [[plugins]]
# repo = 'megalithic/zk.nvim'
# # The searcher on telescope is NYI; on fzf depends on nvim-fzf.
# # `go get -u github.com/mickael-menu/zk` to install the binary.
# if = 'has("nvim") && executable("zk")'
# on_path = '^.*/neuron/.*$'
# hook_source = 'luafile $DEIN_RC_DIR/zk/sou.lua'
#
#[ Org Mode ]
# [[plugins]]
# repo = 'jceb/vim-orgmode'
# on_path = 'org$'
# hook_source = 'runtime source/orgmode.vim'
# [[plugins]]
# repo = 'dhruvasagar/vim-dotoo'
# on_path = 'dotoo$'
#
#[ Task Management ]
# [[plugins]]
# repo = 'https://gitlab.com/igrep/text_kanban.vim'
# on_cmd = 'TextKanbanOpenBoard'
# on_func = 'text_kanban#open_board'
#[[plugins]]
#repo = 'vitalk/vim-simple-todo'
## just create mappings which produce a list inserting "[ ]" and so on.
#on_map = {niv = '<Plug>(simple-todo-'}
#hook_add = 'runtime add/simple-todo.vim'
#hook_source = 'runtime source/simple-todo.vim'

#[ Scratch ]
#[[plugins]]
#repo = 'mtth/scratch.vim'
## Note: cannot :source in it
#on_cmd = ['Scratch']
#on_map = {nx = '<Plug>(scratch-'}

#[ Table-Mode ]
[[plugins]]
repo = 'dhruvasagar/vim-table-mode'
on_cmd = [
  'Tableize',
  'TableAddFormula',
  'TableModeRealign'
]
on_map = {
  ox = '<Plug>(table-mode-cell-text-object-',
  nox = '<Plug>(table-mode-motion-'
}
hook_add = 'runtime add/table-mode.vim'
hook_source = 'runtime source/table-mode.vim'

#[ Outliner ]
#[[plugins]]
#repo = 'vim-voom/VOoM'
#on_ft = ['vimwiki','org','markdown','tex','toml']
#hook_post_source = 'runtime add/voom.vim'

##[ Vimwiki ]
#[[plugins]]
#repo = 'vimwiki/vimwiki'
## causes an error of too recursive syntax in fenced block of markdown
#rev = 'dev'
#on_ft = ['vimwiki', 'markdown']
##hook_add = 'runtime add/vimwiki.vim'
#hook_source = 'runtime source/vimwiki.vim'
#[[plugins]]
#repo = 'tbabej/taskwiki'
#if = 'executable("task")'
#on_source = 'vimwiki'
#hook_post_update = '!pip install --user --upgrade -r requirements.txt'
#hook_source = 'runtime add/taskwiki.vim'
#[[plugins]]
#repo = 'powerman/vim-plugin-AnsiEsc'
## Provides Color support on chart of taskwiki.
#if = 'executable("task")'
#on_cmd = ['TaskWiki']
#hook_post_source = 'runtime add/AnsiEsc.vim'

#[ Task Worrior ]
#[[plugins]]
#repo = 'blindFS/vim-taskwarrior'
## enables grid-view on taskwiki.
#if = "executable('task')"
#on_cmd = ['TW']
#on_map = {nx = '<Plug>(taskwarrior'}
#hook_post_source = 'runtime source/taskwarrior.vim'

#[[plugins]]
#repo = 'vim-scripts/utl.vim'
## Org; Activate Hyperlink
#on_ft = 'org'
#hook_post_source = 'runtime add/utl.vim'

#[[plugins]]
#repo = 'tpope/vim-speeddating'
## <c-a/x> for dateing.
#on_ft = 'org'
#hook_post_source = 'runtime add/speeddating.vim'

#[[plugins]]
#repo = 'inkarkat/vim-SyntaxRange'
## Multiple-Language Syntax in one buffer.
#on_ft = ['snippets','org']
#hook_post_source = 'runtime add/SyntaxRange.vim'
