# From: dein/dein.vim

[[plugins]]
repo = 'kana/vim-operator-user'
lazy = 0
hook_add = 'source $DEIN_RC_DIR/operator/user/add.vim'
[[plugins]]
repo = 'thinca/vim-operator-sequence'
lazy = 0
[[plugins]]
repo = 'osyo-manga/vim-operator-exec_command'
# Ref: https://bit.ly/3fOqC1L
# -- Blog: operator-gn to dot-repeat
# Note: `lazy = 0` fails to work.
on_func = [
 'operator#exec_command#mapexpr_gn',
 'operator#exec_command#mapexpr_gN',
]
hook_add = 'runtime add/operator-exec_command.vim'

#[ Comment out ]
# [[plugins]]
# repo = 'tomtom/tcomment_vim'
# # Memo: complex named <Plug>-mappings
# on_map = '<Plug>TComment'
# hook_add = 'runtime add/tcomment.vim'
[[plugins]]
repo = 'tyru/caw.vim'
# operater requires kana/vim-operator-user
# Note: no use <Plug>(caw:foo:bar:operator), why?
on_map = '<Plug>(caw:'
hook_add = 'runtime add/caw.vim'
hook_source = 'runtime source/caw.vim'
#[[plugins]]
#repo = 'scrooloose/nerdcommenter'
## Reason: has no operater
#on_map = '<Plug>NERDCommenter'
#hook_add = 'runtime add/nerdcommenter.vim'
#[[plugins]]
#repo = 'tpope/vim-commentary'
## Simplest
#on_map = '<Cmd>Commentary'
#hook_add = 'runtime add/plugin.vim'

#[ Arrangement ]
[[plugins]]
repo = 'machakann/vim-swap'
# Swap parameters positions. It also includes textobjects.
on_map = {nox = '<Plug>(swap-'}
hook_add = 'runtime add/swap.vim'
# [[plugins]]
# # repo = 'AndrewRadev/sideways.vim'
# # Swap parameters positions. It also includes textobjects.
# # Addition to comma-separated parameters, it also detects css declarations
# # which separated by ';', HTML attributes, Cucumber tables components, Go lists
# # surrounded by '{}', etc.
# # Moreover, configurable globally/localy like switch.vim
# on_cmd = 'Sideways'
# on_map = {ox = '<Plug>Sideways'}
# hook_add = 'runtime add/sideways.vim'
# hook_source = 'runtime source/sideways.vim'
[[plugins]]
repo = 'AndrewRadev/switch.vim'
# switch as predefined, such as "true" & "false".
on_cmd = ['Switch', 'SwitchReverse']
on_func = ['switch#']
on_map = {n = '<Plug>(switch-'}
hook_add = 'source $DEIN_RC_DIR/switch/add.vim'
hook_source = 'source $DEIN_RC_DIR/switch/sou.vim'
hook_post_source = '''
  source $DEIN_RC_DIR/switch/local_definitions.vim
'''
# [[plugins]]
# repo = 'nishigori/increment-activator'
# # almost same as AndrewRadev/switch.vim; configurable in Dict of filetypes.
# # Note: it only work for word boundary.
# on_map = {ni = ['<Plug>(increment-activator']}
# hook_add = 'runtime add/increment-activator.vim'
[[plugins]]
repo = 'junegunn/vim-easy-align'
on_map = ['<Plug>(EasyAlign)', '<Plug>(LiveEasyAlign)']
on_cmd = 'EasyAlign'
hook_add = 'source $DEIN_RC_DIR/easy-align/add.vim'
[[plugins]]
repo = 'emonkak/vim-operator-sort'
on_map = {nx = ['<Plug>(operator-sort']}
hook_add = 'runtime add/operator-sort.vim'

#[ Simultaneous ]
[[plugins]]
# repo = 'machakann/vim-sandwich'
repo = 'kaile256/vim-sandwich'
on_map = {
  nx = ['<Plug>(operator-sandwich-'],
  ox = ['<Plug>(textobj-sandwich-',],
}
on_event = ['BufRead']
hook_add = 'source $DEIN_RC_DIR/sandwich/add.vim'
hook_source = 'source $DEIN_RC_DIR/sandwich/sou.vim'
hook_post_source = 'source $DEIN_RC_DIR/sandwich/pos.vim'
#[[plugins]]
#repo = 'tpope/vim-surround'
#on_event = 'BufRead'
#hook_post_source = 'runtime add/surround.vim'

#[[plugins]]
#repo = 'tommcdo/vim-express'
#on_event = 'VimEnter'
#hook_post_source = 'runtime add/express.vim'

#[ Substitute ]
[[plugins]]
repo = 'hauleth/sad.vim'
# asterisk-like operator
on_map = {nox = '<Plug>(sad'}
hook_add = 'runtime add/sad.vim'
#[[plugins]]
#repo = 'svermeulen/vim-subversive'
## just puts selected area into :s.
#on_map = {nx = ['<Plug>(Subversive']}
#hook_add = 'runtime add/subversive.vim'

#[ Swap ]
[[plugins]]
repo = 'tommcdo/vim-exchange'
 # Note: sometimes fails to clear highlight
on_map = {nx = ['<Plug>(Exchange']}
hook_add = 'source $DEIN_RC_DIR/exchange/add.vim'
hook_source = 'source $DEIN_RC_DIR/exchange/sou.vim'
#[[plugins]]
#repo = 'osyo-manga/vim-operator-swap'
## Require another plugin to highlight selected area.
## Require 2 keys to be mapped.
#on_map = {nx = ['<Plug>(operator-swap']}
#hook_add = 'runtime add/operator-swap.vim'
# [[plugins]]
# repo = 'SausageCats/vim-operator-swap'
# # No linear mapping.
# # Require 2 keys to be mapped.
# on_map = {nx = ['<Plug>(operator-swap-']}
# hook_add = 'runtime add/operator-swap-SausageCats.vim'
# hook_source = 'runtime source/operator-swap-SausageCats.vim'
#
#[ Copy ]
# [[plugins]]
# repo = 'emugel/vim-ictrlye'
# i_<C-e>/<C-y> to start operator.
# on_event = 'InsertEnter'
