# From: dein/dein.vim

#[ Browser ]
[[plugins]]
repo = 'tyru/open-browser.vim'
on_map = {nx = '<Plug>(openbrowser-'}
on_cmd = 'OpenBrowser'
on_func = 'openbrowser#'
# hook_add = 'runtime add/open-browser.vim'
hook_source = 'runtime source/open-browser.vim'

[[plugins]]
repo = 'tyru/open-browser-github.vim'
depends = 'open-browser.vim'
on_cmd = [
  'OpenGithubFile',
  'OpenGithubIssue',
  'OpenGithubPullReq',
  'OpenGithubProject',
  'OpenGithubCommit',
]

# [[plugins]]
# repo = 'aiya000/vim-webpage'
# on_cmd =  ['WebpageShow']
# on_func =  ['webpage#']
# hook_add = 'runtime add/webpage.vim'
# hook_source = 'runtime source/webpage.vim'
#[[plugins]]
#repo = 'notomo/ctrlb.nvim'
## let Vim control a browser in remote.
## Note: only supports firefox?
#build = 'npm run setup'
#on_cmd = ['Ctrlb']

#[ On Browser ]
[[plugins]]
repo = 'glacambre/firenvim'
on_func = 'firenvim#'
hook_done_update = 'call firenvim#install(0)'
hook_source = 'runtime source/firenvim.vim'

#[[plugins]]
#repo = 'raghur/vim-ghost'
## depends on chrome's extention or firefox's addon.
#hook_done_update = 'GhostInstall'
#on_cmd = 'Ghost'
#
[[plugins]]
repo = 'mattn/qiita-vim'
on_cmd = ['Qiita']

#[[plugins]]
#repo = 'aiya000/vim-webpage'
#on_cmd =  ['WebpageShow']

#[ APIs ]
[[plugins]]
repo = 'wakatime/vim-wakatime'
# tracking service for coding activity.
# Note: visit https://wakatime.com/settings/api-key before using this plugin.
#on_cmd = 'WakaTime' # has to start in background
on_event = ['VimEnter']
# [[plugins]]
# # repo = 'romgrk/todoist.nvim'
# # Note: exact `on_cmd = 'Todoist'` will delete ':Todoist' after once it
# # executed.
# on_cmd = 'Todois'
# # Note: `hook_source` won't set g:todoist['key'] on time.
# hook_add = 'runtime add/todoist.vim'
# hook_post_source = 'runtime post/todoist.vim'
# hook_done_update = 'TodoistInstal'

#[ Google ]
[[plugins]]
repo = 'itchyny/calendar.vim'
on_cmd = 'Calendar'
hook_source = 'runtime source/calendar.vim'
# Note: hook_add fails on VimEnter, BufEnter and so on.
hook_source = 'runtime add/wakatime.vim'
# [[plugins]]
# repo = 'mattn/googletasks-vim'
# # Only interactive at once in echo style.
# on_cmd = 'GoogleTasks'
# [[plugins]]
# # repo = 'mbsperry/done.vim'
# # Interact with GoogleTasks asynchronously.
# on_cmd = ['Tasks', 'AddTask']
#
#[ Collaborative Editing ]
# [[plugins]]
# repo = 'Floobits/floobits-neovim'
# on_cmd = ['FlooShareDirPublic', 'FlooShareDirPrivate', 'FlooJoinWorkspace']
#[[plugins]]
#repo = 'basyura/twibill.vim'
#on_cmd = 'TweetVim'
[[plugins]]
repo = 'jbyuki/instant.nvim'
if = 'has("nvim-0.4.4")'
on_cmd = ['InstantStart', 'InstantJoin']
hook_source = 'source $DEIN_RC_DIR/instant/sou.vim'

#[ WebAPI ]
[[plugins]]
repo = 'mattn/webapi-vim'
# an interface
lazy = 0
[[plugins]]
repo = 'soramugi/pocket.vim'
on_cmd = ['PocketList', 'PocketArchive', 'PocketFavorite']
hook_add = 'runtime add/pocket.vim'

# API; Twitter
#[[plugins]]
#repo = 'basyura/TweetVim'
#depends = 'twibill.vim'
#on_cmd = 'TweetVim'
#hook_post_source = 'runtime add/tweet.vim'

#[[plugins]]
#repo = 'ankokumoyashi/weblio_vim'
## TODO: make it work
#script_type = 'plugin'
#on_cmd = ['Weblio']
#hook_add = 'runtime add/weblio.vim'

#[ Slack ]
#[[plugins]]
#repo = 'higashi000/sarahck.vim'
## nvim is partially unsupported
#on_cmd = [
#  'SarahckChannelList',
#  'SarahckCreateChannel',
#  'SarahckDM',
#  'SarahckDispChannel',
#  'SarahckJoinChannel',
#  'SarahckLeaveChannel',
#  'SarahckPostMessage',
#]
#hook_source = 'runtime source/sarahck.vim'
#
[[plugins]]
repo = 'yaasita/edit-slack.vim'
on_path = 'slack:\/\/'
on_func = [
  'edit_slack#open#buffer',
  'edit_slack#open#sidebar',
]
hook_add = 'runtime add/edit-slack.vim'
hook_source = 'runtime source/edit-slack.vim'
build = '''
  # get the binary of yaasita/edit-slack
  git clone --depth=1 https://github.com/yaasita/edit-slack
  go build -o ../tmp -pkgdir edit-slack/

  rm -rf edit-slack/
  mv tmp edit-slack
'''

#[ Gist ]
[[plugins]]
repo = 'mattn/gist-vim'
on_cmd = 'Gist'
hook_source = 'runtime source/gist.vim'

#[ AtCoder ]
[[plugins]]
repo = 'ka-tsu-mo/at-vim-coder'
on_cmd = 'AtVimCoder'
hook_source = 'runtime source/at-vim-coder.vim'
[[plugins]]
repo = 'cannot-fly-pig/vim-atcoder'
if = '!has("nvim")'
on_cmd = 'Atcoder'
[[plugins]]
repo = 'ianding1/leetcode.vim'
on_cmd = 'LeetCode'

#[ Client ]
[[plugins]]
repo = 'mattn/vim-reading-vimrc'
# Requires `go get github.com/mattn/gitter-cli`
if = '!has("nvim")'
on_cmd = 'ReadingVimrc'
[[plugins]]
repo = 'dansomething/vim-hackernews'
on_cmd = 'HackerNews'

