#!/bin/sh

!!!! From: .xinitrc
!!!!  Ref: Xmodmap
!! Comments: leave ! on head of line to comment out.
!!  Source: start with #include, like #include ".Xresources.d/xterm"
!! ~/.Xresources

!!!! urxvt (rxvt-unicode)
URxvt.termName: rxvt-256color

!!! Window-Size (default: 80x24)
URxvt.geometry:             96x32

!!! Scroll-Bar
URxvt.scrollBar_right:      false
URxvt.scrollBar_floating:   false  ! true: no-bg on scrollbar.
URxvt.scrollstyle:          plain

URxvt.cursorBlink:          true
URxvt.cursorUnderline:      true
URxvt.pointerBlank:         true

URxvt.visualBell:           true
URxvt.saveLines:            3000

!!! Fading except Current-Window (%)
URxvt.fading:               40

!! Font list and Spacing
URxvt.font:                 xft:Dejavu Sans Mono-11,\
                            xft:Nerd
URxvt.letterSpace:          -1  ! prepare exagerated space esp. on Japanese Fonts.
!URxvt.lineSpace:            2  ! expand space between command-lines.

!!! Color Scheme and Opacity - gruvbox-dark https://github.com/morhetz/gruvbox
! Define opacity in []; [100] is no-opacity, [0] is completely invisible.
URxvt.depth:       32

URxvt.color0:      [90]#282828    /* black          */
URxvt.color1:      [90]#cc241d    /* red            */
URxvt.color2:      [90]#98971a    /* green          */
URxvt.color3:      [90]#d79921    /* yellow         */
URxvt.color4:      [90]#458588    /* blue           */
URxvt.color5:      [90]#b16286    /* magenta        */
URxvt.color6:      [90]#689d6a    /* cyan           */
URxvt.color7:      [90]#a89984    /* white          */
URxvt.color8:      [90]#928374    /* bright black   */
URxvt.color9:      [90]#fb4934    /* bright red     */
URxvt.color10:     [90]#b8bb26    /* bright green   */
URxvt.color11:     [90]#fabd2f    /* bright yellow  */
URxvt.color12:     [90]#83a598    /* bright blue    */
URxvt.color13:     [90]#d3869b    /* bright magenta */
URxvt.color14:     [90]#8ec07c    /* bright cyan    */
URxvt.color15:     [90]#ebdbb2    /* bright white   */

URxvt.foreground:  [90]#ebdbb2
URxvt.background:  [90]#282828

!! Italic/Bold/UnderLine
URxvt.colorIT:     [90]#8ec07c
URxvt.colorBD:     [90]#fe8019
URxvt.colorUL:     [90]#83a598

URxvt.scrollColor: [90]#504945
!URxvt.troughColor: [90]#3C3836  ! bg-color of scrollbar.

!!!! EXTENTION
!! CAUTION: spare extra extentions to save RAM.
URxvt.perl-ext:
URxvt.perl-ext-common:

exec i3
!exec i3 -V >> ~/.local/share/i3/i3log-$(date +'%F-%k-%M-%S') 2>^1

!!!!! XTERM
!!!! General
!XTerm*termName: xterm-256color
!Term*scrollBar: False
!XTerm*cursorBlink: True
!
!!! Fonts and Encoding
!XTerm*utf8: True
!XTerm*locale: True
!XTerm*utf8Title: True
!XTerm*faceName: xft:DejaVu Sans Mono
!XTerm*faceNameDoublesize: xft:IPAGothic
!XTerm*faceSize: 9
!XTerm*scaleHeight: 1.08
!
!!! Color Scheme : Tomorrow Night
!!! https://github.com/chriskempson/tomorrow-theme
!
!XTerm*background: #1D1F21
!XTerm*foreground: #C5C8C6
!! black
!XTerm*color0: #282A2E
!XTerm*color8: #373B41
!! red
!XTerm*color1: #A54242
!XTerm*color9: #CC6666
!! green
!XTerm*color2: #8C9440
!XTerm*color10: #B5BD68
!! yellow
!XTerm*color3: #DE935F
!XTerm*color11: #F0C674
!! blue
!XTerm*color4: #5F819D
!XTerm*color12: #81A2BE
!! magenta
!XTerm*color5: #85678F
!XTerm*color13: #B294BB
!! cyan
!XTerm*color6: #5E8D87
!XTerm*color14: #8ABEB7
!! white
!XTerm*color7: #707880
!XTerm*color15: #C5C8C6

!twm &
!xclock -geometry 50x50-1+1 &
!xterm -geometry 80x50+494+51 &
!xterm -geometry 80x20+494-0 &
!exec xterm -geometry 80x66+0+0 -name login
!xterm*faceSize: 23
