[[plugins]]
repo = 'nvim-lua/popup.nvim'
[[plugins]]
repo = 'nvim-lua/plenary.nvim'

[[plugins]]
repo = 'nvim-telescope/telescope.nvim'
on_cmd = 'Telescope'
depends = ['popup.nvim', 'plenary.nvim']
hook_add = 'source $DEIN_RC_DIR/telescope/add.vim'
hook_post_source = 'luafile $DEIN_RC_DIR/telescope/pos.lua'

[[plugins]]
repo = 'nvim-telescope/telescope-github.nvim'
on_source = 'telescope.nvim'
[[plugins]]
repo = 'nvim-telescope/telescope-vimspector.nvim'
on_source = 'vimspector'
