[[plugins]]
repo = 'nvim-telescope/telescope.nvim'
on_cmd = 'Telescope'
on_map = {c = ['<Plug>(Telescope']}
depends = ['popup.nvim', 'plenary.nvim']
hook_add = 'source $DEIN_LUA_DIR/telescope/add.vim'
hook_post_source = 'luafile $DEIN_LUA_DIR/telescope/pos.lua'

# [[plugins]]
# repo = 'nvim-telescope/telescope-fzf-native.nvim'
# build = 'make'
# depends = ['telescope.nvim']
# on_source = ['telescope.nvim']
# hook_post_source = 'luafile $DEIN_LUA_DIR/telescope/fzf-native/pos.lua'

[[plugins]]
repo = 'nvim-telescope/telescope-github.nvim'
on_source = 'telescope.nvim'
hook_post_source = '''
lua << EOD
require"telescope".load_extension("gh")
EOD
'''
[[plugins]]
repo = 'nvim-telescope/telescope-vimspector.nvim'
on_source = 'vimspector'
hook_post_source = 'luafile $DEIN_LUA_DIR/telescope/vimspector/pos.lua'
# [[plugins]]
# repo = 'nvim-telescope/telescope-symbols.nvim'
# Insert symbols like Emoji which is listed in `data/telescope-sources/*.json`
# # at &ftp.
# on_source = ['telescope.nvim']
# hook_add = 'source $DEIN_LUA_DIR/telescope/symbols/add.vim'

[[plugins]]
repo = 'pwntester/octo.nvim'
# Edit issues, PRs, etc., of GitHub
depends = ['plenary.nvim', 'telescope.nvim']
on_cmd = 'Octo'
hook_source = 'luafile $DEIN_LUA_DIR/telescope/octo/sou.lua'

# [[plugins]]
# repo = 'fannheyward/telescope-coc.nvim'
# depends = ['coc.nvim']
# on_source = ['telescope.nvim']
# hook_post_source = 'luafile $DEIN_LUA_DIR/telescope/coc/pos.lua'

[[plugins]]
repo = 'DevonMorris/telescope-docker.nvim'
if = 'executable("docker")'
hook_post_source = 'luafile $DEIN_LUA_DIR/telescope/docker/pos.lua'

[[plugins]]
repo = 'nvim-telescope/telescope-frecency.nvim'
depends = ['telescope.nvim', 'sql.nvim']
on_source = ['telescope.nvim']
hook_post_source = '''
lua << EOD
require"telescope".load_extension("frecency")
EOD
'''
[[plugins]]
repo = 'tami5/sql.nvim'
# SQLite/LuaJIT binding.
