[[plugins]]
repo = 'nvim-lua/popup.nvim'
[[plugins]]
repo = 'nvim-lua/plenary.nvim'

[[plugins]]
repo = 'nvim-telescope/telescope.nvim'
on_cmd = 'Telescope'
depends = ['popup.nvim', 'plenary.nvim']
hook_add = 'source $DEIN_RC_DIR/telescope/add.vim'
hook_post_source = 'luafile $DEIN_RC_DIR/telescope/pos.lua'

[[plugins]]
repo = 'nvim-telescope/telescope-github.nvim'
on_source = 'telescope.nvim'
hook_post_source = 'luafile $DEIN_RC_DIR/telescope/github/pos.lua'
[[plugins]]
repo = 'nvim-telescope/telescope-vimspector.nvim'
on_source = 'vimspector'
# [[plugins]]
# repo = 'nvim-telescope/telescope-symbols.nvim'
# Insert symbols like Emoji which is listed in `data/telescope-sources/*.json`
# # at &ftp.
# on_source = ['telescope.nvim']
# hook_add = 'source $DEIN_RC_DIR/telescope-symbols/add.vim'
# 
[[plugins]]
repo = 'pwntester/octo.nvim'
# Edit issues, PRs, etc., of GitHub
depends = ['plenary.nvim', 'telescope.nvim']
on_cmd = 'Octo'

