# From dein/dein.vim

[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
on_event = 'BufRead'
hook_done_update = 'TSUpdate'
hook_source = 'source $DEIN_RC_DIR/treesitter/sou.vim'

# [[plugins]]
# repo = 'p00f/nvim-ts-rainbow'
# on_source = 'nvim-treesitter'
# on_event = 'BufRead'
# hook_post_source = 'luafile $DEIN_RC_DIR/treesitter/rainbow/pos.lua'
[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter-refactor'
depends = 'nvim-treesitter'
on_event = 'BufRead'
hook_post_source = 'luafile $DEIN_RC_DIR/treesitter/refactor/pos.lua'
# [[plugins]]
# repo = 'nvim-treesitter/nvim-treesitter-textobjects'
# # It's a problem to override mappings for yet undefined nodes in queries.
# depends = 'nvim-treesitter'
# on_event = 'BufRead'
# hook_source = 'luafile $DEIN_RC_DIR/treesitter-textobjects/sou.lua'
#
[[plugins]]
repo = 'nvim-treesitter/playground'
# View treesitter's infomation.
on_cmd = ['TSPlaygroundToggle']
hook_source = 'luafile $DEIN_RC_DIR/playground/sou.lua'

[[plugins]]
repo = 'JoosepAlviste/nvim-ts-context-commentstring'
# Give lua functions to update &cms in some filetypes.
# Related to Shougo/context_filetype.vim.
depends = ['nvim-treesitter']
on_ft = ['javascriptreact', 'typescriptreact', 'vue']
hook_post_source = 'source $DEIN_RC_DIR/treesitter/context-commentstring/pos.vim'
