# From dein/dein.vim

[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
on_event = 'BufRead'
hook_done_update = 'TSUpdate'
hook_source = 'source $DEIN_RC_DIR/treesitter/sou.vim'

# [[plugins]]
# # repo = 'p00f/nvim-ts-rainbow'
# on_source = 'nvim-treesitter'
# on_event = 'BufRead'
[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter-refactor'
depends = 'nvim-treesitter'
on_event = 'BufRead'
hook_source = 'luafile $DEIN_RC_DIR/treesitter-refactor/sou.lua'
# [[plugins]]
# repo = 'nvim-treesitter/nvim-treesitter-textobjects'
# # It's a problem to override mappings for yet undefined nodes in queries.
# depends = 'nvim-treesitter'
# on_event = 'BufRead'
# hook_source = 'luafile $DEIN_RC_DIR/treesitter-textobjects/sou.lua'
#
[[plugins]]
repo = 'nvim-treesitter/playground'
# View treesitter's infomation.
on_cmd = ['TSPlaygroundToggle']
hook_source = 'luafile $DEIN_RC_DIR/playground/sou.lua'
