alias tmux 'tmux -2'
alias l 'ls -la'
alias la 'ls -A'
alias ll 'ls -l'
alias ec 'echo'
alias ech 'echo'
alias pk '~/start-kail.sh'
alias mirrors 'sudo pacman-mirrors -f && sudo pacman -Syy'
alias cz 'cd (ghq list --full-path | fzf)'
#alias rustlings 'bash && cd ~/rustlings && rustlings'
