#### Required
[[plugins]]
repo = 'Shougo/dein.vim'
hook_add = '''
  " source plugins configs after dein activates.
  runtime! config.d/plugin.d/**.vimrc
  '''

### Async Processor
[[plugins]]
# run vim-plugins asynchronously, inc., quickrun.
repo = 'Shougo/vimproc.vim'
build = 'make'

### Run Code on vim
[[plugins]]
repo = 'thinca/vim-quickrun'
hook_add = '''
  let g:quickrun_config = {}
  let g:quickrun_config['markdown'] = {
    \ 'outputter': 'browser'
    \ }
  '''

### Start Page
[[plugins]]
repo = 'mhinz/vim-startify'

### Filer
[[plugins]]
repo = 'kristijanhusak/defx-git'
depends = 'defx.nvim'
[[plugins]]
repo = 'kristijanhusak/defx-icons'
depends = 'defx.nvim'
[[plugins]]
repo = 'Shougo/defx.nvim'
hook_done_update= '''
  au VimEnter * :UpdateRemotePlugins<cr>
  '''
#### Plugins Visual
## Color Themes
[[plugins]]
repo = 'tomasr/molokai'
 
#[[plugins]]
#repo = 'altercation/vim-colors-solarized'

## Status Bar
#[[plugins]]
#repo = 'itchyny/lightline.vim' # config is written in 'plugin.vim'
[[plugins]]
repo = 'vim-airline/vim-airline'
[[plugins]]
repo = 'vim-airline/vim-airline-themes'
depends = 'vim-airline'
