## Color Themes
[[plugins]]
repo = 'tomasr/molokai'
on_if = 'has("nvim")'
hook_post_source = 'runtime! molokai.vimrc'
 
#[[plugins]]
#repo = 'altercation/vim-colors-solarized'

### Run Code on vim
[[plugins]]
repo = 'skywind3000/asyncrun.vim'
on_map = 'AsyncRun'
hook_post_source = 'runtime! asyncrun.vimrc'
[[plugins]]
repo = 'thinca/vim-quickrun'
on_map = 'QuickRun'
hook_post_source = 'runtime! quickrun.vimrc'
hook_post_source = '''
  let g:quickrun_config = {}
  let g:quickrun_config['markdown'] = {
    \ 'outputter': 'browser'
    \ }
  '''

### Filer
[[plugins]]
repo = 'kristijanhusak/defx-git'
depends = 'defx.nvim'
on_map = 'Defx'
[[plugins]]
repo = 'kristijanhusak/defx-icons'
depends = 'defx.nvim'
on_map = 'Defx'
[[plugins]]
repo = 'Shougo/defx.nvim'
on_map = 'Defx'
hook_post_source = '''
  if exists('expand("g:python3_host_prog")') | runtime! defx.vimrc | endif
  '''

### Buffer
[[plugins]]
repo = 'Shougo/denite.nvim'
on_map = 'Denite'
hook_post_source = '''
  if exists('expand("g:python3_host_prog")') | runtime! denite.vimrc | endif
  '''
[[plugins]]
repo = 'Shougo/neoyank.vim'
on_map = 'Denite'
[[plugins]]
repo = 'ozelentok/denite-gtags'
hook_post_source = 'runtime! denite-gtags.vimrc'
on_map = 'Denite'

## On Term Mode
[[plugins]]
repo = 'mhinz/neovim-remote'
on_event = 'TermOpen'

#### Smooth Edit 
### QuickRun
[[plugins]]
repo = 'neomake/neomake'
if = 'version >= 800'
hook_post_source = 'runtime! neomake'
on_map = 'make'

### Template
[[plugins]]
repo = 'mattn/sonictemplate-vim'
on_event = 'BufRead'

#[[plugins]]
## preset a template respectively.
#repo = 'thinca/vim-template'
#on_event = 'BufReadPre'
#on_ft = 'bash'

### Visual
## Indent
[[plugins]]
# indent line should be visible
repo = 'Yggdroot/indentLine'
hook_post_source = '''
  let g:indentline_color_term = 239
  '''
on_event = 'BufReadPre'
## Paren
[[plugins]]
repo = 'luochen1990/rainbow'
on_event = 'WinEnter'
hook_post_source = '''
  " set 0 to active only on :RainbowToggle
  let g:reinbow_active = 1
  '''

### Functional
[[plugins]]
# Repeats even not-default editing by "."
# e.g., surround.vim
repo = 'tpope/vim-repeat'
on_event = 'BufRead'

## Jump
[[plugins]]
repo = 'jremmen/vim-ripgrep'
on_map = 'Rg'
hook_post_source = '''
  if exists('expand("g:python3_host_prog")') | runtime! ripgrep.vimrc | endif
  '''
#[[plugins]]
#repo = 'justinmk/vim-sneak'
#on_map = '<Plug>'
#depend = 'vim-repeat'
#hook_post_source = 'runtime! sneak.vimrc'
[[plugins]]
# Show marks
repo = 'jacquesbh/vim-showmarks'
on_map = '<c-u>'
hook_post_source = 'runtime! showmarks.vimrc'

[[plugins]]
repo = 'machakann/vim-sandwich'
on_event = 'BufRead'
#[[plugins]]
#repo = 'tpope/vim-surround'
#on_event = 'BufRead'

#[[plugins]]
## auto close parens
#repo = 'cohama/lexima.vim'
#on_event = 'InsertEnter'

#[[plugins]]
#repo = 'Lokaltog/vim-easymotion'
#on_event = 'VimEnter'
## move between Vim panes and Tmux splits seamlessly.
#[[plugins]]
#repo = 'christoomey/vim-tmux-navigator'
#on_event = 'VimEnter'

## Ctags
[[plugins]]
# generate ctags & gtags.
repo = 'jsfaint/gen_tags.vim'
on_event = 'VimEnter'
[[plugins]]
repo = 'majutsushi/tagbar'
on_event = 'BufRead'
#[[plugins]]
#repo = 'szw/vim-tags'
#on_event = 'VimEnter'
#[[plugins]]
#repo = 'ludovicchabant/vim-gutentags'
#on_event = 'VimEnter'
# No any .txt file
#[[plugins]]
## written by python
## auto-delete entries that no longer exist.
#repo = 'craigemery/vim-autotag'
#hook_post_source = '''
#  let g:autotagTagsFile='.tags'
#  '''
#on_event = 'VimEnter'

### Completion
[[plugins]]
repo = 'ycm-core/YouCompleteMe'
on_event = 'InsertEnter'
hook_post_source = 'runtime! YouCompleteMe.vimrc'

#[[plugins]]
#repo = 'neoclide/coc.nvim'
#hook_post_source = 'runtime! coc.vimrc'
#on_event = 'VimEnter'
#hook_post_update = '''
#  au VimEnter * call coc#util#install()
#  au VimEnter * CocInstall coc-json coc-tsserver coc-html coc-yaml coc-python 
#  \ coc-git coc-yank coc-vimlsp coc-highlight
#  '''

### FZF
[[plugins]]
repo = 'junegunn/fzf'
on_event = '[InsertEnter,CmdwinEnter]'
[[plugins]]
repo = 'junegunn/fzf.vim'
on_event = '[InsertEnter,CmdwinEnter]'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'
on_event = 'InsertEnter'
on_ft = 'snippets'
[[plugins]]
repo = 'Shougo/neosnippet.vim'
hook_post_source = 'runtime! neosnippet.vimrc'
on_event = 'InsertEnter'
on_ft = 'snippets'


## Browser on vim
[[plugins]]
repo = 'tyru/open-browser.vim'
hook_post_source = 'runtime! open-browser.vimrc'
on_map = '<Plug>'
hook_post_source = '''
  let g:netrw_nogx = 1 " disable netrw's gx mapping.
  nnoremap gx <Plug>(openbrowser-smart-search)
  vnoremap gx <Plug>(openbrowser-smart-search)
  '''

## Memo
[[plugins]]
repo = 'glidenote/memolist.vim'
hook_post_source = 'runtime! memolist.vimrc'
on_map = '<leader>'

#[[plugins]]
#repo = 'tyru/qfpopup.vim'
#[[plugins]]
#repo = 'liuchengxu/vista.vim'
#depends = ['coc.nvim']
#on_event = 'InsertEnter'

## open DevDocs from vim
## still need more settings
#repo = 'rhysd/devdocs.vim'
#on_map = '<Plug>'
#hook_post_source = '''
#  nnoremap K <Plug>(devdocs-under-cursor)
#  '''
