#### By dein.vim

### Required
[[plugins]]
repo = 'Shougo/dein.vim'
hook_add = '''
  set rtp+=~/.config/nvim/config.d/plugin.d
  '''
hook_done_update= '''
    au VimEnter :UpdateRemotePlugins<cr>
  '''

### Async Processor
#[[plugins]]
## run vim-plugins asynchronously, inc., quickrun.
#repo = 'Shougo/vimproc.vim'
#build = 'make'

### Start Page
#[[plugins]]
#repo = 'mhinz/vim-startify'
#hook_add = 'runtime! startify.vimrc'
