#!/usr/bin/env bash
# Ref: https://github.com/DanielFGray/fzf-scripts

has() {
  local verbose=false
  if [[ $1 == '-v' ]]; then
    verbose=true
    shift
  fi
  for c in "$@"; do c="${c%% *}"
    if ! command -v "$c" &> /dev/null; then
      [[ "$verbose" == true ]] && err "$c not found"
      return 1
    fi
  done
}

err() {
  printf '\e[31m%s\e[0m\n' "$*" >&2
}

die() {
  (( $# > 0 )) && err "$*"
  exit 1
}

has -v nmcli fzf || die

nmcli device wifi rescan 2> /dev/null
network=$(nmcli --color yes device wifi | fzf --ansi --height=40% --reverse --cycle --inline-info --header-lines=1)
[[ -z "$network" ]] && exit
network=$(sed -r 's/^\s*\*?\s*//; s/\s*(Ad-Hoc|Infra).*//' <<< "$network")
echo "connecting to ${network}..."

# Ref: https://unix.stackexchange.com/questions/420640/unable-to-connect-to-any-wifi-with-networkmanager-due-to-error-secrets-were-req/444433
#   try disable connection
nmcli connection up "$network"
#nmcli -a device wifi connect "$network" || nmcli connection up "$network"

## Ref: https://unix.stackexchange.com/questions/420640/unable-to-connect-to-any-wifi-with-networkmanager-due-to-error-secrets-were-req/444433
##  remove all connections for `Error: Connection activation failed: (7) Secrets were required, but not provided.` on nucli
#nmcli --fields UUID,TIMESTAMP-REAL con show | grep never | awk '{print $1}' \
#  | while read -r line; do nmcli con delete uuid "$line"; done
#
#nmcli -a device wifi connect "$network"
