# user is root.
ubuntu config --default-user root

# download a bootstrap
tar -zxvf /mnt/c/Users/ktigr/Downloads/WSL/archlinux-bootstrap-version.tar.gz

echo "# This file was automatically generated by WSL. To stop automatic generation of this file, remove this line." > ~/root.x86_64/etc/resolv.conf




