#!/usr/bin/env bash

set -Ce

URLs=$XDG_CONFIG_HOME/qutebrowser/bookmarks/urls
type "$1" >/dev/null 2>&1 && BROWSER="$1" || BROWSER=xdg-open

fzf < "$URLs" | cut -d' ' -f1 | while read -r URL
do
  "$BROWSER" "$URL" >/dev/null 2>&1
done
