# From: rc/dein.vim

#[ Indent ]
#[[plugins]]
#repo = 'Yggdroot/indentLine'
## Note: Causes a bulk of problems
#on_event = 'BufRead'
#hook_add = 'runtime add/indentLine.vim'

#[ Resonance ]
[[plugins]]
repo = 'itchyny/vim-cursorword'
# Underlines appear on every word under the cursor.
on_event = 'CursorMoved'
# Error: no such Event CursorWord0
#hook_add = 'let g:cursorword_highlight = 0'
hook_post_source = 'runtime add/cursorword.vim'

#[[plugins]]
#repo = 't9md/vim-quickhl'
## Note: buggy
#on_map = {nx = '<Plug>(quickhl-'}
#on_map = {nx = '<Plug>(operator-quickhl-'}
#hook_add = 'runtime add/quickhl.vim'

#[[plugins]]
#repo = 'junegunn/rainbow_parentheses.vim'
#on_event = 'BufWinEnter'
#hook_post_source = 'runtime add/rainbow_parentheses.vim'

#[[plugins]]
#repo = 'luochen1990/rainbow'
## CAUTION: source add/rainbow.vim AFTER :colorscheme.
#on_event = 'BufReadPre'

#[[plugins]]
#repo = 'wellle/context.vim'
## shows function/if/while and so on in a preview
## Note: too slow
#on_event = ['BufWinEnter']
#hook_source = 'runtime source/context.vim'
#[[plugins]]
#repo = 'junegunn/limelight.vim'
#on_cmd = 'Limelight'
#hook_add = 'runtime add/limelight.vim'

#[ Icons ]
[[plugins]]
repo = 'ryanoasis/vim-devicons'
on_event = 'BufRead'
hook_post_source = 'runtime add/devicons.vim'

#[ Statusline ]
#[[plugins]]
#repo = 'liuchengxu/eleline.vim'
#on_event = 'VimEnter'
#hook_source = 'runtime source/eleline.vim'

[[plugins]] # has extentions
repo = 'vim-airline/vim-airline'
on_event = 'VimEnter'
# Uncompatible with nyaovim?
# Better to be sourced earlier than colorschemes
hook_source = 'runtime source/airline.vim'
hook_post_source = 'set noshowmode noruler'
hook_done_update = '''
exe 'e' g:dein_github_dir .'/vim-airline/vim-airline/autoload/airline/extensions.vim'
%s/CocC/Cc
write
'''

[[plugins]]
repo = 'vim-airline/vim-airline-themes'
# Note: original only has 'dark'
depends = 'vim-airline'
on_event = 'VimEnter'

#[[plugins]]
#repo = 'hardcoreplayers/spaceline.vim'
## Not good w/ neovim-qt
#on_event = 'BufRead'
#hook_source = 'runtime rc/spaceline.vim'

[[plugins]]
repo = 'mg979/vim-xtabline'
on_event = ['VimEnter']
hook_add = 'runtime add/xtabline.vim'
hook_source = 'runtime source/xtabline.vim'
hook_done_update = '''
exe 'e' g:dein_github_dir .'/mg979/vim-xtabline/autoload/xtabline/maps.vim'
g/<Plug>(XT-Select-Buffer)/s/<unique>//e
write
'''

#[[plugins]] # has extentions
#repo = 'itchyny/lightline.vim'
#on_event = 'BufAdd'
#hook_post_source = 'runtime add/lightline.vim'

#[[plugins]]
#repo = 'albertomontesg/lightline-asyncrun'
## provides an indicator to tell async jobs running in background.
#on_source = 'vim-airline'
#depends = 'asyncrun.vim'
#hook_post_source = 'runtime add/lightline-asyncrun.vim'
#[[plugins]]
#repo = 'taohexxx/lightline-buffer'
#on_source = 'lightline.vim'
#hook_post_source = 'runtime add/lightline-buffer.vim'

#[ Colorscheme ]
#[[plugins]]
#repo = 'KeitaNakamura/neodark.vim'
#on_event = 'VimEnter'
#hook_source = 'runtime add/neodark.vim'

#[[plugins]]
#repo = 'flrnprz/candid.vim'
## Looks like dracula scheme.
#on_event = 'VimEnter'
#hook_post_source = 'runtime add/candid.vim'

#[ Colorscheme.Collection ]
[[plugins]]
repo = 'flazz/vim-colorschemes'
# Note: not include airline/lightline's
on_event = 'VimEnter'
hook_post_source = 'runtime post/colorschemes.vim'
# Note: no use to ':au Colorscheme' at start even in /source
#hook_source      = 'runtime source/colorschemes.vim'

[[plugins]]
repo = 'rhysd/try-colorscheme.vim'
# try colorscheme via URL/Repo
on_func =  ['try_colorscheme#try']
hook_add = 'runtime add/try-colorscheme.vim'

#[ Colorscheme.Edit ]
[[plugins]]
repo = 'cocopon/inspecthi.vim'
# Generates a beautiful color swatch from the current buffer
on_cmd = ['Inspecthi']
hook_add = 'runtime add/inspecthi.vim'
hook_done_update = '''
exe 'e' g:dein_github_dir .'/cocopon/inspecthi.vim/plugin/inspecthi.vim'
%s/\<Inspecthi\>/ColoLinks
write
'''

#[[plugins]]
#repo = 'cocopon/colorswatch.vim'
## Inspects a link structure of highlighting groups
#on_cmd = 'ColorSwatchGenerate'
#hook_add = 'runtime add/colorswatch.vim'

#[[plugins]]
#repo = 'rbtnn/vim-coloredit'
## no support for neovim
#if = '!has("nvim")'
#on_cmd =  ['ColorEdit']

#[[plugins]]
#repo = 'cocopon/pgmnt.vim'
## Template engine for colorschemes, in pure Vim script
## e.g., if g:colors_name ==# 'iceberg' | call pgmnt#foo#bar('foobar', 'foofoo') ...
#on_event = 'VimEnter'
#hook_post_source = 'runtime add/pgmnt.vim'

#[[plugins]]
#repo = 'norcalli/nvim-terminal.lua'
#on_cmd = "lua require 'terminal'.setup"
#hook_add = 'runtime add/terminal.lua.vim'

#[[plugins]]
#repo = 'norcalli/nvim-colorizer.lua'
##on_cmd = 'ColorizerAttachToBuffer'
#on_cmd = "lua require'colorizer'.setup()"
#hook_add = 'runtime add/colorizer.lua.vim'
