# From: rc/dein.vim

#[ Easy Motion ]
#[[plugins]] # has extentions
#repo = 'kaile256/vim-easymotion'
##repo = 'easymotion/vim-easymotion'
#on_map = {nox = '<Plug>(easymotion-'}
#hook_add = 'runtime add/easymotion.vim'
#hook_post_source = 'runtime post/easymotion.vim'
#hook_done_update = '''
#"exe 'e' g:dein_github_dir .'/easymotion/vim-easymotion/autoload/EasyMotion.vim
#exe 'e' g:dein_github_dir .'/kaile256/vim-easymotion/autoload/EasyMotion.vim
#g/\Vlen(group_values) == 1/norm! A || (g:EasyMotion_always_jump_first == 1)
#write
#'''

#[ Extensions ]
#[[plugins]]
#repo = 'haya14busa/vim-easyoperator-phrase'
#on_map = '<plug>(easyoperator-'
#hook_add = 'runtime add/easyoperator.vim'
#[[plugins]]
#repo = 'haya14busa/incsearch.vim'
#on_event = 'ColorScheme'
#hook_post_source = 'runtime add/incsearch.vim'
#[[plugins]]
#repo = 'haya14busa/incsearch-easymotion.vim'
#on_event = 'ColorScheme'
#hook_post_source = 'runtime add/incsearch-easymotion.vim'
#[[plugins]]
#repo = 'haya14busa/incsearch-fuzzy.vim'
#on_event = 'ColorScheme'
#hook_post_source = 'runtime add/incsearch-fuzzy.vim'

#[ Sort of ]
[[plugins]]
repo = 'kaile256/vim-sneak'
#repo = 'justinmk/vim-sneak'
# Note: just for comparison to easymotion
on_map = {nox = '<Plug>Sneak_'}
hook_add = 'runtime add/sneak.vim'
hook_post_source = 'runtime post/sneak.vim'
#hook_done_update = '''
#exe 'e'. g:dein_github_dir .'/justinmk/vim-sneak/plugin/sneak.vim'
#g/g:sneak#opt.prompt/d_
#g/<Plug>Sneak_s/norm! "_dap
#g/<Plug>Sneak_S/norm! "_dap
#write
#'''
#[[plugins]]
#repo = 'unblevable/quick-scope'
#on_map = {nox = '<Plug>(QuickScope'}
#hook_add = 'runtime add/quick-scope.vim'
#[[plugins]]
#repo = 'tbo/notion'
## Note: written in typescript & javascript
## no highlight, so confising.
#on_cmd = 'NotionJump'
#hook_add = 'runtime add/notion.vim'

#[[plugins]]
#repo = 'ripxorip/aerojump.nvim'
## seems buggy.
#on_map = {nox = '<Plug>(Aerojump'}
#hook_add = 'runtime add/aerojump.vim'


