# From: rc/dein.vim

#[ Hex Editor ]
[[plugins]]
repo = 'Shougo/vinarise.vim'
on_cmd =  ['Vinarise']
hook_add = 'runtime add/vinarise.vim'
[[plugins]]
repo = 'rootkiter/vim-hexedit'
on_cmd =  ['Hexedit']
#[[plugins]]
#repo = 'd0c-s4vage/pfp-vim'
#on_cmd = 'Pfp'
#hook_add = 'runtime add/pfp.vim'

#[ SQL ]
[[plugins]]
repo = 'joereynolds/SQHell.vim'
on_cmd = [
'SQHShowDatabases',
'SQHShowTablesForDatabase',
]
hook_add = 'runtime add/SQHell.vim'
hook_source = 'runtime source/SQHell.vim'

#[ Minimap ]
#[[plugins]]
#repo = 'severin-lemaignan/vim-minimap'
#on_cmd = 'Minimap'
#hook_add = 'runtime add/minimap.vim'
## the name, vim-minimap, causes error when jump to this repository.
#hook_done_update = '''
#exe 'e' g:dein_github_dir .'/severin-lemaignan/vim-minimap/autoload/minimap.py'
#g/MINIMAP/s/vim-minimap/[minimap]/e
#write
#'''
#
#[ Template ]
#[[plugins]]
#repo = 'mattn/sonictemplate-vim'
## Note: Use snippet instead
#on_event = 'BufNew'
#hook_post_source = 'runtime add/sonictemplate.vim'

#[[plugins]]
#repo = 'chrisbra/NrrwRgn'
#on_event = 'VimEnter'
#hook_post_source = 'runtime add/NrrwRgn.vim'

#[[plugins]]
#repo = 'AndrewRadev/switch.vim'
## toggle as predefined, such as 'true' & 'false'.
#on_if = '&modifiable'
#hook_post_source = 'runtime add/switch.vim'

#[[plugins]]
#repo = 'xolox/vim-session'
#depend = 'xolox/vim-misc'
#on_cmd = ['SessionOpen', 'SessionSave']
#hook_done_update = '''
#exe 'e' g:dein_github_dir .'xolox/vim-session/plugin/session.vim
#g/command!/g/Session /norm! ndeBP
#g/command!/s/RestartVim/SessionVimRestart
#write
#'''

#[[plugins]]
#repo = 'mtth/scratch.vim'
#on_cmd =  ['Scratch']
#
#[ Plugin ]
[[plugins]]
repo = 'wsdjeg/dein-ui.vim'
on_cmd = 'DeinUpdate'
hook_add = 'runtime add/dein-ui.vim'
[[plugins]]
repo = 'haya14busa/dein-command.vim'
# For `Dein list`
on_cmd = 'Dein'
hook_add = 'runtime add/dein-command.vim'
#[[plugins]]
#repo = 'fszymanski/fzf-gitignore'
#type = 'git'
##on_if = '@% =~# ".gitignore"'
#hook_post_source = 'runtime add/fzf-gitignore.vim'
