# From: rc/dein.vim

[[plugins]]
repo = 'wsdjeg/dein-ui.vim' #{{{
on_cmd = 'DeinUpdate'
hook_add = 'runtime add/dein-ui.vim'
#}}}
[[plugins]]
repo = 'haya14busa/dein-command.vim' #{{{
# For `Dein list`
on_cmd = 'Dein'
hook_add = 'runtime add/dein-command.vim'
#}}}

#[[plugins]]
#repo = 'fszymanski/fzf-gitignore' #{{{
#type = 'git'
##on_if = '@% =~# ".gitignore"'
#hook_post_source = 'runtime add/fzf-gitignore.vim'
##}}}

