# From: rc/dein.vim

# FZF
[[plugins]]
repo = 'junegunn/fzf' #{{{
# Note: :Files in fzf.vim is the same as :FZF.
# Note: Necessary for fzf.vim
#on_source = 'fzf.vim'
[[plugins]]
#repo = 'junegunn/fzf.vim'
repo = 'kaile256/fzf.vim'
on_cmd = 'fzf#vim#'
rev = 'verbose_commands'
hook_add = 'runtime add/fzf.vim'
hook_source = 'runtime source/fzf.vim'
hook_post_source = 'runtime post/fzf.vim'
#}}}

#[[plugins]]
#repo = 'liuchengxu/vim-clap' #{{{
## Note: a fuzzy finder written in 99.7% vimscript.
#on_cmd = 'Clap'
#hook_add = 'runtime add/clap.vim'
##}}}

# Filer
[[plugins]] # has extentions
repo = 'Shougo/defx.nvim' #{{{
if = 'has("python3")'
on_cmd = 'Defx'
hook_add = 'runtime add/defx.vim'
hook_post_source = 'runtime post/defx.vim'
[[plugins]]
repo = 'kristijanhusak/defx-git' #{{{
on_source = 'defx.nvim'
#}}}
#[[plugins]]
#repo = 'kristijanhusak/defx-icons' #{{{
#on_source = 'defx.nvim'
##}}}
#}}} End of Defx
#[[plugins]]
#repo = 'lambdalisue/fila.vim' #{{{
## Note: currently has no docment.
#on_cmd = 'Fila'
#hook_add = 'runtime add/fila.vim'
##}}}
#[[plugins]]
#repo = 'cocopon/vaffle.vim' #{{{
#on_if = 'has("python3")'
#hook_post_source = 'runtime add/vaffle.vim'
##}}}
#[[plugins]]
#repo = 'justinmk/vim-dirvish' #{{{
#on_event = 'BufAdd'
#hook_post_source = 'runtime add/dirvish.vim'
#}}}
## Ranger
#[[plugins]]
#repo = 'Lokaltog/neoranger' #{{{
## Note: only one pane is in use; can't call it a ranger.
#on_event = 'BufRead'
#hook_add = 'runtime add/neoranger.vim'
##}}}
#[[plugins]]
#repo = 'ipod825/vim-netranger' #{{{
## Browser for system/cloud storage
#on_event = 'BufRead'
#hook_post_source = 'runtime add/netranger.vim'
##}}}
#[[plugins]]
#repo = 'rafaqz/ranger.vim' #{{{
### semms only call the external ranger.
#on_event = 'BufRead'
#hook_post_source = 'runtime add/ranger.vim'
##}}}
#[[plugins]]
#repo = 'francoiscabrol/ranger.vim' #{{{
## semms only call the external ranger.
#on_event = 'BufRead'
#hook_post_source = 'runtime add/ranger.vim'
##}}}

# CTags/global
[[plugins]]
repo = 'jsfaint/gen_tags.vim' #{{{
on_event = 'BufLeave'
hook_post_source = 'runtime add/gen_tags.vim'
#}}}
#[[plugins]]
#repo = 'SpaceVim/gtags.vim' #{{{
## Only for SpaceVim? E117: Unknown function: gtags#update
## 1. generate gtags file automatically
## 2. quickfix list support
## 3. A fuzzy finder souces for some plugins:
##          denite, unite, fzf, leader-f, fzy
#on_event = 'BufRead'
#hook_post_source = 'runtime add/gtags.vim'
##}}}
[[plugins]]
repo = 'majutsushi/tagbar' #{{{
on_cmd = 'TagbarToggle'
hook_add = 'runtime add/tagbar.vim'
#}}}
#[[plugins]]
#repo = 'liuchengxu/vista.vim' #{{{
## Note: supports lsp via such plugins as coc, vim-lsp.
## Note: sort tags on the role, like function, struct, variable and so on.
#on_cmd = 'Vista'
#hook_add = 'runtime add/vista.vim'
##}}}

# Enhance; Marks
#[[plugins]]
#repo = 'MattesGroeger/vim-bookmarks' #{{{
## ???
#on_cmd = ['BookmarkAnnotate', 'BookmarkShowAll', 'BookmarkNext', 'BookmarkPrev']
#hook_add = 'runtime add/bookmarks.vim'
##}}}
#[[plugins]]
#repo = 'jacquesbh/vim-showmarks'{{{
#on_map = ['m','`',"'",'<space>']
#hook_add = 'runtime add/showmarks.vim'
#}}}
