# From: rc/dein.vim

[[plugins]]
repo = 'Konfekt/FastFold'
# lazy load inside foleded.
on_event = 'VimEnter'
hook_source = 'runtime source/FastFold.vim'
#[[plugins]]
#repo = 'SwintonStreet/HighlightFoldLevelVimScript'
# Seems not to work. May not get along with foldCC.
#hook_add = 'runtime add/HighlightFoldLevel.vim'
#[[plugins]]
#repo = 'anschnapp/move-less'
#on_event = 'BufRead'
#hook_add = 'runtime add/move-less.vim'
#[[plugins]]
#repo = 'tmhedberg/SimpylFold'
#on_ft = 'python'
#hook_post_source = 'runtime add/SimpylFold.vim'
#[[[Fold Text]]]
#[[plugins]]
#repo = 'LeafCage/foldCC'
#on_event = 'BufWinEnter'
#hook_source = 'runtime source/foldCC.vim'
#[[plugins]]
#repo = 'doy/vim-foldtext'
## no use
#on_event = ['BufRead']
#[[plugins]]
#repo = 'jrudess/vim-foldtext'
## lack of info about lnum/foldlevel etc.
#on_event = ['BufRead']
#

