# From: rc/dein.vim

[[plugins]]
repo = 'Konfekt/FastFold'
# lazy load inside foleded.
on_event = 'VimEnter'
hook_source = 'runtime source/FastFold.vim'
#[[plugins]]
#repo = 'SwintonStreet/HighlightFoldLevelVimScript'
# Seems not to work. May not get along with foldCC.
#hook_add = 'runtime add/HighlightFoldLevel.vim'
#[[plugins]]
#repo = 'anschnapp/move-less'
#on_event = 'BufRead'
#hook_add = 'runtime add/move-less.vim'

#[[plugins]]
#repo = 'pseewald/vim-anyfold'
## too many extra fold
#on_ft = ['python', 'yaml']
#hook_source = 'runtime source/anyfold.vim'
#
#[ Fold Text ]
#[[plugins]]
#repo = 'LeafCage/foldCC'
#on_event = 'BufWinEnter'
#hook_source = 'runtime source/foldCC.vim'
#[[plugins]]
#repo = 'doy/vim-foldtext'
## no use
#on_event = ['BufRead']
#[[plugins]]
#repo = 'jrudess/vim-foldtext'
## lack of info about lnum/foldlevel etc.
#on_event = ['BufRead']
#

#[ FileType ]
#[[plugins]]
#repo = 'matze/vim-ini-fold'
#rev = 'c5ba417dd57942e6463e7079f0650ae0722d72c9'
##repo = 'kaile256/vim-ini-fold'
## PR-Merged: matze/vim-ini-fold/pull/1
## PR: matze/vim-ini-fold/pull/2
#on_ft = ['cfg', 'config', 'desktop', 'dosini', 'gitconfig', 'toml']
#hook_source = 'runtime source/ini-fold.vim'
#
#[[plugins]]
#repo = 'pedrohdz/vim-yaml-folds'
#on_ft = ['yaml', 'raml', 'sls', 'eyaml']
#[[plugins]]
#repo = 'tmhedberg/SimpylFold'
## no fold on trailing blanklines
#on_ft = ['python']
#
#[[plugins]]
#repo = 'arutz12/pyfolding'
## An excerpt from python-mode/python-mode, only for fold
#on_ft = ['python']
#
#[ Indent ]
#[[plugins]]
#repo = 'xi/vim-indent-folding'
## Note: includes a fdt-function
#on_ft = ['python', 'yaml']
#
#[[plugins]]
#repo = 'tomtom/indentfolds_vim'
## Note: complicated
#on_ft = ['python', 'yaml']
#
#[[plugins]]
#repo = 'rdpate/vim-fold-indent-block'
## Note: lack of detection
#on_ft = ['python', 'yaml']
#
