# From: rc/dein.vim
# Ref: syntax.toml

#[ Multiple FileType ]
[[plugins]]
repo = 'editorconfig/editorconfig-vim'
# Note: coc-prettier doesn't use editorconfig if prettier is either unavailable.
# Note: vim-prettier is unnecessary, though it also covers editorconfig.
on_event = 'BufWinEnter'
hook_source = 'runtime source/editorconfig.vim'

#[[plugins]]
#repo = 'prettier/vim-prettier'
## Note: also read .editorconfig
#on_event = 'BufWinEnter'
#hook_add = 'runtime add/prettier.vim'

#[[plugins]]
#repo = 'tpope/vim-sleuth'
## Note: Sleuth means a detective.
## Enough with coc-prettier?
## Automatically adjusts 'shiftwidth' and 'expandtab'
#on_event = ['BufNewFile','BufRead']
#hook_add = 'runtime add/sleuth.vim'

#[[plugins]]
#repo = 'Shougo/context_filetype.vim'
#on_ft = ['vimwiki','markdown','html','php','neosnippet','snippets']

#[[plugins]]
#repo = 'vim-syntastic/syntastic'
#on_ft = ['toml']
#hook_post_source = 'runtime add/syntastic.vim'

#[ Rust ]
[[plugins]]
repo = 'martskins/vim-cargo-search'
if = '&ft ==# "rust"'
on_cmd =  ['CargoSearch']

#[[plugins]]
#repo = 'rust-lang/rust.vim'
#on_ft = 'rust'

#[[plugins]]
#repo = 'rhysd/rust-doc.vim'
#on_cmd = 'RustDoc'
#hook_source = 'runtime add/rust-doc.vim'

#[ Python ]
[[plugins]]
repo = 'plytophogy/vim-virtualenv'
# supports pip-packages, independently installed in shell, to work on vim
on_ft = 'python'
#[[plugins]]
#repo = 'python-rope/ropevim'
#on_ft = ['python']
#
#[[plugins]]
#repo = 'python-mode/python-mode'
#on_ft = 'python'
#hook_post_update = '!git submodule update --init --recursive'
#hook_source = 'runtime source/python-mode.vim'
#
#[[plugins]]
#repo = 'tweekmonster/braceless.vim'
## To: fold up to syntax of python.
## not work so good
#on_ft = ['python']
#on_cmd =  ['BracelessEnable']
#hook_add = 'runtime add/braceless.vim'
#
#[ Python.Jupyter ]
[[plugins]]
repo = 'goerz/jupytext.vim'
on_ft = ['ipynb']
hook_source = 'runtime source/jupytext.vim'

[[plugins]]
repo = 'szymonmaszke/vimpyter'
on_ft = ['ipynb']
hook_source = 'runtime source/vimpyter.vim'


#[ Document ]
[[plugins]]
repo = 'rafaqz/citation.vim'
on_ft = ['zotero', 'pybtex']
hook_source = 'runtime source/citation.vim'

[[plugins]]
repo = 'Konfekt/vim-office'
# no need any config.
on_ft = ['pdf', 'doc', 'docx', 'els', 'xlsx', 'ppt', 'pptx', 'odt', 'epub']

[[plugins]]
repo = 'itchyny/vim-pdf'
on_ft = ['pdf']

#[ Config ]
[[plugins]]
repo = 'tpope/vim-jdaddy'
on_ft = 'json'

[[plugins]]
repo = 'danishprakash/vim-docker'
on_cmd =  ['DockerDocBrowser', 'DockerHubBrowser',]

#[ Quickfix ]
[[plugins]]
repo = 'lambdalisue/qfloc.vim'
# provies some local keymaps
on_ft = ['qf', 'loc']
hook_source = 'runtime source/qfloc.vim'

#[ Android ]
[[plugins]]
repo = 'hsanson/vim-android'
on_ft = ['java', 'kotlin', 'xml']

[[plugins]]
repo = 'AndroidMarv/android-dev.vim'
on_ft = ['java', 'kotlin', 'xml']

