# From: rc/dein.vim

#[[plugins]]
#repo = 'iamcco/sran.nvim'
#if = 'has("nvim") || version >= 801'
#hook_post_update = 'call sran#util#install()'
#type = 'git'
#on_event = 'BufRead'
#hook_add = 'runtime add/sran.vim'
#[[plugins]]
#repo = 'iamcco/git-p.nvim'
#type = 'git'
#on_event = 'BufWinEnter'
#hook_add = 'runtime add/git-p.vim'

[[plugins]]
repo = 'cohama/agit.vim' #{{{
# Log viewer
on_cmd = 'Agit'
hook_add = 'runtime add/agit.vim'
#}}}

#[[plugins]]
#repo = 'airblade/vim-gitgutter' #{{{
## enough only with coc.nvim & fugitive.vim?
#type = 'git'
#on_event = 'BufRead'
#hook_post_source = 'runtime add/gitgutter.vim'
##}}}

#[[plugins]]
#repo = 'lambdalisue/gina.vim' #{{{
#on_event = ['BufWritePost']
#hook_post_source = 'runtime add/gina.vim'
##}}}

