# From: rc/dein.vim

#[[plugins]]
#repo = 'reedes/vim-pencil'
## auto format upon &tw
#on_func = ['pencil#']
#on_cmd  = ['Pencil']
#hook_add = 'runtime add/pencil.vim'
#
#[ Snippets; Engine ]
[[plugins]]
repo = 'Shougo/neosnippet.vim'
# set the filetype in augroups.vim
# it disturbs on 'n', of cource
#on_map = {nov = 'neosnippet#'}
on_func =  ['neosnippet#']
on_path = ['*.snip', '*.snippets']
hook_add = 'runtime add/neosnippet.vim'
hook_source = 'runtime once/smaps.vim'

#[[plugins]]
#repo = 'SirVer/ultisnips'
## Note: it override <TAB>
#on_event = ['InsertEnter']
#hook_post_source = 'runtime add/ultisnips.vim'
#hook_source = 'runtime once/smaps.vim'

#[ Snippets; Contents ]
[[plugins]]
repo = 'honza/vim-snippets'
on_source = ['neosnippet.vim']

#[[plugins]]
#repo = 'Shougo/neosnippet-snippets'
## minimal
#on_event = ['InsertEnter']
#[[plugins]]
#repo = 'garbas/vim-snipmate'
#on_event = ['InsertEnter']

#[ Thesaurus ]
[[plugins]]
repo = 'Ron89/thesaurus_query.vim'
on_cmd = 'Thesaurus'
hook_add = 'runtime add/thesaurus_query.vim'

#[ Unicode ]
[[plugins]]
repo = 'chrisbra/unicode.vim'
# Note: on_map of unicode.vim is useless; maybe because they are imap.
on_map = {i = ['<Plug>(UnicodeComplete)', '<Plug>(DigraphComplete)']}
hook_post_source = 'runtime add/unicode.vim'
#[[plugins]]
#repo = 'arthurxavierx/vim-unicoder'
#on_map = {i = '<Plug>(unicoder-'}

#[ Spell ]
#[[plugins]]
#repo = 'kamykn/spelunker.vim'
#on_map = {ni = '<Plug>(spelunker-'}
#hook_source = 'runtime source/spelunker.vim'
#[[plugins]]
#repo = 'rhysd/vim-grammarous'
## Grammer Check
## Note: Too heavy to download pre-requested files
#on_cmd = 'GrammarousCheck'
#hook_add = 'runtime add/grammarous.vim'
[[plugins]]
repo = 'shinglyu/vim-codespell'
# only supports python?
on_cmd = 'Codespell'
hook_add = 'runtime add/codespell.vim'
#[[plugins]]
#repo = 'tweekmonster/dyslexic.vim'
## Spell checker according to <cword>.
#on_cmd = 'Dyslexic'
#hook_add = 'runtime dyslexic.vimrc'

#[ CapsLock ]
#[[plugins]]
#repo = 'tpope/vim-capslock'
## Doesn't Work
#on_event = ['InsertEnter', 'CmdlineEnter']
#hook_post_source = 'runtime add/capslock.vim'
#[[plugins]]
#repo = 'mattn/vim-switch-esc-capslock'
#### For Windows?
#on_event = ['InsertEnter', 'CmdlineEnter']
#hook_post_source = 'runtime add/switch-esc-capslock.vim'

#[ Completion ]
#[[plugins]]
#repo = 'Shougo/deoplete.nvim'
## good with eskk.vim
#on_if = 'has("python3")'
#on_event = ['InsertCharPre', 'InsertEnter']
#hook_post_source = 'runtime add/deoplete.vim'
##[[plugins]]
##repo = 'SevereOverfl0w/deoplete-github'
##on_ft = ['gitcommit']
##[[plugins]]
##repo = 'wellle/tmux-complete.vim'
##on_ft = 'tmux'
#[[plugins]]
#repo = 'deoplete-plugins/deoplete-zsh'
#on_ft = 'zsh'
#[[plugins]]
#repo = 'ponko2/deoplete-fish'
#on_ft = 'fish'
#[[plugins]]
#repo = 'tenfyzhong/CompleteParameter.vim'
## Enough w/ lsp and snippets?
#on_map = '<Plug>(complete_parameter#'
#hook_add = 'runtime add/CompleteParameter.vim'
#
#[ Spell ]
[[plugins]]
repo = 'reedes/vim-lexical'
on_func =  ['lexical#init']
hook_source = 'runtime source/lexical.vim'
