# From: rc/dein.vim

#[[[Preview]]]
#[[plugins]]
#repo = 'previm/previm'
#on_ft = 'markdown'
#hook_source = 'runtime source/previm.vim'
#hook_done_update = '''
#exe 'e' g:dein_github_dir .'/previm/previm/plugin/previm.vim'
#g/FileType *{md,mkd,markdown,rst,textile,asciidoc}*/norm! oau BufEnter *.{md,mkd,markdown,mdown,mkdn,mdwn}/e
#write
#'''

#[[plugins]]
#repo = 'reroche/vim-markdown-preview'
## several requirements
#on_ft = 'markdown'

[[plugins]]
repo = 'iamcco/markdown-preview.nvim'
# Ref: iamcco/markdown.css
on_ft = 'markdown'
build = 'cd app & yarn install'
hook_source = 'runtime source/markdown-preview.vim'

[[plugins]]
repo = 'euclio/vim-markdown-composer'
on_ft = 'markdown'
build = 'cargo build --release'
hook_done_update = '''
exe 'e' g:dein_github_dir .'/euclio/vim-markdown-composer/after/ftplugin/markdown/composer.vim'
g/command!/s/Composer/Md/
write
'''
hook_source = 'runtime source/markdown-composer.vim'

#[[plugins]]
#repo = 'suan/vim-instant-markdown'
#on_ft = 'markdown'
#hook_source = 'runtime add/instant-markdown.vim'

#[[[Go]]]
[[plugins]]
repo = 'po3rin/vim-gofmtmd'
if = "&ft ==# 'markdown'"
on_cmd =  ['GoFmtMd']
#on_ft = ['markdown']
hook_source = 'runtime source/gofmtmd.vim'

#[[[Syntax]]]
[[plugins]]
repo = 'rhysd/vim-gfm-syntax'
on_ft = ['markdown']

#[[plugins]]
#repo = 'gabrielelana/vim-markdown'
## includes fold on markdown
## too heavy to `:e any.md`
#on_ft = ['markdown']
#hook_source = 'runtime source/gabrielelana-markdown.vim'

#[[plugins]]
#repo = 'plasticboy/vim-markdown'
#on_ft = 'markdown'
#hook_source = 'runtime source/plasticboy-markdown.vim'

#[[plugins]]
#repo = 'joker1007/vim-markdown-quote-syntax'
## Note: seems no use
#on_ft = ['markdown']
#hook_source = 'runtime source/markdown-quote-syntax.vim'
#

#[[[Fold]]]
#[[plugins]]
#repo = 'Jagua/vim-markdown_fold'
## no use
#on_ft = ['markdown']
#[[plugins]]
#repo = 'GuilloteauQ/vim-mdfold'
## no use
#on_ft = ['markdown']

