# From: rc/dein.toml

# Note: Don't locate the plugins under $MYVIMRC for dein's hook.
[[plugins]]
repo = 'kaile256/vim-among_HML' #{{{
on_func = 'among_HML#'
hook_add = 'runtime add/among_HML.vim'
#}}}

[[plugins]]
repo = 'kaile256/vim-sensible_K' #{{{
# Note: the plugin defines no map/cmd, only using augroup.
on_event = 'VimEnter'
hook_add = 'runtime add/sensible_K.vim'
#}}}

#[[plugins]]
#repo = 'kaile256/vim-window-picker' #{{{
#on_cmd = ['WindowPKreduce', 'WindowPKpick', 'WindowPKoly', 'WindowPKfloating', 'WindowPKcopy', 'WindowPKtabGive']
#hook_add = 'runtime add/window-picker.vim'
##}}}

[[plugins]]
repo = 'kaile256/vim-keymaps-dealer' #{{{
# Note: must load the plugin before mapped, cannot lazy-load.
on_event = 'VimEnter'
hook_source = 'runtime source/keymaps-dealer.vim'
# Note: autoload-functions in vimrc must be called after loading the autoload/.
hook_post_source = 'runtime post/keymaps-dealer.vim'
#}}}

[[plugins]]
repo = 'kaile256/vim-lines-in-functions' #{{{
on_cmd = ['LinesFunctions']
#}}}

#[[plugins]]
#repo = 'kaile256/vim-fvf' #{{{
#on_event = 'VimEnter'
#rev = 'refactoring'
##rev = 'verbose_commands'
#hook_add = 'runtime add/fzf.vim'
#hook_source = 'runtime source/fzf.vim'
#hook_post_source = 'runtime post/fzf.vim'
#}}}

[[plugins]]
repo = 'kaile256/vim-spell-temporary' #{{{
on_map = {nix = '<Plug>(spellTMP-suggestion'}
hook_add = 'runtime add/spell-temporary.vim'
#}}}

[[plugins]]
repo = 'kaile256/vim-findpath' #{{{
on_cmd = 'FindPath'
#hook_add = 'runtime add/findpath.vim'
#}}}

[[plugins]]
repo = 'kaile256/vim-help-toc' #{{{
on_ft = ['help', 'man']
hook_source = 'runtime source/help-toc.vim'
#}}}

[[plugins]]
repo = 'kaile256/vim-foldpeek' #{{{
on_event = ['BufWinEnter']
hook_source = 'runtime source/foldpeek.vim'
#}}}
