# From: dein.toml

# Note: You'd better not place the plugins under $MYVIMRC to use dein's hook

[[plugins]]
repo = 'kaile256/vim-among_HML'
on_cmd = 'among_HML#'
hook_add = 'runtime add/among_HML.vim'

[[plugins]]
repo = 'kaile256/vim-sensible_K'
# Note: the plugin defines no map/cmd, only using augroup.
on_event = 'VimEnter'
hook_add = 'runtime add/sensible_K.vim'

[[plugins]]
repo = 'kaile256/vim-window-picker'
depends = ['fzf.vim', 'vim-fugitive', 'coc.nvim']
#on_cmd = 'winpick#'
on_event = 'VimEnter'
hook_add = 'runtime add/winpick.vim'
hook_post_source = 'runtime post/winpick.vim'

[[plugins]]
repo = 'kaile256/vim-foldcolors'
on_event = 'BufWinEnter'
hook_source = 'runtime source/foldcolors.vim'
