# From: rc/dein.toml

# Note: Don't locate the plugins under $MYVIMRC for dein's hook.

[[plugins]]
repo = 'kaile256/vim-among_HML'
on_cmd = 'among_HML#'
hook_add = 'runtime add/among_HML.vim'

[[plugins]]
repo = 'kaile256/vim-sensible_K'
# Note: the plugin defines no map/cmd, only using augroup.
on_event = 'VimEnter'
hook_add = 'runtime add/sensible_K.vim'

[[plugins]]
repo = 'kaile256/vim-panes-farmer'
on_event = 'VimEnter'
hook_add = 'runtime add/panes-farmer.vim'

[[plugins]]
repo = 'kaile256/vim-keymaps-dealer'
# Note: must load the plugin before mapped, cannot lazy-load.
on_event = 'VimEnter'
hook_add = 'runtime add/keymaps-dealer.vim'
# Note: autoload-functions in vimrc must be called after loading the autoload/.
hook_post_source = 'runtime post/keymaps-dealer.vim'

[[plugins]]
repo = 'kaile256/vim-foldcolors'
on_event = ['BufNewFile', 'BufRead']
hook_source = 'runtime source/foldcolors.vim'
