# From: rc/dein.vim

#[ Sudo ]
[[plugins]]
repo = 'lambdalisue/suda.vim'
if = 'executable("sudo")'
on_event = 'CmdlineEnter'
on_func = 'suda#'
hook_add = 'runtime add/suda.vim'
#[[plugins]]
#repo = 'chrisbra/SudoEdit.vim'
## Useless w/ neovim
#on_cmd = 'Sudo'
#hook_post_source = 'runtime add/SudoEdit.vim'

#[ REPL ]
#[[plugins]]
#repo = 'metakirby5/codi.vim'
## REPL while coding one char by one, in the same buffer.
#on_ft = ['python', 'javascript', 'coffeescript', 'haskell', 'ruby', 'OCaml', 'R', 'clojure', 'php', 'lua', 'cpp', 'julia', 'elm', 'elixir', 'typescript', 'mathjs']
#hook_post_source = 'runtime add/codi.vim'
#[[plugins]]
#repo = 'sillybun/vim-repl'
## Only for python?
#on_cmd = 'REPL'
#hook_add = 'runtime add/repl.vim'

#[ Async Processor ]
[[plugins]]
repo = 'Shougo/vimproc.vim'
on_func = ['vimproc#']
# run vim-plugins asynchronously, like openbrowser, quickrun.
build = 'make'

[[plugins]]
repo = 'thinca/vim-quickrun'
on_cmd = 'QuickRun'
on_map = '<Plug>(quickrun'
hook_add = 'runtime add/quickrun.vim'
hook_source = 'runtime source/quickrun.vim'
[[plugins]]
repo = 'heavenshell/vim-quickrun-hook-unittest'
# Note: g:quickrun_config is loaded on each :QuickRun
if = "index(['php', 'python', 'ruby', 'go', 'javascript'], &ft) >= 0"
on_cmd = 'QuickRun'
on_map = '<Plug>(quickrun'
hook_source = 'runtime source/quickrun-unittest.vim'
[[plugins]]
repo = 'skywind3000/asyncrun.vim'
# Only supports external shell to qf.
on_cmd = 'AsyncRun'
hook_add = 'runtime add/asyncrun.vim'

[[plugins]]
repo = 'skywind3000/asynctasks.vim'
depend = ['asyncrun.vim']
on_cmd = ['AsyncTask']

#[ Shell; Wrapper ]
#[[plugins]]
#repo = 'kassio/neoterm'
## also has async-run feature.
#on_cmd = ['T']
#hook_add = 'runtime add/neoterm.vim'
#[[plugins]]
#repo = 'Shougo/deol.nvim'
#on_event = 'VimEnter'
#hook_post_source = 'runtime add/deol.vim'

