# From: rc/dein.vim

[[plugins]]
repo = 'mattn/vim-findroot' #{{{
on_cmd = 'FindRoot'
hook_add = 'runtime add/findroot.vim'
# To enable to :FindRoot w/ other commands through <bar>.
hook_done_update = '''
exe 'e' g:dein_github_dir .'/mattn/vim-findroot/plugin/findroot.vim'
g/command!/norm! Ea -bar
g/s:findroot(/s/1/0
write
'''
#}}}

[[plugins]]
repo = 'kaile256/vim-submode' #{{{
#repo = 'kana/vim-submode'
# make another mode!
on_func = 'submode#'
hook_add = 'runtime add/submode.vim'
#hook_post_source = 'runtime post/submode.vim'
#hook_done_update = '''
#exe 'e' g:dein_github_dir .'/kana/vim-submode/autoload/submode.vim'
#%s/submode-/sbm-/g
#write
##}}}

#[[plugins]]
#repo = 'thinca/vim-ref' #{{{
#on_event = 'BufRead'
#hook_add = 'runtime rc/ref.vim'
##}}}

# Hex Editor
[[plugins]]
repo = 'd0c-s4vage/pfp-vim' #{{{
on_cmd = 'Pfp'
hook_add = 'runtime add/pfp.vim'
#}}}

# Floating Window
#[[plugins]]
#repo = 'ncm2/float-preview.nvim' #{{{
#on_source = ['denite.nvim', 'deolplete.nvim', 'coc.nvim']
#hook_source = 'runtime source/float-preview.vim'
#hook_done_update = '''
#exe 'e' g:dein_github_dir .'/ncm2/float-preview.nvim/plugin/float_preview.vim'
#g/au/Complete/norm! i"
#g/au/InsertLeave/norm! i"
#write
#'''
##}}}
#[[plugins]]
#repo = 'voldikss/vim-floaterm' #{{{
#on_cmd = 'FloatermToggle'
#on_map = '<Plug>(floaterm-'
#hook_add = 'runtime add/floaterm.vim'
##}}}

[[plugins]]
repo = 'severin-lemaignan/vim-minimap' #{{{
on_cmd = 'Minimap'
hook_add = 'runtime add/minimap.vim'
# the name, vim-minimap, causes error when jump to this repository.
hook_done_update = '''
exe 'e' g:dein_github_dir .'/severin-lemaignan/vim-minimap/autoload/minimap.py'
g/MINIMAP/s/vim-minimap/[minimap]/e
write
'''
#}}}

# Template
#[[plugins]]
#repo = 'mattn/sonictemplate-vim' #{{{
#on_event = 'BufNew'
#hook_post_source = 'runtime add/sonictemplate.vim'
#}}}

[[plugins]]
repo = 'infokiller/vim-errorlist' #{{{
on_cmd = ['errorlist#Navigate']
on_event = ['BufRead']
hook_source = 'runtime source/errorlist.vim'
#}}}
# Checker
#[[plugins]]
#repo = 'haya14busa/vim-stacktrace' #{{{
## Note: a lot of unknown_functions
#build = 'make'
#on_cmd = ['CStacktraceFromhist', 'LStacktraceFromhist']
#hook_add = 'runtime add/stacktrace.vim'
##}}}
#[[plugins]]
#repo = 'lacygoill/vim-stacktrace' #{{{
## WIP: no use because of the lack of autoload-functions except main()
#on_cmd = 'WTF'
#hook_post_source = 'runtime add/stacktrace.vim'
##}}}

#[[plugins]]
#repo = 'chrisbra/NrrwRgn' #{{{
#on_event = 'VimEnter'
#hook_post_source = 'runtime add/NrrwRgn.vim'
##}}}
#[[plugins]]
#repo = 'AndrewRadev/switch.vim' #{{{
## toggle as predefined, such as 'true' & 'false'.
#on_if = '&modifiable'
#hook_post_source = 'runtime add/switch.vim'
#}}}

#[[plugins]]
#repo = 'xolox/vim-session' #{{{
#depend = 'xolox/vim-misc'
#on_cmd = ['SessionOpen', 'SessionSave']
#hook_done_update = '''
#exe 'e' g:dein_github_dir .'xolox/vim-session/plugin/session.vim
#g/command!/g/Session /norm! ndeBP
#g/command!/s/RestartVim/SessionVimRestart
#write
#'''
##}}}
