# From: rc/dein.vim

[[plugins]]
repo = 'mattn/vim-findroot' #{{{
on_cmd = 'FindRoot'
hook_add = 'runtime add/findroot.vim'
# To: enable to :FindRoot w/ other commands through <bar>.
hook_done_update = '''
exe 'e' g:dein_cache_dir .'/repos/github.com/mattn/vim-findroot/plugin/findroot.vim'
g/command!/norm! Ea -bar
g/s:findroot(/s/1/0
write
'''
#}}}

#[[plugins]]
#repo = 'thinca/vim-ref' #{{{
#on_event = 'BufRead'
#hook_add = 'runtime rc/ref.vim'
##}}}

# Hex Editor
[[plugins]]
repo = 'd0c-s4vage/pfp-vim' #{{{
on_cmd = 'Pfp'
hook_add = 'runtime add/pfp.vim'
#}}}

# Floating Window
#[[plugins]]
#repo = 'ncm2/float-preview.nvim' #{{{
#on_source = ['delplete.nvim', 'coc.nvim']
#hook_post_source = 'runtime add/float-preview.vim'
##}}}
#[[plugins]]
#repo = 'voldikss/vim-floaterm' #{{{
#on_cmd = 'FloatermToggle'
#on_map = '<Plug>(floaterm-'
#hook_add = 'runtime add/floaterm.vim'
##}}}

[[plugins]]
repo = 'severin-lemaignan/vim-minimap' #{{{
on_cmd = 'Minimap'
hook_add = 'runtime add/minimap.vim'
# the name, vim-minimap, causes error when jump to this repository.
hook_done_update = '''
exe 'e' g:dein_cache_dir .'/repos/github.com/severin-lemaignan/vim-minimap/autoload/minimap.py'
g/MINIMAP/s/vim-minimap/[minimap]/e
write
'''
#}}}

# Template
#[[plugins]]
#repo = 'mattn/sonictemplate-vim' #{{{
#on_event = 'BufNew'
#hook_post_source = 'runtime add/sonictemplate.vim'
#}}}

# Checker
#[[plugins]]
#repo = 'haya14busa/vim-stacktrace' #{{{
## Error: a lot of unknown_functions
#build = 'make'
#on_event = 'BufRead'
#hook_add = 'runtime add/stacktrace.vim'
##}}}
#[[plugins]]
#repo = 'lacygoill/vim-stacktrace' #{{{
## Note: useless for dein's error, either not in detail
#on_event = 'BufRead'
#hook_post_source = 'runtime add/stacktrace.vim'
##}}}

#[[plugins]]
#repo = 'chrisbra/NrrwRgn' #{{{
#on_event = 'VimEnter'
#hook_post_source = 'runtime add/NrrwRgn.vim'
##}}}
#[[plugins]]
#repo = 'AndrewRadev/switch.vim' #{{{
## toggle as predefined, such as 'true' & 'false'.
#on_if = '&modifiable'
#hook_post_source = 'runtime add/switch.vim'
#}}}

#[[plugins]]
#repo = 'xolox/vim-session' #{{{
#depend = 'xolox/vim-misc'
#on_cmd = ['SessionOpen', 'SessionSave']
#hook_done_update = '''
#exe 'e' g:dein_github_dir .'xolox/vim-session/plugin/session.vim
#g/command!/g/Session /norm! ndeBP
#g/command!/s/RestartVim/SessionVimRestart
#write
#'''
##}}}
