# From: rc/dein.vim

# Browser;
[[plugins]]
repo = 'tyru/open-browser.vim' #{{{
#on_event = 'BufRead'
# No use below
on_cmd = 'OpenBrowser'
on_map = {nx = '<Plug>(openbrowser'}
hook_add = 'runtime add/open-browser.vim'
#}}}
#[[plugins]]
#repo = 'tyru/open-browser-github.vim' #{{{
#depends = 'open-browser.vim'
#on_cmd = 'OpenGithub'
#hook_post_source = 'runtime add/open-browser-github.vim'
##}}}

# Vim on Browser
#[[plugins]]
#repo = 'raghur/vim-ghost'
## depends on chrome's extention or firefox's addon.
#hook_done_update = 'GhostInstall'
#on_cmd = 'Ghost'
#hook_add = 'runtime add/ghost.vim'

# API
[[plugins]]
repo = 'itchyny/calendar.vim' #{{{
on_cmd = 'Calendar'
hook_post_source = 'runtime add/calendar.vim'
#}}}
[[plugins]]
repo = 'wakatime/vim-wakatime' #{{{
# tracking service for coding activity.
# Note: visit https://wakatime.com/settings/api-key before using this plugin.
on_cmd = 'WakaTime'
hook_add = 'runtime add/wakatime.vim'
#}}}
# API; Collaborative Editing
[[plugins]]
repo = 'Floobits/floobits-neovim' #{{{
on_cmd = ['Floo', 'FlooShareDirPublic', 'FlooShareDirPrivate', 'FlooJoinWorkspace']
#hook_add = 'runtime add/floobits.vim'
#}}}
# API; WebAPI
[[plugins]] # has extentions
repo = 'mattn/webapi-vim' #{{{
#on_map = ['Pocket']
on_event = ['BufRead']
hook_add = 'runtime add/webapi.vim'
[[plugins]]
repo = 'soramugi/pocket.vim' #{{{
on_cmd = ['PocketList', 'PocketArchive', 'PocketFavorite']
hook_add = 'runtime add/pocket.vim'
#}}}
# API; Twitter
#[[plugins]]
#repo = 'basyura/TweetVim' #{{{
#depends = 'twibill.vim'
#on_cmd = 'TweetVim'
#hook_post_source = 'runtime add/tweet.vim'
##}}}
#[[plugins]]
#repo = 'basyura/twibill.vim' # {{{
#on_cmd = 'TweetVim'
##}}}
