#### Required ##################################################################
[[plugins]]
repo = 'Shougo/dein.vim'

### Meta
## Async
# run vim asynchronously, inc., quickrun.
[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

## Run Code
[[plugins]]
repo = 'thinca/vim-quickrun'
hook_add = '''
  let g:quickrun_config = {}
  let g:quickrun_config['markdown'] = {
    \ 'outputter': 'browser'
    \ }
  '''

### Filer
[[plugins]]
repo = 'Shougo/defx.nvim'
[[plugins]]
repo = 'kristijanhusak/defx-git'
[[plugins]]
repo = 'kristijanhusak/defx-icons'

#### Plugins Edit Smooth
[[plugins]]
repo = 'tpope/vim-surround'
# Repeats even not-default editing by "."
# e.g., surround.vim
[[plugins]]
repo = 'tpope/vim-repeat'
#[[plugins]]
#repo = 'Lokaltog/vim-easymotion'
## move between Vim panes and Tmux splits seamlessly.
#[[plugins]]
#repo = 'christoomey/vim-tmux-navigator'

## preset a template respectively.
#[[plugins]]
#repo = 'thinca/vim-template'

#### Plugins Visual
## Visual Color Themes
[[plugins]]
repo = 'tomasr/molokai'
#[[plugins]]
#repo = 'altercation/vim-colors-solarized'

## Status Bar
#[[plugins]]
#repo = 'itchyny/lightline.vim' # config is written in 'plugin.vim'
[[plugins]]
repo = 'vim-airline/vim-airline'
[[plugins]]
repo = 'vim-airline/vim-airline-themes'
depends = 'vim-airline'

## Indent Line should be visible
[[plugins]]
repo = 'Yggdroot/indentLine'
hook_add = '''
  let g:indentline_color_term = 239
  '''

#[[plugins]]
#repo = 'tyru/qfpopup.vim'

## Show marks
#[[plugins]]
#repo = 'jacquesbh/vim-showmarks'
