# Autogenerated config.py
# Documentation:
#   qute://help/configuring.html
#   qute://help/settings.html

# Uncomment this to still load settings configured via autoconfig.yml
config.load_autoconfig()

# Hint to yank codes in xml
# https://github.com/LaurenceWarne/qute-code-hint
c.hints.selectors["code"] = [
  # Select all code tags whose direct parent is not a <pre> tag.
  ":not(pre) > code",
  "pre"
]
