# From: rc/dein.vim

#[ Repeat ]
[[plugins]]
repo = 'tpope/vim-repeat'
# Note: has no help
# Note: dein seems to load except autoload/ if on_map at least.
script_type = 'plugin'
on_map = '<Plug>(Repeat'
hook_add = 'runtime add/repeat.vim'

#[ Mode ]
[[plugins]]
repo = 'kaile256/vim-submode'
#repo = 'kana/vim-submode'
# make another mode!
on_func = 'submode#'
hook_add = 'runtime add/submode.vim'
#hook_post_source = 'runtime post/submode.vim'
#hook_done_update = '''
#exe 'e' g:dein_github_dir .'/kana/vim-submode/autoload/submode.vim'
#%s/submode-/sbm-/g
#write
#[ cd ]
[[plugins]]
repo = 'mattn/vim-findroot'
on_cmd = 'FindRoot'
hook_add = 'runtime add/findroot.vim'
# To enable to :FindRoot w/ other commands through <bar>.
hook_done_update = '''
exe 'e' g:dein_github_dir .'/mattn/vim-findroot/plugin/findroot.vim'
g/command!/norm! Ea -bar
g/s:findroot(/s/1/0
write
'''

#[ Cmdline ]
[[plugins]]
repo = 'tyru/vim-altercmd'
on_event = ['CmdLineEnter', 'CmdWinEnter']
hook_post_source = 'runtime post/altercmd.vim'

#[ Register ]
[[plugins]]
repo = 'svermeulen/vim-yoink'
on_map = {nx = ['<Plug>(Yoink']}
hook_add = 'runtime add/yoink.vim'
#hook_source = 'runtime source/yoink.vim'
#hook_post_source = 'call yoink#onVimEnter()'
#[[plugins]]
#repo = 'svermeulen/vim-easyclip'
#on_event = 'BufWinEnter'
#hook_add = 'runtime add/easyclip.vim'
#hook_source = 'runtime source/easyclip.vim'
[[plugins]]
repo = 'junegunn/vim-peekaboo'
on_map = {nxi = ['<Plug>(peekaboo']}
hook_add = 'runtime add/peekaboo.vim'
hook_source = 'runtime source/peekaboo.vim'
#hook_post_source = 'runtime post/peekaboo.vim'

#[ Mark ]
#[[plugins]]
#repo = 'Yilin-Yang/vim-markbar'
## peekaboo for marks
#on_map = {nx = ['<Plug>OpenMarkbar']}

#[ Undo ]
[[plugins]]
repo = 'simnalamburt/vim-mundo'
on_cmd = 'Mundo'
hook_add = 'runtime add/mundo.vim'
hook_source = 'runtime source/mundo.vim'
#[[plugins]]
#repo = 'jaxbot/selective-undo.vim'
#on_event = 'BufRead'
#hook_post_source = 'runtime add/selective-undo.vim'
#[[plugins]]
#repo = 'machakann/vim-highlightedundo'
#if = 'executable("diff")'
#on_event = 'BufRead'
#hook_post_source = 'runtime add/highlightedundo.vim'
#[[plugins]]
#repo = 'mbbill/undotree'
#on_map = 'Undotree'
#hook_add = 'runtime add/undotree.vim'
#[ Diff ]
#[[plugins]]
#repo = 'rickhowe/diffchar.vim'
#on_if = '&diff'
## DiffUpdated for Internal diff
## FilterWritePost for External diff
#on_event = ['DiffUpdated', 'FilterWritePost']
#on_func = ['diffchar#']
#hook_source = 'runtime add/diffchar.vim'
[[plugins]]
repo = 'AndrewRadev/linediff.vim'
on_cmd = 'Linediff'
hook_add = 'runtime add/linediff.vim'
#[[plugins]]
#repo = 'chrisbra/vim-diff-enhanced'
#on_cmd = ['EnhancedDiff', 'PatienceDiff']
#hook_add = 'runtime diff-enhanced.vimrc'
# :norm <c-a>/<c-x>
#[[plugins]]
#repo = 'qwertologe/nextval.vim'
## has some errors; unintended deletion of words around the target numbers
#on_map = '<Plug>nextval'
#hook_add = 'runtime add/nextval.vim'
#[ Help ]
[[plugins]]
repo = 'thinca/vim-ref'
on_cmd = ['Ref']
on_func = ['ref#']
on_map = {nx = '<Plug>(ref-'}
hook_source = 'runtime source/ref.vim'
[[plugins]]
repo = 'notomo/helpeek.vim'
# provides a wrapper command to show help in a floating/popup window.
on_cmd = ['Helpeek']

#[ Window ]
#[[plugins]]
#repo = 'camspiers/lens.vim'
#on_func = ['lens#']
#hook_source = 'runtime source/lens.vim'
#[[plugins]]
#repo = 'camspiers/animate.vim'
#on_source = ['lens.vim']
#on_func = ['animate#']

#[ Floating Window ]
#[[plugins]]
#repo = 'ncm2/float-preview.nvim'
#on_source = ['denite.nvim', 'deolplete.nvim', 'coc.nvim']
#hook_source = 'runtime source/float-preview.vim'
#hook_done_update = '''
#exe 'e' g:dein_github_dir .'/ncm2/float-preview.nvim/plugin/float_preview.vim'
#g/au/Complete/norm! i"
#g/au/InsertLeave/norm! i"
#write
#'''
#[[plugins]]
#repo = 'voldikss/vim-floaterm'
#on_cmd = 'FloatermToggle'
#on_map = '<Plug>(floaterm-'
#hook_add = 'runtime add/floaterm.vim'
#[ Session ]
#[[plugins]]
#repo = 'xolox/vim-session'
#depend = 'xolox/vim-misc'
#on_cmd = ['SessionOpen', 'SessionSave']
#hook_done_update = '''
#exe 'e' g:dein_github_dir .'xolox/vim-session/plugin/session.vim
#g/command!/g/Session /norm! ndeBP
#g/command!/s/RestartVim/SessionVimRestart
#write
#'''
#[[plugins]]
#repo = 'thaerkh/vim-workspace'
#
#[ Startpage ]
#[[plugins]]
#repo = 'mhinz/vim-startify'

#[ Menu ]
[[plugins]]
repo = 'skywind3000/quickmenu.vim'
on_func = ['quickmenu#toggle']
hook_add = 'runtime add/quickmenu.vim'
hook_post_source = 'runtime post/quickmenu.vim'
