# From: dein/dein.vim

#[ mp3 ]
[[plugins]]
repo = 'AndrewRadev/id3.vim'
# Edit metadata for mp3 files.
# When 'flac' package is installed, it also works for FLAC files.
if = 'executable("id3")'
#[ Hex Editor ]
[[plugins]]
repo = 'Shougo/vinarise.vim'
on_cmd =  ['Vinarise']
hook_add = 'runtime add/vinarise.vim'
[[plugins]]
repo = 'rootkiter/vim-hexedit'
on_cmd =  ['Hexedit']
#[[plugins]]
#repo = 'd0c-s4vage/pfp-vim'
#on_cmd = 'Pfp'
#hook_add = 'runtime add/pfp.vim'

#[ Minimap ]
#[[plugins]]
#repo = 'severin-lemaignan/vim-minimap'
#on_cmd = 'Minimap'
#hook_add = 'runtime add/minimap.vim'
## the name, vim-minimap, causes error when jump to this repository.
#hook_done_update = '''
#e $DEIN_GITHUB_DIR/severin-lemaignan/vim-minimap/autoload/minimap.py
#g/MINIMAP/s/vim-minimap/[minimap]/e
#write
#'''
#
#[[plugins]]
#repo = 'chrisbra/NrrwRgn'
#on_event = 'VimEnter'
#hook_post_source = 'runtime add/NrrwRgn.vim'

#[[plugins]]
#repo = 'mtth/scratch.vim'
#on_cmd =  ['Scratch']
#
#[ Calendar ]
# [[plugins]]
# repo = 'rizumi/gosasyu.vim'
# # Generate calendar in Markdown format on scratch buffer.
# on_cmd = 'Gosasyu'
#[ Plugin's ]
[[plugins]]
repo = 'wsdjeg/dein-ui.vim'
on_cmd = 'DeinUpdate'
hook_add = 'runtime add/dein-ui.vim'
[[plugins]]
repo = 'haya14busa/dein-command.vim'
# For `Dein list`
on_cmd = 'Dein'
# hook_add = 'runtime add/dein-command.vim'
#[[plugins]]
#repo = 'fszymanski/fzf-gitignore'
#type = 'git'
##on_if = '@% =~# ".gitignore"'
#hook_post_source = 'runtime add/fzf-gitignore.vim'
