# From: dein/dein.vim

#[ Docker ]
[[plugins]]
repo = 'kkvh/vim-docker-tools'
# Manage docker containers with it.
on_func = [
  'docker_tools#dt_open',
  'docker_tools#dt_set_host',
  'docker_tools#complete',
  'docker_tools#container_action',
  'docker_tools#container_logs',
]
hook_add = 'runtime add/docker-tools.vim'
hook_post_source = 'runtime post/docker-tools.vim'

[[plugins]]
repo = 'skanehira/docker.vim'
if = '!has("nvim")'
# Manage docker's images/containers
# Note: unavailable on neovim because of job_start()
on_cmd = [
  'Docker',
  'DockerImages',
  'DockerImagePull',
  'DockerImageSearch',
  'DockerContainers',
  'DockerMonitorStart',
  'DockerEvents',
  'DockerNetworks',
  'DockerVersion'
]
hook_source = 'runtime source/docker.vim'

#[[plugins]]
#repo = 'skanehira/docker-compose.vim'
## Error:
## Error generating helptags:
## Vim(helptags):E154: Duplicate tag "docker-compose" in file /home/kaile256/.cache/dein/.cache/init.vim/.dein/doc/docker-compose.txt
## function <SNR>346_on_pull_exit[45]..<SNR>346_recache_rtp[19]..dein#recache_runtimepath[1]..dein#install#_recache_runtimepath[19]..<SNR>362_helptags, line 12
#on_cmd = 'DockerCompose'
#hook_add = 'runtime add/docker-compose.vim'

#[ Pair Programming ]
#[[plugins]]
#repo = 'cathook/vim-shrvim'
# Note: necessary to rewrite to work it
#on_cmd = ['ShrVimConnect']
#hook_add = 'runtime add/shrvim.vim'
#build = '''
#mv vim/plugin .
#rmdir vim
#'''
#
#[[plugins]]
#repo = 'derteta/vimpair'
## Error: buggy on init
#on_cmd = 'VimpairServerStart "127.0.0.1"'
#hook_add = 'runtime add/vimpair.vim'

[[plugins]]
repo = 'xavierchow/vim-sequence-diagram'
on_map = '<Plug>GenerateDiagram'
on_cmd = '<Plug>GenerateDiagram'
hook_add = 'runtime add/sequence-diagram.vim'

#[ Doc ]
#[[plugins]]
#repo = 'HiPhish/info.vim'
#on_cmd = 'Info'
#hook_add = 'runtime add/info.vim'
#hook_done_update = '''
#e $DEIN_GITHUB_DIR/HiPhish/info.vim/plugin/info.vim
#g/nnoremap/g/K/s/ K / gK /e
#write
#'''

[[plugins]]
repo = 'sunaku/vim-dasht'
on_cmd = 'Dasht'
hook_source = 'runtime add/dasht.vim'

#[ File Rename ]
#[[plugins]]
#repo = 'qpkorr/vim-renamer'
## Note: behaves different than what I expects.
#on_cmd = 'Renamer'
#hook_add = 'runtime renamer.vimrc'

#[ i3-wm ]
#[[plugins]]
#repo = 'termhn/i3-vim-nav'
#on_if = 'isdirectory("~/go/sadd/github.com/termhn/i3-vim-nav")'
#hook_post_source = 'runtime add/i3-vim-nav.vim'

