# From: rc/dein.vim
# Ref: fugitive.toml

[[plugins]]
repo = 'ruanyl/vim-gh-line'
# open github in browser at the current line
on_cmd =  ['GHInteractive', 'GBInteractive']
#[[plugins]]
#repo = 'whatyouhide/vim-lengthmatters'
## change highlight &tw
#on_event = 'Colorscheme'
#[ Workflow ]
[[plugins]]
repo = 'iberianpig/tig-explorer.vim'
# no nest of vim-tig-vim-tig-... using host vim process
on_cmd = [
  'TigOpenCurrentFile',
  'TigOpenProjectRootDir',
  'TigGrep',
  'TigBlame',
]
[[plugins]]
repo = 'jreybert/vimagit'
on_cmd =  ['Magit']
#[ Blame ]
#[[plugins]]
#repo = 'rhysd/ghpr-blame.vim'
## Note: seems no use in neovim
#if = "!has('nvim')
#on_cmd =  ['GHPRBlame']
#[[plugins]]
#repo = 'tveskag/nvim-blame-line'
# Note: seems to have some bugs
## shows blames in virtual line
#if = 'has("nvim")'
#on_cmd =  ['ToggleBlameLine', 'SingleBlameLine', 'EnableBlameLine']
#[[plugins]]
#repo = 'iamcco/sran.nvim'
#if = 'has("nvim") || v:version >= 801'
#hook_done_update = 'call sran#util#install()'
#on_func  = ['sran#rpc#']
#hook_add = 'runtime add/sran.vim'
#[[plugins]]
#repo = 'iamcco/git-p.nvim'
## shows blames in virtual line
#depend = 'sran.nvim'
#type     = 'git'
#on_event = 'BufRead'
#hook_source = 'runtime source/git-p.vim'
#[[plugins]]
#repo = 'zivyangll/git-blame.vim'
## Ref: zivyangll/git-blame.vim/issues/18
##  causes an error on 'cd' with vimproc
#on_cmd = ['GitBlame']
#on_func = ['gitblame#echo']
#hook_add = '''
#exe 'source' g:dein_github_dir .'/zivyangll/git-blame.vim/plugin/gitblame.vim'
#'''

#[[plugins]]
#repo = 'RobertAudi/git-blame.vim'
#on_func = ['gitblame#blame']

#[ Log ]
#[[plugins]]
#repo = 'junkblocker/git-time-lapse'
## use map to <Left>/<Right> and <S-Left>/<S-Right>
#on_cmd = ['GitTimeLapse']
[[plugins]]
repo = 'cohama/agit.vim'
# git log viewer; faster than the others presently
# TODO: set each colors on different branch's flow like vim-gitv
on_cmd = 'Agit'
hook_add = 'runtime add/agit.vim'
hook_source = 'runtime source/agit.vim'
[[plugins]]
repo = 'airblade/vim-gitgutter'
# enough only with coc.nvim & fugitive.vim?
on_source = ['vim-foldpeek']
on_event = 'BufRead'
hook_add = 'runtime add/gitgutter.vim'
hook_source = 'runtime source/gitgutter.vim'
hook_post_source = 'runtime post/gitgutter.vim'
#[[plugins]]
#repo = 'lambdalisue/gina.vim'
#on_event = ['BufWritePost']
#hook_post_source = 'runtime add/gina.vim'

#[ Rebase ]
[[plugins]]
repo = 'hotwatermorning/auto-git-diff'
on_ft = ['gitrebase', 'git-rebase-todo']
on_map = {nx = '<Plug>(auto-git-diff-'}
#[[plugins]]
#repo = 'salcode/vim-interactive-rebase-reverse'
## reverse commit order from top-to-bottom to bottom-to-top
#on_ft = ['gitrebase']
[[plugins]]
repo = 'piersy/vim-rebase-view'
on_func = ['rebase_view#']

#[ Stash ]
#[[plugins]]
#repo = 'tweekmonster/gitbusy.vim'
## automatic stash on checkout, via :GitBusy
#on_cmd =  ['GitBusy']
#[ Merge ]
[[plugins]]
repo = 'samoshkin/vim-mergetool'
on_cmd = ['MergetoolStart']
hook_add = 'runtime add/mergetool.vim'
hook_source = 'runtime source/mergetool.vim'

#[ Git Ignore ]
[[plugins]]
repo = 'iwataka/gitignore.vim'
type = 'git'
on_cmd = ['Gitignore']
