# From: rc/dein.vim

#[ Help ]
[[plugins]]
repo = 'vim-jp/vimdoc-ja-working'
on_cmd = ['Helptags', 'help', 'helpgrep']

#[ SKK ]
#[[plugins]]
#repo = 'tyru/skk.vim'
#on_map = {ci = ['<Plug>(skk']}
#hook_add = 'runtime add/skk.vim'
[[plugins]]
repo = 'tyru/eskk.vim'
on_cmd = 'eskk#enable()'
hook_add = 'runtime add/eskk.vim'
hook_source = 'runtime source/eskk.vim'
hook_done_update= '''
e $DEIN_GITHUB_DIR/tyru/eskk.vim/autoload/eskk.vim
" Comment out unnecessary modes
silent! g/^\s*"\@!Eskk.*zenei/norm! I"
silent! g/^\s*"\@!Eskk.*to-hira/norm! I"
silent! g/^\s*"\@!sticky.*;/norm! I"
write!
'''
[[plugins]]
repo = 'tyru/skkdict.vim'
# Syntax Files for skkdict.
on_path = '*.dict'

#[ Motion ]
[[plugins]]
repo = 'deton/jasegment.vim'
# no mappings for 'w', 'e', and so on.
# remaps `W`,`E`, and so on.
on_ft = 'markdown'
hook_source = 'runtime source/jasegment.vim'

[[plugins]]
repo = 'deton/jasentence.vim'
# remaps `)(` for '、' and '。'
on_ft = 'markdown'
#hook_post_source = 'runtime add/jasentence.vim'

#[[plugins]]
#repo = 'fuenor/JpFormat.vim'
#on_ft = ['markdown']
#on_cmd = 'Jp'
#hook_add = 'runtime add/JqFormat.vim'

#[[plugins]]
#repo = 'kana/vim-textobj-jabraces'
## provides textobj of japanese braces.
## e.g., for 『』as `ajk`
##       to <Plug>(textobj-jabraces-double-kakko-a)
#on_ft = 'markdown'
#hook_add = 'runtime add/textobj-jabraces.vim'
