# From: dein/dein.vim

[[plugins]]
repo = 'kana/vim-operator-user'
lazy = 0
[[plugins]]
repo = 'thinca/vim-operator-sequence'
lazy = 0

#[ Comment out ]
# [[plugins]]
# repo = 'tomtom/tcomment_vim'
# # Memo: complex named <Plug>-mappings
# on_map = '<Plug>TComment'
# hook_add = 'runtime add/tcomment.vim'
[[plugins]]
repo = 'tyru/caw.vim'
# operater requires kana/vim-operator-user
# Note: no use <Plug>(caw:foo:bar:operator), why?
on_map = '<Plug>(caw:'
hook_add = 'runtime add/caw.vim'
hook_source = 'runtime source/caw.vim'
#[[plugins]]
#repo = 'scrooloose/nerdcommenter'
## Reason: has no operater
#on_map = '<Plug>NERDCommenter'
#hook_add = 'runtime add/nerdcommenter.vim'
#[[plugins]]
#repo = 'tpope/vim-commentary'
## Simplest
#on_map = '<Cmd>Commentary'
#hook_add = 'runtime add/plugin.vim'

#[ Arrangement ]
# [[plugins]]
# repo = 'machakann/vim-swap'
# # Swap parameters positions. It also includes textobjects.
# Use AndrewRadev/sideways.vim instead
# on_map = {nox = '<Plug>(swap-'}
# hook_add = 'runtime add/swap.vim'
[[plugins]]
repo = 'AndrewRadev/sideways.vim'
# Swap parameters positions. It also includes textobjects.
# Addition to comma-separated parameters, it also detects css declarations
# which separated by ';', HTML attributes, Cucumber tables components, Go lists
# surrounded by '{}', etc.
# Moreover, configurable globally/localy like switch.vim
on_cmd = 'Sideways'
on_map = {ox = '<Plug>Sideways'}
hook_add = 'runtime add/sideways.vim'
hook_source = 'runtime source/sideways.vim'
[[plugins]]
repo = 'AndrewRadev/switch.vim'
# switch as predefined, such as "true" & "false".
on_cmd = ['Switch', 'SwitchReverse']
on_func = ['switch#']
hook_add = 'runtime add/switch.vim'
hook_source = 'runtime source/switch.vim'
# [[plugins]]
# repo = 'nishigori/increment-activator'
# # almost same as AndrewRadev/switch.vim; configurable in Dict of filetypes.
# # Note: it only work for word boundary.
# on_map = {ni = ['<Plug>(increment-activator']}
# hook_add = 'runtime add/increment-activator.vim'
[[plugins]]
repo = 'junegunn/vim-easy-align'
on_map = ['<Plug>(EasyAlign)', '<Plug>(LiveEasyAlign)']
on_cmd = 'EasyAlign'
hook_add = 'runtime add/easy-align.vim'
[[plugins]]
repo = 'AndrewRadev/splitjoin.vim'
on_cmd = ['SplitjoinJoin', 'SplitjoinSplit']
on_map = ['<Plug>SplitjoinJoin', '<Plug>SplitjoinSplit']
hook_add = 'runtime add/splitjoin.vim'

[[plugins]]
repo = 'emonkak/vim-operator-sort'
on_map = {nx = ['<Plug>(operator-sort']}
hook_add = 'runtime add/operator-sort.vim'

#[ Simultaneous ]
[[plugins]]
repo = 'machakann/vim-sandwich'
on_map = {nox = [
  '<Plug>(textobj-sandwich-',
  '<Plug>(operator-sandwich-',
]}
hook_add = 'runtime add/sandwich.vim'
hook_source = 'runtime source/sandwich.vim'
hook_post_source = 'runtime post/sandwich.vim'
hook_done_update = '''
exe 'argadd' $DEIN_GITHUB_DIR .'/machakann/vim-sandwich/autoload/textobj/sandwich/recipes.vim'
exe 'argadd' $DEIN_GITHUB_DIR .'/machakann/vim-sandwich/autoload/sandwich.vim'
exe 'argadd' $DEIN_GITHUB_DIR .'/machakann/vim-sandwich/autoload/operator/sandwich/operator.vim'
silent! argdo! g/= type(c) == s:type_num ? nr2char(c) : c/norm! na (c ==# "\<S-lt>") ? '<' :
silent! argdo! write
argdelete *
'''
#[[plugins]]
#repo = 'tpope/vim-surround'
#on_event = 'BufRead'
#hook_post_source = 'runtime add/surround.vim'

#[[plugins]]
#repo = 'tommcdo/vim-express'
#on_event = 'VimEnter'
#hook_post_source = 'runtime add/express.vim'

#[ Substitute ]
#[[plugins]]
#repo = 'svermeulen/vim-subversive'
## just puts selected area into :s.
#on_map = {nx = ['<Plug>(Subversive']}
#hook_add = 'runtime add/subversive.vim'

#[ Swap ]
#[[plugins]]
#repo = 'tommcdo/vim-exchange'
#on_map = {nx = ['<Plug>(Exchange']}
#hook_add = 'runtime add/exchange.vim'
#hook_source = 'runtime source/exchange.vim'
#[[plugins]]
#repo = 'osyo-manga/vim-operator-swap'
## Note: does't work.
## Require 2 keys to be mapped.
#on_map = {nx = ['<Plug>(operator-swap']}
#hook_add = 'runtime add/operator-swap.vim'
[[plugins]]
repo = 'SausageCats/vim-operator-swap'
# Require 2 keys to be mapped.
on_map = {nx = ['<Plug>(operator-swap-']}
hook_add = 'runtime add/operator-swap-SausageCats.vim'
hook_source = 'runtime source/operator-swap-SausageCats.vim'
