# From: dein/dein.vim
# Ref: ftplugin.toml

#[ Detect ]
[[plugins]]
repo = 'itchyny/vim-autoft'
# Fill &ft as predefined patterns when &ft is undefined.
on_func = 'autoft#'
hook_add = 'runtime add/autoft.vim'
hook_source = 'runtime source/autoft.vim'

#[ Append Highlight ]
[[plugins]]
repo = 'itchyny/vim-highlighturl'
on_event = 'Colorscheme'

#[ Multi Filetypes ]
# [[plugins]]
# repo = 'sheerun/vim-polyglot'
# # Note: it often fails on guard.
# # No syntax for java
# on_event = 'FileType'
# hook_source = 'runtime source/polyglot.vim'

#[[plugins]]
#repo = 'maralla/validator.vim'
## Note: async
#on_ft = [
#  'vim',
#  'c',
#  'cpp',
#  'python',
#  'cython',
#  'css',
#  'javascript',
#  'ruby',
#  'json',
#  'lua',
#  'sh',
#  'rst',
#  'go',
#  'rust'
#]
#hook_source = 'runtime source/validator.vim'
#
[[plugins]]
repo = 'fcpg/vim-weblogs'
# syntax for web-related log files
lazy = 0

#[ Compile ]
#[[plugins]]
#repo = 'jackguo380/vim-lsp-cxx-highlight'
## Note: imperfect
## semantic highlight; recommended with ccls on coc.nvim
#on_ft = ['c', 'cpp', 'objc', 'objcpp', 'cc']
[[plugins]]
repo = 'bfrg/vim-cpp-modern'
lazy = 0
#[[plugins]]
#repo = 'octol/vim-cpp-enhanced-highlight'
#lazy = 0

#[[plugins]]
#repo = 'fatih/vim-go'
## CAUTION: override ':norm K'.
#on_ft = 'go'
#hook_source = 'runtime source/go.vim'

#[[plugins]]
#repo = 'rust-lang/rust.vim'
#on_ft = 'rust'
#hook_source = 'runtime source/rust.vim'

#[[plugins]]
#repo = 'udalov/kotlin-vim'
#on_ft = 'kotlin'

#[[plugins]]
#repo = 'neovimhaskell/haskell-vim'
## the development stopped 2 y ago
#on_ft = 'haskell'
#hook_post_source = 'runtime add/haskell.vim'
[[plugins]]
repo = 'goolord/vim2hs'
on_ft = ['haskell']

[[plugins]]
repo = 'stevearc/vim-arduino'
# includes syntax/ Ultisnips/(only extends cpp's)
lazy = 0
#[ Interpreter ]
#[[plugins]]
#repo = 'tbastos/vim-lua'
#on_ft = 'lua'
#hook_source = 'runtime lua.vim'

#[[plugins]]
#repo = 'drmingdrmer/vim-indent-lua'
#on_ft = 'lua'

#[[plugins]]
#repo = 'Alloyed/lua-lsp'
#on_ft = 'lua'

#[ Javascript ]
# [[plugins]]
# repo = 'MaxMEllon/vim-jsx-pretty'
# on_path = ['\.js$', '\.jsx$', '\.ts$', '\.tsx$']
[[plugins]]
repo = 'neoclide/vim-jsx-improve'
# includes motion mappings for '[[', '[]' and so on.
on_path = ['\.js$', '\.jsx$']
on_ft = [
  'javascript',
  'javascript.jsx',
  'javascriptreact',
]
# [[plugins]]
# repo = 'leafgarland/typescript-vim'
# on_path = ['\.ts$', '\.tsx$']
# on_ft = [
#   'typescript',
#   'typescript.tsx',
#   'typescriptreact',
# ]
# [[plugins]]
# repo = 'peitalin/vim-jsx-typescript'
# on_path = ['\.tsx$']
# on_ft = [
#   'typescriptreact'
#   'typescript.tsx'
# ]
[[plugins]]
repo = 'HerringtonDarkholme/yats.vim'
on_path = ['\.ts$', '\.tsx$']
on_ft = [
  'typescript',
  'typescriptreact',
]
# [[plugins]]
# repo = 'othree/yajs.vim'
# on_path = ['\.js$', '\.jsx$', '\.ts$', '\.tsx$']
# [[plugins]]
# repo = 'billyvg/tigris.nvim'
# build = './install.sh'
# on_path = ['\.js$', '\.jsx$', '\.ts$', '\.tsx$']
# hook_source = 'runtime source/tigris.vim'
# [[plugins]]
# repo = 'bigfish/vim-js-context-coloring'
# # on_path = ['\.js$', '\.jsx$', '\.ts$', '\.tsx$']

#[ Javascript.styled-jsx ]
[[plugins]]
repo = 'styled-components/vim-styled-components'
on_path = ['\.js$', '\.jsx$', '\.ts$', '\.tsx$']

[[plugins]]
repo = 'alampros/vim-styled-jsx'
# Recommended by [vercel/styled-jsx](https://github.com/vercel/styled-jsx)
# Note: only contains syntax/jsx.vim; you should set `runtime syntax/jsx.vim`.
on_path = ['\.js$', '\.jsx$', '\.ts$', '\.tsx$', '\.css$']

#[ CSS ]
[[plugins]]
repo = 'hail2u/vim-css3-syntax'
on_path = ['\.js$', '\.jsx$', '\.ts$', '\.tsx$', '\.css$']
# [[plugins]]
# # repo = 'amadeus/vim-css'
# on_path = ['\.js$', '\.jsx$', '\.ts$', '\.tsx$', '\.css$']

#[ Shell ]
#[[plugins]]
#repo = 'dag/vim-fish'
#on_ft = 'fish'

#[[plugins]]
#repo = 'chrisbra/vim-zsh'
#on_ft = 'zsh'
[[plugins]]
repo = 'zinit-zsh/zinit-vim-syntax'
lazy = 0

#[[plugins]]
#repo = 'ericpruitt/tmux.vim'
#on_ft = 'tmux'


#[ Text-like ]
#[[plugins]]
#repo = 'freitass/todo.txt-vim'
## Use `set syn=help` instead
#on_ft = 'text'
[[plugins]]
repo = 'qnighy/satysfi.vim'
on_path = 'saty'

#[ Diagram ]
[[plugins]]
repo = 'aklt/plantuml-syntax'
lazy = 0

#[ Test ]
[[plugins]]
repo = 'yasuhiroki/circleci.vim'
lazy = 0

#[ Database ]
#[[plugins]]
#repo = 'exu/pgsql.vim'
#on_event = ['BufRead']
#
#[ Network ]
[[plugins]]
repo = 'momota/cisco.vim'
lazy = 0
[[plugins]]
repo = 'momota/junos.vim'
lazy = 0

#[ for Config ]
[[plugins]]
repo = 'kevinoid/vim-jsonc'
on_ft = ['json', 'jsonc']
on_path = ['json', 'cjsn$', 'jshintrc$']
#[[plugins]]
#repo = 'vmchale/tomlcheck-vim'
#on_ft = 'toml'
[[plugins]]
repo = 'cespare/vim-toml'
# fails when lazy=0
on_ft = 'toml'
#[[plugins]]
#repo = 'maralla/vim-toml-enhance'
#depends = 'cespare/vim-toml'
#on_ft = 'toml'
[[plugins]]
repo = 'delphinus/vim-toml-dein'
# syntax highlight for 'hook_add'
depends = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'PotatoesMaster/i3-vim-syntax'
# Note: vim-polyglot doesn't have enough syntax for i3.
# CAUTION: Not Maintained Anymore
lazy = 0

#[[plugins]]
#repo = 'mboughaba/i3config.vim'
## Note: No enough Syntax Configured yet
#on_ft = 'i3'
