# From: rc/dein.vim
# Ref: ftplugin.toml

#[ Multi Filetypes ]
[[plugins]]
repo = 'sheerun/vim-polyglot'
# No syntax for java
# includes syntax for systemd
if = "&ft !=# '\|zsh\|terminal\|i3\|javascript\|haskell'"
on_event = ['FileType']
hook_source = 'runtime source/polyglot.vim'

#[[plugins]]
#repo = 'maralla/validator.vim'
## Note: async
#on_ft = [
#  'vim',
#  'c',
#  'cpp',
#  'python',
#  'cython',
#  'css',
#  'javascript',
#  'ruby',
#  'json',
#  'lua',
#  'sh',
#  'rst',
#  'go',
#  'rust'
#]
#hook_source = 'runtime source/validator.vim'
#
[[plugins]]
repo = 'fcpg/vim-weblogs'
on_ft = [
  'fail2banlog'
  'httplog',
  'httplogerror',
  'modseclog',
  'modsectx',
  'phplog',
  'webmonolog',
 ]

#[ Compile ]
[[plugins]]
repo = 'jackguo380/vim-lsp-cxx-highlight'
# semantic highlight; recommended with ccls on coc.nvim
on_ft = ['c', 'cpp', 'objc', 'objcpp']

#[[plugins]]
#repo = 'fatih/vim-go'
## CAUTION: override ':norm K'.
#on_ft = 'go'
#hook_source = 'runtime source/go.vim'

#[[plugins]]
#repo = 'rust-lang/rust.vim'
#on_ft = 'rust'
#hook_source = 'runtime source/rust.vim'

#[[plugins]]
#repo = 'udalov/kotlin-vim'
#on_ft = 'kotlin'

#[[plugins]]
#repo = 'neovimhaskell/haskell-vim'
## the development stopped 2 y ago
#on_ft = 'haskell'
#hook_post_source = 'runtime add/haskell.vim'
[[plugins]]
repo = 'goolord/vim2hs'
on_ft = ['haskell']

#[ Interpreter ]
[[plugins]]
repo = 'billyvg/tigris.nvim'
build = './install.sh'
#depend = 'node-host'
# Note: node-host, previously depended on, has been merged into neovim!
#       Ref: neovim/neovim/pull/7458
on_ft = ['javascript', 'javascript.jsx']
hook_source = 'runtime source/tigris.vim'

#[[plugins]]
#repo = 'tbastos/vim-lua'
#on_ft = 'lua'
#hook_source = 'runtime lua.vim'

#[[plugins]]
#repo = 'drmingdrmer/vim-indent-lua'
#on_ft = 'lua'

#[[plugins]]
#repo = 'Alloyed/lua-lsp'
#on_ft = 'lua'


#[ Shell ]
#[[plugins]]
#repo = 'dag/vim-fish'
#on_ft = 'fish'

#[[plugins]]
#repo = 'chrisbra/vim-zsh'
#on_ft = 'zsh'
[[plugins]]
repo = 'zinit-zsh/zinit-vim-syntax'
on_ft = 'zsh'

#[[plugins]]
#repo = 'ericpruitt/tmux.vim'
#on_ft = 'tmux'


#[ for Text-like ]
#[[plugins]]
#repo = 'othree/html5.vim'
# Note: contributes in vim-polyglot
#on_ft = 'html'
#[[plugins]]
#repo = 'freitass/todo.txt-vim'
## Use `set syn=help` instead
#on_ft = 'text'

#[ Diagram ]
[[plugins]]
repo = 'aklt/plantuml-syntax'
on_path = ['\.pu$', '\.uml$', '\.puml$', '\.iuml$', '\.plantuml$']

#[ Test ]
[[plugins]]
repo = 'yasuhiroki/circleci.vim'
if = "expand('%:h:t') =~# '.circleci'"
on_ft = ['yaml']

#[ Database ]
#[[plugins]]
#repo = 'exu/pgsql.vim'
#on_event = ['BufRead']
#
#[ Network ]
[[plugins]]
repo = 'momota/cisco.vim'
on_path = '\.cisco$'
[[plugins]]
repo = 'momota/junos.vim'
on_path = '\.junos$'

#[ for Config ]
[[plugins]]
repo = 'delphinus/vim-toml-dein'
# syntax highlight for 'hook_add'
on_ft = 'toml'

#[[plugins]]
#repo = 'vmchale/tomlcheck-vim'
#on_ft = 'toml'

#[[plugins]]
#repo = 'cespare/vim-toml'
#on_ft = 'toml'

[[plugins]]
repo = 'PotatoesMaster/i3-vim-syntax'
# Note: vim-polyglot doesn't have enough syntax for i3.
# CAUTION: Not Maintained Anymore
on_ft = 'i3'

#[[plugins]]
#repo = 'mboughaba/i3config.vim'
## Note: No enough Syntax Configured yet
#on_ft = 'i3'
