# From: rc/dein.vim
# Else: toml/ftplugin.toml

#[ HTML ]
[[plugins]]
repo = 'turbio/bracey.vim'
on_cmd = ['Bracey']
hook_add = 'runtime add/bracey.vim'
hook_source = 'runtime source/bracey.vim'
[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['html', 'xml', 'xsl', 'php']

#[[plugins]]
#repo = 'lyokha/vim-publish-helper'
#on_ft = 'pandoc'
#[[plugins]]
#repo = 'lervag/vimtex'
#on_ft = 'tex'
#hook_post_source = 'runtime add/vimtex.vim'
#[[plugins]]
#repo = 'greyblake/vim-preview'
## causes error
#on_func = ['preview#show_html']
#hook_source = 'runtime source/preview.vim'

#[[plugins]]
#repo = 'othree/html5.vim'
# Note: contributes in vim-polyglot
#on_ft = 'html'
#[ PHP ]
[[plugins]]
repo = 'vim-scripts/php.vim-html-enhanced'
on_ft = ['php']
#[[plugins]]
#repo = 'berrygoudswaard/vim-php-html-indent'
#on_ft = ['php']
#[[plugins]]
#repo = '2072/PHP-Indenting-for-VIm'
#on_ft = ['php']

#[[plugins]]
#repo = 'phpactor/phpactor'
#on_ft = ['php']

#[ CSV ]
[[plugins]]
repo = 'mechatroner/rainbow_csv'
on_ft = ['csv', 'sql']
[[plugins]]
repo = 'chrisbra/csv.vim'
on_ft = ['csv']

#[ SQL ]
[[plugins]]
repo = 'joereynolds/SQHell.vim'
on_cmd = [
  'SQHShowDatabases',
  'SQHShowTablesForDatabase',
]
hook_add = 'runtime add/SQHell.vim'
hook_source = 'runtime source/SQHell.vim'

#[[plugins]]
#repo = 'tpope/vim-dadbod'
#on_cmd = ['DB']
#
#[[plugins]]
#repo = 'vim-scripts/dbext.vim'
#on_cmd = [
#'DBExtSQL',
#'DBConnect',
#]
#
[[plugins]]
repo = 'alcesleo/vim-uppercase-sql'
on_ft = ['sql']
[[plugins]]
repo = 'mattn/vim-sqlfmt'
build = 'pip3 install --upgrade sqlparse'
on_ft = ['sql']
[[plugins]]
repo = 'cosminadrianpopescu/vim-sql-workbench'
on_ft = ['sql']
