#### From: dein.vimrc
#### Ref: Init.toml

### Indent
[[plugins]]
# indent line should be visible
repo = 'Yggdroot/indentLine'
on_event = 'BufReadPre'
hook_post_source = 'runtime indentline.vimrc'

### Paren
[[plugins]]
repo = 'luochen1990/rainbow'
## CAUTION: source rainbow.vimrc AFTER :colorscheme.
on_event = 'BufReadPost'

### Resonance
[[plugins]]
## Better %
repo = 'andymass/vim-matchup'
on_event = 'CursorMoved'
[[plugins]]
repo = 'itchyny/vim-cursorword'
on_event = 'CursorMoved'

### Substitution
[[plugins]]
repo = 'osyo-manga/vim-over'
on_event = 'CmdlineEnter'
hook_post_source = 'runtime over.vimrc'
