#### From: dein.vim

### Color Themes
[[plugins]]
repo = 'tomasr/molokai'
on_if = 'has("nvim")'
hook_post_source = 'runtime! molokai.vimrc'
#[[plugins]]
#repo = 'altercation/vim-colors-solarized'

#### Indent
[[plugins]]
# indent line should be visible
repo = 'Yggdroot/indentLine'
hook_post_source = 'runtime! indentline.vimrc'
on_event = 'BufReadPre'

#### Paren
[[plugins]]
repo = 'luochen1990/rainbow'
on_event = 'BufReadPost'
hook_post_source = 'runtime! rainboe.vimrc'
