#### From: dein.vim
#### Ref: Init.toml

#### Color Themes
### CAUTION: Colorscheme MUST be sourced on time.

#### Indent
[[plugins]]
# indent line should be visible
repo = 'Yggdroot/indentLine'
on_event = 'BufReadPre'
hook_post_source = 'runtime! indentline.vimrc'

#### Paren
[[plugins]]
repo = 'luochen1990/rainbow'
on_event = 'BufReadPost'
hook_post_source = 'runtime! rainbow.vimrc'

#### Substitution
[[plugins]]
repo = 'osyo-manga/vim-over'
on_event = 'CmdlineEnter'
hook_post_source = 'runtime! over.vimrc'
