#### From: dein.vimrc

### Browser
[[plugins]] #{{{
repo = 'tyru/open-browser.vim'
on_if = ['executable("qutebrowser")','executable("w3m")']
hook_post_source = 'runtime! open-browser.vimrc'
#}}}

### Calendar
[[plugins]]
repo = 'itchyny/calendar.vim'
on_event = 'VimEnter'
on_cmd = '<a-q>'
hook_post_source = 'runtime calendar.vimrc'

### Tags
[[plugins]]
repo = 'jsfaint/gen_tags.vim'
on_event = 'BufLeave'
hook_post_source = 'runtime gen_tags.vimrc'
#[[plugins]]
#repo = 'majutsushi/tagbar'
#on_event = ['BufNew','BufReadPost']
#hook_post_source = 'runtime tagbar.vimrc'
[[plugins]]
repo = 'liuchengxu/vista.vim'
on_event = ['BufNew','BufRead']
hook_post_source = 'runtime vista.vimrc'

### i3-wm
#[[plugins]]
#repo = 'termhn/i3-vim-nav'
#on_if = 'isdirectory("~/go/src/github.com/termhn/i3-vim-nav")'
#hook_post_source = 'runtime i3-vim-nav.vimrc'
