#### From: dein.vimrc

### Browser
[[plugins]]
repo = 'tyru/open-browser.vim'
on_if = 'executable("qutebrowser")'
hook_post_source = 'runtime! open-browser.vimrc'

### Calendar
[[plugins]]
repo = 'itchyny/calendar.vim'
on_event = 'VimEnter'
hook_post_source = 'runtime calendar.vimrc'

#### i3-wm
#[[plugins]]
#repo = 'termhn/i3-vim-nav'
#on_if = 'exists("/usr/local/bin/termhn/i3-vim-nav")'
#hook_post_source = 'runtime i3-vim-nav.vimrc'
