#### From: dein.vimrc

## Snippet
[[plugins]]
repo = 'Shougo/neosnippet-snippets'
on_event = 'InsertEnter'
on_ft = 'snippet'
[[plugins]]
repo = 'Shougo/neosnippet.vim'
on_event = 'InsertEnter'
on_ft = 'snippet'
depends = 'neosnippet-snippets'
hook_add = 'runtime! neosnippet.vimrc'

#### Language Support
### Org Mode
[[plugins]]
repo = 'jceb/vim-orgmode'
on_ft = 'org'
hook_post_source = 'runtime orgmode.vimrc'

### 13-wm
[[plugins]]
repo = 'PotatoesMaster/i3-vim-syntax'
on_ft = 'i3'
### LaTex
[[plugins]]
repo = 'lervag/vimtex'
on_ft = 'tex'
hook_post_source = 'runtime! vimtex.vimrc'
### Python
# supports pip-packages, independently installed in shell, to work on vim
[[plugins]]
repo = 'plytophogy/vim-virtualenv'
on_ft = 'python3'

### Markdown
[[plugins]]
repo = 'dhruvasagar/vim-table-mode'
hook_add = 'runtime! table-mode.vimrc'
on_event = 'BufReadPre'
on_ft = 'markdown'
[[plugins]]
repo = 'suan/vim-instant-markdown'
on_event = 'BufRead'
on_ft = 'markdown'

### Html
## Emmet
[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = 'html'
## Tag
# auto-close tag
[[plugins]]
repo = 'alvan/vim-closetag'
on_event = 'BufRead'
hook_add = 'runtime! closetag.vimrc'
on_ft = ['html', 'javascript']
hook_add = '''
  let g:cloesetag_filenames = '*.html,*.vue'
  '''

### Syntax
## Language Console
[[plugins]]
repo = 'dag/vim-fish'
on_ft = 'fish'
[[plugins]]
repo = 'ericpruitt/tmux.vim'
on_ft = 'tmux'

## Language Functional
[[plugins]]
repo = 'udalov/kotlin-vim'
on_ft = 'kotlin'
[[plugins]]
repo = 'Alloyed/lua-lsp'
on_ft = 'lua'

## Language Expression
[[plugins]]
repo = 'tpope/vim-markdown'
on_ft = 'markdown'
[[plugins]]
repo = 'elzr/vim-json'
on_ft = 'json'
hook_add = '''
  " show up auto-hidden '"'.
  let g:vim_json_syntax_conceal = 0
  '''
[[plugins]]
repo = 'cespare/vim-toml' 
on_ft = 'toml'
# syntax highlight for 'hook_add'
[[plugins]]
repo = 'delphinus/vim-toml-dein' 
on_ft = 'toml'
