#### From: dein.vimrc

### Required
[[plugins]]
repo = 'Shougo/dein.vim'
hook_done_update= 'runtime reinstall.vim'

### Git
[[plugins]]
repo = 'tpope/vim-fugitive'
type = 'git'
hook_add = 'runtime fugitive.vimrc'

### FZF
[[plugins]]
repo = 'junegunn/fzf' #{{{
[[plugins]]
repo = 'junegunn/fzf.vim'
hook_add = 'runtime fzf.vimrc'
#}}}

#### Color Themes
## CAUTION: Colorscheme MUST be sourced after dein#end() on dein.vim.
## Ref: appearance.toml
[[plugins]]
repo = 'morhetz/gruvbox' #{{{
if = 'has("nvim")'
#}}}

### Status Bar
#[[plugins]]
## ERORR: g:lightline is undefined.
#repo = 'itchyny/lightline.vim' # config is written in 'plugin.vim'
#hook_add = 'runtime! lightline.vimrc'
[[plugins]]
repo = 'vim-airline/vim-airline'
hook_add = 'runtime airline.vimrc'
[[plugins]]
repo = 'vim-airline/vim-airline-themes'

### Denite
#[[plugins]]
### CAUTION: denite.vimrc MUST be sourced after dein#end() on dein.vim.
#repo = 'Shougo/denite.nvim' #{{{
#if = 'has("python3")'
#hook_add = 'runtime denite.vimrc'
##}}}
