#### From: dein.vimrc
#### Ref: appearance.toml

### Required
[[plugins]]
repo = 'Shougo/dein.vim'
hook_add = '''
  set rtp+=~/.config/nvim/config.d/plugin.d
  '''
hook_done_update= '''
    au VimEnter * :UpdateRemotePlugins<cr>
  '''

## Async Processor
[[plugins]]
# run vim-plugins asynchronously, like openbrowser, quickrun.
repo = 'Shougo/vimproc.vim'
build = 'make'

### Completion
[[plugins]]
repo = 'neoclide/coc.nvim'
hook_post_source = 'runtime coc.vimrc'
hook_done_update = '''
  call coc#util#install()
  CocInstall coc-json coc-tsserver coc-html coc-yaml coc-python coc-vimlsp
  CocInstall coc-lists coc-git coc-yank coc-highlight coc-snippets
  '''

#### Color Themes
## CAUTION: Colorscheme MUST be sourced after dein#end() on dein.vim.
[[plugins]]
repo = 'tomasr/molokai'
if = 'has("nvim")'
[[plugins]]
repo = 'sjl/badwolf'
if = 'has("nvim")'
[[plugins]]
repo = 'altercation/vim-colors-solarized'
if = 'has("nvim")'

### Status Bar
#[[plugins]]
#repo = 'itchyny/lightline.vim' # config is written in 'plugin.vim'
#hook_post_source = 'runtime! lightline.vimrc'
[[plugins]]
repo = 'vim-airline/vim-airline'
hook_post_source = 'runtime! airline.vimrc'
[[plugins]]
repo = 'vim-airline/vim-airline-themes'
depends = 'vim-airline'

### FZF
[[plugins]]
repo = 'junegunn/fzf'
[[plugins]]
repo = 'junegunn/fzf.vim'
hook_add = 'runtime! fzf.vimrc'

### Git
[[plugins]]
repo = 'tpope/vim-fugitive'
hook_add = 'runtime fugitive.vimrc'

### Denite
## Ref: extra.toml
## Ref: denite.vimrc
#[[plugins]]
### CAUTION: denite.vimrc MUST be sourced after dein#end() on dein.vim.
#repo = 'Shougo/denite.nvim'
#if = 'has("python3")'

### Defx
## Ref: defx.vimrc
[[plugins]]
repo = 'kristijanhusak/defx-git'
if = 'has("python3")'
[[plugins]]
repo = 'kristijanhusak/defx-icons'
if = 'has("python3")'
[[plugins]]
## CAUTION: defx.vimrc MUST be sourced after dein#end() on dein.vim.
repo = 'Shougo/defx.nvim'
if = 'has("python3")'
