#### From: dein.vim

### Required
[[plugins]]
repo = 'Shougo/dein.vim'
hook_add = '''
  set rtp+=~/.config/nvim/config.d/plugin.d
  '''
hook_done_update= '''
    au VimEnter :UpdateRemotePlugins<cr>
  '''

### Async Processor
#[[plugins]]
## run vim-plugins asynchronously, inc., quickrun.
#repo = 'Shougo/vimproc.vim'
#build = 'make'

### Color Themes
[[plugins]]
# CAUTION: DON'T source on lazy.
repo = 'tomasr/molokai'
if = 'has("nvim")'
hook_add = 'runtime! molokai.vimrc'
#[[plugins]]
#repo = 'altercation/vim-colors-solarized'

### Status Bar
#[[plugins]]
#repo = 'itchyny/lightline.vim' # config is written in 'plugin.vim'
#hook_post_source = 'runtime! lightline.vimrc'
[[plugins]]
repo = 'vim-airline/vim-airline'
hook_post_source = 'runtime! airline.vimrc'
[[plugins]]
repo = 'vim-airline/vim-airline-themes'
depends = 'vim-airline'

### FZF
[[plugins]]
repo = 'junegunn/fzf'
[[plugins]]
repo = 'junegunn/fzf.vim'
hook_add = 'runtime! fzf.vimrc'

### Git
[[plugins]]
repo = 'tpope/vim-fugitive'
hook_add = 'runtime! fugitive.vimrc'

### Deinte
[[plugins]]
repo = 'Shougo/denite.nvim'
if = 'has("python3")'
hook_add = 'runtime! denite.vimrc'

### Defx
[[plugins]]
repo = 'Shougo/defx.nvim'
if = 'has("python3")'
hook_add = 'runtime! defx.vimrc'
