#### From: dein.vimrc
#### Ref: appearance.toml

### Required
[[plugins]]
repo = 'Shougo/dein.vim'
hook_done_update= 'runtime reinstall.vim'

### Git
[[plugins]]
repo = 'tpope/vim-fugitive'
type = 'git'
hook_add = 'runtime fugitive.vimrc'

### Start Page
#[[plugins]]
#repo = 'mhinz/vim-startify'
#hook_add = 'runtime startify.vimrc'

### Which Key
## Uselees for <a-*>/<c-*>.
#[[plugins]]
#repo = 'liuchengxu/vim-which-key'
#hook_add = 'runtime which-key.vimrc'

### FZF
[[plugins]]
repo = 'junegunn/fzf'
hook_done_update = './install --all'
[[plugins]]
repo = 'junegunn/fzf.vim'
hook_add = 'runtime fzf.vimrc'

### Denite
## Ref: extra.toml
## Ref: denite.vimrc
[[plugins]]
## CAUTION: denite.vimrc MUST be sourced after dein#end() on dein.vim.
repo = 'Shougo/denite.nvim'
if = 'has("python3")'

### Defx
## Ref: defx.vimrc
[[plugins]]
repo = 'kristijanhusak/defx-git'
if = 'has("python3")'
[[plugins]]
repo = 'kristijanhusak/defx-icons'
if = 'has("python3")'
[[plugins]]
## CAUTION: defx.vimrc MUST be sourced after dein#end() on dein.vim.
repo = 'Shougo/defx.nvim'
if = 'has("python3")'

#### Color Themes
## CAUTION: Colorscheme MUST be sourced after dein#end() on dein.vim.
## Ref: appearance.toml
[[plugins]]
repo = 'morhetz/gruvbox'
if = 'has("nvim")'

### Status Bar
#[[plugins]]
## ERORR: g:lightline is undefined.
#repo = 'itchyny/lightline.vim' # config is written in 'plugin.vim'
#hook_add = 'runtime! lightline.vimrc'
[[plugins]]
repo = 'vim-airline/vim-airline'
hook_add = 'runtime airline.vimrc'
[[plugins]]
repo = 'vim-airline/vim-airline-themes'
