#### From: dein.vimrc

### Filer
[[plugins]]
repo = 'cocopon/vaffle.vim'
on_if = '!has("python3")'
hook_post_source = 'runtime vaffle.vimrc'

#### Jump
#[[plugins]]
#repo = 'jremmen/vim-ripgrep'
#on_if = 'executable("rg")'
#hook_post_source = 'runtime ripgrep.vimrc'

### Marks
[[plugins]]
# Show marks
repo = 'jacquesbh/vim-showmarks'
on_map = ['m','`',"'",'\<space>']
hook_post_source = 'runtime showmarks.vimrc'
[[plugins]]
repo = 'machakann/vim-sandwich'
on_event = 'BufRead'
hook_post_source = 'runtime sandwich.vimrc'
#[[plugins]]
#repo = 'tpope/vim-surround'
#on_event = 'BufRead'
#hook_post_source = 'runtime surround.vimrc'
