#### From: dein.vimrc

## Async Processor
[[plugins]]
# run vim-plugins asynchronously, like openbrowser, quickrun.
repo = 'Shougo/vimproc.vim'
build = 'make'

### Snippets
## Engine
[[plugins]]
repo = 'SirVer/ultisnips'
on_event = ['InsertEnter','TermOpen']
hook_post_source = 'runtime ultisnips.vimrc'
## Contents
[[plugins]]
repo = 'honza/vim-snippets'
on_event = ['InsertEnter', 'TermOpen']

### Tags
[[plugins]]
repo = 'jsfaint/gen_tags.vim'
on_event = 'BufLeave'
hook_post_source = 'runtime gen_tags.vimrc'
#[[plugins]]
#repo = 'majutsushi/tagbar'
#on_event = ['BufNew','BufReadPost']
#hook_post_source = 'runtime tagbar.vimrc'
[[plugins]]
repo = 'liuchengxu/vista.vim'
on_event = ['BufNew','BufReadPost']
hook_post_source = 'runtime vista.vimrc'

### Operator
[[plugins]]
repo = 'junegunn/vim-easy-align'
on_event = 'BufReadPost'
hook_post_source = 'runtime easy-align.vimrc'

### Code Runner
[[plugins]]
repo = 'skywind3000/asyncrun.vim'
on_map = 'AsyncRun'
hook_post_source = 'runtime asyncrun.vimrc'
[[plugins]]
repo = 'thinca/vim-quickrun'
on_map = 'QuickRun'
hook_post_source = 'runtime quickrun.vimrc'
[[plugins]]
repo = 'neomake/neomake'
on_map = 'make'
hook_post_source = 'runtime neomake.vimrc'

### Functional
[[plugins]]
# Repeats even not-default editing by "."
# e.g., surround.vim
repo = 'tpope/vim-repeat'
on_event = 'BufRead'

### Template
[[plugins]]
repo = 'mattn/sonictemplate-vim'
on_event = 'BufRead'
hook_post_source = 'runtime sonictemplate.vimrc'

#### UI
#[[plugins]]
#repo = 'wsdjeg/dein-ui.vim'
#hook_add = 'runtime dein-ui.vim'

### Emacs-Like
### Narrow Region
#[[plugins]]
#repo = 'chrisbra/NrrwRgn'
#on_event = 'VimEnter'
#hook_post_source = 'runtime NrrwRgn.vimrc'

