#### From: dein.vimrc

### Imput Method
[[plugins]]
# ERORR: Present Unnecessary Sign '>' on Kanji.
repo = 'tyru/eskk.vim'
on_event = ['InsertEnter', 'CmdlineEnter']
hook_post_source = 'runtime eskk.vimrc'

### Org Mode
[[plugins]]
repo = 'jceb/vim-orgmode'
on_ft = 'org'
hook_post_source = 'runtime orgmode.vimrc'
[[plugins]]
repo = 'dhruvasagar/vim-table-mode'
hook_add = 'runtime! table-mode.vimrc'
on_ft = ['org', 'text']
[[plugins]]
# For Hyperlink
repo = 'vim-scripts/utl.vim'
on_ft = 'org'
hook_post_source = 'runtime utl.vimrc'
#[[plugins]]
## <c-a/x> for dateing.
#repo = 'tpope/vim-speeddating'
#on_ft = 'org'
#hook_post_source = 'runtime speeddating.vimrc'

[[plugins]]
# Multiple-Language Syntax in one buffer.
repo = 'inkarkat/vim-SyntaxRange'
on_ft = ['snippets','org']
hook_post_source = 'runtime SyntaxRange.vimrc'

## Narrow Region
[[plugins]]
repo = 'chrisbra/NrrwRgn'
on_event = 'VimEnter'
hook_post_source = 'runtime NrrwRgn.vimrc'

### Matcher
[[plugins]]
repo = 'raghur/fruzzy'
on_ft = 'denite'
hook_post_source = 'runtime fruzzy.vimrc'

### Completion
[[plugins]]
repo = 'neoclide/coc.nvim'
on_event = 'BufRead'
hook_post_source = 'call coc#util#install()'
hook_post_source = 'runtime coc.vimrc'

## Async Processor
[[plugins]]
# run vim-plugins asynchronously, like openbrowser, quickrun.
repo = 'Shougo/vimproc.vim'
build = 'make'

### Snippets
## Engine
#[[plugins]]
#repo = 'SirVer/ultisnips'
#on_event = ['InsertEnter','TermOpen']
#hook_post_source = 'runtime ultisnips.vimrc'
[[plugins]]
repo = 'Shougo/neosnippet.vim'
on_event = ['InsertEnter', 'TermOpen','CmdlineEnter']
hook_add = 'runtime! neosnippet.vimrc'
### Contents
[[plugins]]
repo = 'Shougo/neosnippet-snippets'
on_event = ['InsertEnter', 'TermOpen','CmdlineEnter']
[[plugins]]
repo = 'honza/vim-snippets'
on_event = ['InsertEnter', 'TermOpen']
#[[plugins]]
#repo = 'garbas/vim-snipmate'
#on_event = ['InsertEnter', 'TermOpen']

### Template
[[plugins]]
repo = 'mattn/sonictemplate-vim'
on_event = 'BufRead'
hook_post_source = 'runtime sonictemplate.vimrc'

### Operator
[[plugins]]
repo = 'AndrewRadev/splitjoin.vim'
on_event = 'BufRead'
hook_post_source = 'runtime splitjoin.vimrc'
[[plugins]]
repo = 'junegunn/vim-easy-align'
on_event = 'BufRead'
hook_post_source = 'runtime easy-align.vimrc'

### Code Runner
[[plugins]]
repo = 'skywind3000/asyncrun.vim'
on_map = 'AsyncRun'
hook_post_source = 'runtime asyncrun.vimrc'
[[plugins]]
repo = 'thinca/vim-quickrun'
on_map = 'QuickRun'
hook_post_source = 'runtime quickrun.vimrc'
[[plugins]]
repo = 'neomake/neomake'
on_map = 'make'
hook_post_source = 'runtime neomake.vimrc'

### Functional
[[plugins]]
# Repeats even not-default editing by "."
# e.g., surround.vim
repo = 'tpope/vim-repeat'
on_event = 'BufRead'

#### UI
#[[plugins]]
#repo = 'wsdjeg/dein-ui.vim'
#hook_add = 'runtime dein-ui.vim'

### Linux Command
#[[plugins]]
## ERORR: Seems no utils provided by the plugin.
#repo = 'tpope/vim-eunuch'
#on_event = 'CmdlineEnter'
#hook_post_source = 'runtime eunuch.vimrc'

### Input Method
#[[plugins]]
## Doesn't Work
#repo = 'tpope/vim-capslock'
#on_event = ['InsertEnter', 'TermOpen', 'CmdlineEnter']
#hook_post_source = 'runtime capslock.vimrc'
#[[plugins]]
#### For Windows?
#repo = 'mattn/vim-switch-esc-capslock'
#on_event = ['InsertEnter', 'TermOpen', 'CmdlineEnter']
#hook_post_source = 'runtime switch-esc-capslock'
