#### From: dein.vimrc

### Completion
[[plugins]]
repo = 'neoclide/coc.nvim'
on_event = 'BufRead'
hook_post_source = 'call coc#util#install()'
hook_post_source = 'runtime coc.vimrc'

## Async Processor
[[plugins]]
# run vim-plugins asynchronously, like openbrowser, quickrun.
repo = 'Shougo/vimproc.vim'
build = 'make'

### Snippets
## Engine
[[plugins]]
repo = 'SirVer/ultisnips'
on_event = ['InsertEnter','TermOpen']
hook_post_source = 'runtime ultisnips.vimrc'
## Contents
[[plugins]]
repo = 'honza/vim-snippets'
on_event = ['InsertEnter', 'TermOpen']
#[[plugins]]
#repo = 'Shougo/neosnippet-snippets'
#on_event = 'InsertEnter'
#[[plugins]]
#repo = 'Shougo/neosnippet.vim'
#on_event = 'InsertEnter'
#depends = 'neosnippet-snippets'
#hook_add = 'runtime! neosnippet.vimrc'

### Template
[[plugins]]
repo = 'mattn/sonictemplate-vim'
on_event = 'BufRead'
hook_post_source = 'runtime sonictemplate.vimrc'


### Operator
[[plugins]]
repo = 'AndrewRadev/splitjoin.vim'
on_event = 'BufRead'
hook_post_source = 'runtime splitjoin.vimrc'
[[plugins]]
repo = 'junegunn/vim-easy-align'
on_event = 'BufRead'
hook_post_source = 'runtime easy-align.vimrc'

### Code Runner
[[plugins]]
repo = 'skywind3000/asyncrun.vim'
on_map = 'AsyncRun'
hook_post_source = 'runtime asyncrun.vimrc'
[[plugins]]
repo = 'thinca/vim-quickrun'
on_map = 'QuickRun'
hook_post_source = 'runtime quickrun.vimrc'
[[plugins]]
repo = 'neomake/neomake'
on_map = 'make'
hook_post_source = 'runtime neomake.vimrc'

### Functional
[[plugins]]
# Repeats even not-default editing by "."
# e.g., surround.vim
repo = 'tpope/vim-repeat'
on_event = 'BufRead'

#### UI
#[[plugins]]
#repo = 'wsdjeg/dein-ui.vim'
#hook_add = 'runtime dein-ui.vim'

