#### From: dein.vim

### Completion
[[plugins]]
repo = 'neoclide/coc.nvim'
hook_post_source = 'runtime! coc.vimrc'
on_event = 'VimEnter'
hook_done_update = '''
  call coc#util#install()
  CocInstall coc-json coc-tsserver coc-html coc-yaml coc-python
  CocInstall coc-vimlsp coc-git coc-yank coc-highlight coc-snippets
  '''

#### Snippets
#[[plugins]]
#repo = 'Shougo/neosnippet-snippets'
#on_event = 'InsertEnter'
#on_ft = 'snippets'
#[[plugins]]
#repo = 'Shougo/neosnippet.vim'
#hook_post_source = 'runtime! neosnippet.vimrc'
#on_event = 'InsertEnter'
#on_ft = 'snippets'

### Operator
[[plugins]]
repo = 'junegunn/vim-easy-align'
on_event = 'BufReadPost'
hook_post_source = 'runtime easy-align.vimrc'

### Org Mode
[[plugins]]
repo = 'jceb/vim-orgmode'
on_event = 'VimEnter'

### Code Runner
[[plugins]]
repo = 'skywind3000/asyncrun.vim'
on_map = 'AsyncRun'
hook_post_source = 'runtime! asyncrun.vimrc'
[[plugins]]
repo = 'thinca/vim-quickrun'
on_map = 'QuickRun'
hook_post_source = 'runtime! quickrun.vimrc'
[[plugins]]
repo = 'neomake/neomake'
on_map = 'make'
hook_post_source = 'runtime! neomake.vimrc'

### Template
[[plugins]]
repo = 'mattn/sonictemplate-vim'
on_event = 'BufRead'
hook_post_source = 'runtime! sonictemplate.vimrc'
#[[plugins]]
## preset a template respectively.
#repo = 'thinca/vim-template'
#on_event = 'BufReadPre'
#on_ft = 'bash'

### Start Page
[[plugins]]
repo = 'mhinz/vim-startify'
hook_post_source = 'runtime! startify.vimrc'

### Memo
[[plugins]]
repo = 'glidenote/memolist.vim'
hook_post_source = 'runtime! memolist.vimrc'
on_map = '<space>'

### Functional
[[plugins]]
# Repeats even not-default editing by "."
# e.g., surround.vim
repo = 'tpope/vim-repeat'
on_event = 'BufRead'
